### ISSUE TITLE
Create and add logo

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#1]
@mxstbr says he's cool with this:

![glamorous](https://cloud.githubusercontent.com/assets/1500684/24659270/65342540-1909-11e7-8029-c19bcb30acc3.png)

It's obviously inspired by styled-components:

![styled-components](https://cloud.githubusercontent.com/assets/1500684/24659279/6d89bb4c-1909-11e7-83d8-c6f7e8f6ddff.png)

Here's how I made it:

```html
<div style="
  width: 300px;
  height: 300px;
  display: flex;
  margin: auto;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  font-size: 60px;
  font-family: cursive;
  border: 2px solid;
">
  <div>&lt; 💄 &gt;</div>
  <div>glamorous</div>
</div>
```

Thanks Max!

**Comment by kentcdodds** [comment]
Based on feedback from @jdan, I changed it to:

![glamorous](https://cloud.githubusercontent.com/assets/1500684/24670972/495bd696-192d-11e7-91e3-a0636bba2cc8.png)

I like it because it demonstrates a more than slight difference to styled-components and even calls out the difference in the API being JS rather than CSS

```html
<div style="
  width: 300px;
  height: 300px;
  display: flex;
  margin: auto;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  font-size: 60px;
  font-family: cursive;
  border: 2px solid;
">
  <div>{ 💄 }</div>
  <div>glamorous</div>
</div>
```

**Comment by kentcdodds** [comment]
So I just upgraded to macOS Sierra and the lipstick emoji changed. So should we update the logo?

![glamorous-new](https://cloud.githubusercontent.com/assets/1500684/24957661/a6e3a3ee-1f49-11e7-8f9d-98af3e490b34.png)

I think I like the old one better.

Give this comment a :+1: if you like it better and think we should change or a :-1: if you like the original better or think we should keep it the same.

**Comment by hisk** [comment]
@kentcdodds Following the same styled-components logo feel, here is what I came up with:
<img width="415" alt="screen shot 2017-04-12 at 20 56 11" src="https://cloud.githubusercontent.com/assets/1017536/24972597/a051cabc-1fc4-11e7-8d4f-9196ae6e6259.png">

Smaller preview without border:
<img width="324" alt="screen shot 2017-04-12 at 21 06 05" src="https://cloud.githubusercontent.com/assets/1017536/24972636/c33541b2-1fc4-11e7-9267-5284f78cae8b.png">

The version rendered using glamorous and SVG can be found here: https://codesandbox.io/s/DlwAv2yA

**Comment by kentcdodds** [comment]
I'm going to think on this. Snoozing my email for a week or so... Anyone can feel free to add variations of their own if they like :)

**Comment by kentcdodds** [comment]
Ok, I've gotta get serious about this. I've made a few slight adjustments. I decided I want to keep the cursive font. I want to put this to a vote. I'll add a comment and screenshot for all the logo options. Please vote with emoji reactions!

I've decided to avoid sticking with proprietary emoji because (even though I love it), it's eh... proprietary, and I'd like to avoid copyright issues...

**Comment by kentcdodds** [comment]
[Custom SVG Emoji](https://codesandbox.io/s/qYQm101jr) from @hisk 

<img width="414" alt="screen shot 2017-04-17 at 11 21 33 am" src="https://cloud.githubusercontent.com/assets/1500684/25097060/268b9d80-2360-11e7-98d6-9d858b48e1d2.png">

**Comment by kentcdodds** [comment]
[EmojiOne](https://codesandbox.io/s/k8BJ8MNE)

<img width="410" alt="screen shot 2017-04-17 at 11 22 12 am" src="https://cloud.githubusercontent.com/assets/1500684/25097080/3af6fa08-2360-11e7-95ad-1e3d60888f8d.png">

**Comment by kentcdodds** [comment]
Feel free to put up your own if you feel like you've got better. Requirements:
1. Must be able to easily put it into: http://kcd.im/glamorous-help
2. Must be SVG
3. Must have open and free licensing

I have a strong preference for this general style and the cursive, but feel free to be as creative as you want.

**Comment by paulmolluzzo** [comment]
Vote cast.

> I've decided to avoid sticking with proprietary emoji because (even though I love it), it's eh... proprietary, and I'd like to avoid copyright issues...

Totally agree.

**Comment by satya164** [comment]
I like the first one you added, but the cursive `{` and `}` feel a bit weird

**Comment by satya164** [comment]
Probably more because the light grey colour and different stroke width than rest of the elements, and not because it's cursive

**Comment by kentcdodds** [comment]
Someone suggested we [rotate the second emoji](https://codesandbox.io/s/Wnv8k98Xn) to be inline with the surrounding braces:

<img width="411" alt="screen shot 2017-04-17 at 4 28 29 pm" src="https://cloud.githubusercontent.com/assets/1500684/25107179/f90aa330-238a-11e7-8bff-08d0cd2fcfe7.png">

**Comment by markdalgleish** [comment]
Cross-posting from Twitter.

I really wasn't a fan of the font, so I looked for an alternative—arrived at [Playfair Display](https://fonts.google.com/specimen/Playfair+Display), changing the colour to better match the emoji.

<img width="398" alt="screen shot 2017-04-19 at 8 55 04 am" src="https://cloud.githubusercontent.com/assets/696693/25156443/f2b0a62a-24dd-11e7-863d-10b04c5e17c7.png">

[(Source)](https://codesandbox.io/s/APr0mkGxO)

**Comment by kwelch** [comment]
I am a very big fan of the custom svg and I really like the font adjustment and color above.

**Comment by kentcdodds** [comment]
I really like what @markdalgleish has here. [Iterating on it a bit](https://codesandbox.io/s/D9O2NGE9B):

<img width="412" alt="screen shot 2017-04-18 at 9 35 18 pm" src="https://cloud.githubusercontent.com/assets/1500684/25163409/009e46fc-247f-11e7-842b-d4906082e979.png">

In my mind, this is a real winner. Anyone care to iterate further on this one? Otherwise I think we'll go with this.

**Comment by satya164** [comment]
The font feels a bit too thick. I'd suggest to have the same thickness for the font and the braces.

**Comment by satya164** [comment]
To convert to SVG, all SVG editors support converting fonts to outline, do it shouldn't be an issue.

**Comment by kentcdodds** [comment]
What about [this](https://codesandbox.io/s/mZrkQL633)?

<img width="410" alt="screen shot 2017-04-18 at 11 50 55 pm" src="https://cloud.githubusercontent.com/assets/1500684/25166823/f0a31b66-2491-11e7-84c8-a5ea10b7eb0e.png">

**Comment by kentcdodds** [comment]
I personally prefer the thicker font. It almost looks like you used the lipstick to draw it :)

**Comment by jamesmcallister** [comment]
Why not have a font logo inspired by actually writing in lipstick. 

Something like this. 
http://www.dafont.com/forum/attach/orig/3/8/382404.gif

(Sorry on mobile)

**Comment by kentcdodds** [comment]
Thanks for weighing in @jamesmcallister! I think that might be a _little_ too much based on [tips](https://twitter.com/sarah_federman/status/854593960043364352) from @sarahbethfederman.

**Comment by kentcdodds** [comment]
Thanks to @Connorelsea for making [this](https://imgur.com/a/0dsc3):

![hex](https://cloud.githubusercontent.com/assets/1500684/25288104/36c81a9c-2681-11e7-8b98-7e23cbe88234.png)

I think we're going to go with a combination of that and this from @markdalgleish!

<img width="412" alt="square" src="https://cloud.githubusercontent.com/assets/1500684/25288123/42da6452-2681-11e7-9486-5a298bfe3710.png">

Thanks everyone for weighing in!
