### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#10]
Could I get some people to look through the docs and file issues or [submit PRs](http://makeapullrequest.com) where it's unclear or could use an example? Thanks!

**Comment by paulmolluzzo** [comment]
There could definitely be some additional info included for SSR I think. See https://github.com/zeit/next.js/pull/1620#issuecomment-291747882

Also, there are some great examples included in [this Medium post](https://medium.com/@kentcdodds/introducing-glamorous-fb3c9f4ed20e) that might fit nicely in the README.

**Comment by kentcdodds** [comment]
Great idea! Would you like to make a pull request?

**Comment by paulmolluzzo** [comment]
@kentcdodds you bet!

**Comment by paulmolluzzo** [comment]
The README doesn't have examples o led extending components with `glamorous`, which is very accessible and powerful with this package.

If someone wants to add examples I already wrote a few here: https://github.com/paulmolluzzo/glamorous-jsxstyle/blob/master/README.md#usage

Can certainly be brought over here, and is a good task for a beginner to GitHub and/or `glamorous`. 😉

**Comment by paulmolluzzo** [comment]
@kentcdodds we should have a 'good for beginner' label (or something equivalent).

**Comment by dantesolis** [comment]
Hey guys I just read the medium blog post on glamour. Is anyone working on this and if not can I take it? 

Thanks

**Comment by paulmolluzzo** [comment]
@dantesolis go for it! 😀

This is more of an "open task" for now, so no one person needs to claim it. If someone sees an area that can be improved then a PR is welcome.

**Comment by dantesolis** [comment]
@paulmolluzzo thanks are there any other additional task that a beginner could tackled which have  not yet been claimed? Thanks

**Comment by paulmolluzzo** [comment]
This is the only issue with the `good first issue` label right now. 😕 We do plan to use that label so keep an eye out for it.

It's possible that you'll find an issue yourself using `glamorous` in some project, and finding new issues is also very helpful.

**Comment by kentcdodds** [comment]
This is an ongoing effort. I'll go ahead and close this now.
