### ISSUE TITLE
ForwardProps are not being forwarded

### ISSUE THREAD

**Issue by rbrewington** [paypal/glamorous#100]
- `glamorous` version: 3.5.0
- `glamor` version: 2.20.24
- `react` version: 15.4.2

What you did:
I tried to use glamorous to wrap a third party framework's component.

What happened:
My forwardProps did not get applied to the child of the glamorous component, and I was then able to reproduce the issue in the forwardProps example

Reproduction:

Below is the forwardProps example code.
"Hello worlds" should be rendered but is not:
https://codesandbox.io/s/GZEo8jOyy

Problem description:
forwardProps is not forwarding props

**Comment by kentcdodds** [comment]
Hi @rbrewington, thanks for bringing this up. I'm unsure what's going on, but the version of glamorous in that codesandbox was old so I've updated it and things seem to be working [now](https://codesandbox.io/s/GZEo8jOyy).

Could you try the latest version of glamorous?

**Comment by rbrewington** [comment]
Guess I should have checked myself before I wrecked myself. Thanks!
