### ISSUE TITLE
Allow passing propsAreStyleOverrides into the glamorous() composer

### ISSUE THREAD

**Issue by ajwhite** [paypal/glamorous#114]
There are occasions where it would be nice to access the "props as styles" feature, but that is only supported by the built-in components, unless you know where to look.

This can be accomplished by adding `propsAreStyleOverrides` as a property onto the `GlamorousComponent`

```js
const MyComponent = glamorous.div({backgroundColor: 'blue'})
MyComponent.propsAreStyleOverrides = true

<MyComponent color="white">Hello World</MyComponent>
// renders: <div />
// with styles {background-color: 'blue', color: 'white'}
```

When I do this, I can't help but feel that I'm doing something I'm not meant to do; that I'm hacking my way in. It would be great if I could tell the glamorous composer _how_ to configure the factory.

### Proposal

Allow passing `propsAreStyleOverrides` into the `glamorous()` composer.

```js
const MyComponent = glamorous(div, {propsAreStyleOverrides: true})({backgroundColor: 'blue'})

<MyComponent color="white">Hello World</MyComponent>
// ditto as above
```

Inspired by https://github.com/robinpowered/glamorous-native/issues/9#issuecomment-302571041

**Comment by ssomnoremac** [comment]
I like the proposal but what's the advantage setting the override either way? When would you not want to override with a styleProp? Is it a name collision with propRules that's the issue? In that case I'd say it's more important to have a specificity hierarchy.
Also, I can't find this approach in glamorous. What's it called there?

**Comment by ajwhite** [comment]
My understanding is to avoid unexpected behavior, and _explicitly_ opt-in: what if a component expects a property of the same name for a different reason? 

`glamorous` shouldn't assume every component it composes should conform to this style-prop interface. However built in components (`<glamorous.Div />`) are different - the library creates them, and as such, the library knows that `color="blue"` is not a property that might mean something else; it's meant as a style override. However, I could see the argument that the built-in's component factory function could also compose a component with these style-props enabled.

All the more reason for this proposal! As [the `glamorous()` composer](https://github.com/paypal/glamorous/blob/72c0305a3b2aa48b0447d56846e807ec7bd7105a/src/index.js#L21) could pass in `{propsAreStyleOverrides: true}`, and every component the factory function creates will support the style-props 😄 

> Also, I can't find this approach in glamorous. What's it called there?

It's called the same, here's a few references:
- Where it is assigned to the `GlamorousComponent`
 https://github.com/paypal/glamorous/blob/685dcde56a7f4ccef9d2bdcae771e86fe7657b65/src/index.js#L42
- Where it adds the style property to a set of "css overrides" (a set that will be used to create a style)
 https://github.com/paypal/glamorous/blob/2f224f7e96baf4b2b82084fb17c0e8e352703185/src/split-props.js#L31-L33
- And where those finally become integrated into the component's style
 https://github.com/paypal/glamorous/blob/72c0305a3b2aa48b0447d56846e807ec7bd7105a/src/create-glamorous.js#L95

**Comment by kentcdodds** [comment]
I've considered this... Adding it to the `glamorous` function (aka glamorousComponentFactoryFactory) as an option is one way to do it, but I wouldn't want to enable it for all DOM componentFactories. That would lead to a great deal of confusion IMO.

I'm honestly fine with the current setup of monkey-patching properties onto the component. We're already are used to this with `propTypes`, `defaultProps`, and `displayName`. I don't see how this really needs to be any different.

**Comment by ssomnoremac** [comment]
I beginning to think we should keep it as is. Having it as an option object
I agree might confuse people as they are the same type as the passed
styles. I'm a big proponent of using styleProps for layout but creating
glamRules and passing uniquely (not a RN style) named props is a better
pattern anyway. Once we can get those cached I think I'll be able to use
this in my app.

**Comment by ajwhite** [comment]
> We're already used to this with `propTypes`, `defaultProps`, and `displayName`

Good point -- it's not far off the beat and path. And with that, I'm closing this as this reminder changes my original perception.

----

> Having it as an option object I agree might confuse people as they are the same type as the passed styles. 

That's not quite what this is proposing. The styles happen when you call the **factory function**, this is calling the `glamorous` function, _which creates_ the factory function.

```js
const glamorousFactoryFunction = glamorous(component, OPTIONS)
const GlamorousComponent = glamorousFactoryFunction(STYLES)
```

This proposes that we allow it as another option [to the existing options](https://github.com/paypal/glamorous/blob/72c0305a3b2aa48b0447d56846e807ec7bd7105a/src/create-glamorous.js#L24)

**Comment by ssomnoremac** [comment]
@ajwhite , thanks for clarifying that. Is it a concern that even a contributor is getting lost in the api? 🤔

**Comment by ssomnoremac** [comment]
Ha, I didn't even realize this issue was in glamorous and not glamorous-native. Ok, it's been a long week.

**Comment by ajwhite** [comment]
FWIW - glamorous-native is built entirely in the same way as things are done here - the only differences in determining valid styles and props for the underlying element

**Comment by ssomnoremac** [comment]
and the caching of styles, which I need to look at.

**Comment by ajwhite** [comment]
Added in #258!
