### ISSUE TITLE
Support context

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#125]
It'd be useful to be able to do:

```javascript
const MyDiv = glamorous.div((props, theme, context) => ({ /* my styles */ }))
MyDiv.contextTypes = { /* context types */ }
```

I've not really used context a ton, so I'd appreciate feedback on this API before anyone start working on it. cc @kenwheeler

**Comment by kentcdodds** [comment]
Potentially could do:

```javascript
const MyDiv = glamorous.div((props, theme) => ({ /* props.context has context? Maybe kinda confusing... */ }))
MyDiv.contextTypes = { /* context types */ }
```

**Comment by kentcdodds** [comment]
What if we made a breaking change. So folks using theme today like:

```javascript
const MyDiv = glamorous.div((props, theme) => ({ /* my styles */ }))
```

Would have to do:

```javascript
const MyDiv = glamorous.div((props, {theme}) => ({ /* my styles */ }))
```

The difference being that the second argument is the `context` object which you're destructuring. I think that's acceptable. We could even create a codemod for that easily 👍

**Comment by ajwhite** [comment]
I like the the original proposal of the 3 named arguments

```js
glamorous.div((props, theme, context) => ({})
```
However it won't scale nicely if more options are introduced later, and we have this leap-frog effect where we go from 
```js
(objFromReact, objFromGlamorous, objFromReact, objFromGlamorous, ...) => ...
```
And then the interface feels a bit fuzzy.

➡️ I like the idea of having the second argument be an object of "other options" that deviate from the most common denominator of working with props -- themes, contexts, and anything else down the pipeline. 👍

**Comment by vesparny** [comment]
What would be a use-case for this feature?
I always thought about context as a thing to use for theming and stuff like that.

If someone really needs context within a glamorous component I think it's possible tu require context from parent and send down to glamorous comp via props.

**Comment by kentcdodds** [comment]
For context (no pun intended), this issue was inspired by [this thread](https://twitter.com/kentcdodds/status/867034742973231104).

I like the idea of enabling glamorous components to do everything that regular function components can do (they can already do `propTypes` and `defaultProps` so it's a shame that you cannot do `contextTypes` too). One use case would be if you want to style things differently based on whether it matches the react-router route for example. I wouldn't want to make a HoC just for that. :)

**Comment by kentcdodds** [comment]
Oh, and I really don't see us adding more options in the future. Unless we want to do something weird with state (which I don't think we do), I think that `(props, context)` is the full API that these could accept. With that said, does anyone have issues with that API?

**Comment by kwelch** [comment]
I really like the idea of matching the api for stateless components.

**Comment by ajwhite** [comment]
>  I wouldn't want to make a HoC just for that. :)

Exactly 😄  the library is meant to remove  that 🎶  and 💃 

> don't see us adding more options in the future.

👍  

The only thing that feels finicky to my eyes is the order of the properties

```js
(props, theme, context) => ..
(objFromReact, objFromGlamorous, objFromReact) =>
```

As mentioned above, if there's willingness to introduce a breaking change, which of the following is more appealing?

```js
// 3 arguments
(props, context, theme) => ...

// 2 arguments, last can be destructured
(props, {context, theme}) => ...
```

**Comment by kentcdodds** [comment]
You know, I actually like this better:

```
(props, {context, theme}) => ...
```

Than what I originally thought of:

```javascript
(props, context) => /* theme on context.theme */...
```

Because it would be odd to monkey-patch `theme` onto `context`. I think that's what I want to go for :+1:

**Comment by kentcdodds** [comment]
However, there _is_ something to be said for:

> I really like the idea of matching the api for stateless components.

🤔 I think it's time to vote. I'm going to post a few possible solutions. Please add a :+1: to your favorite and a :-1: to your least favorite...

**Comment by kentcdodds** [comment]
```js
const MyDiv = glamorous.div((props, theme, context) => ({ /* my styles */ }))
MyDiv.contextTypes = { /* context types */ }
```

**Comment by kentcdodds** [comment]
```js
const MyDiv = glamorous.div((props, context, theme) => ({ /* my styles */ }))
MyDiv.contextTypes = { /* context types */ }
```

**Comment by kentcdodds** [comment]
```js
const MyDiv = glamorous.div((props, {context, theme}) => ({ /* my styles */ }))
MyDiv.contextTypes = { /* context types */ }
```

**Comment by kentcdodds** [comment]
```js
const MyDiv = glamorous.div((props, context) => ({ /* theme is on context.theme */ }))
MyDiv.contextTypes = { /* context types */ }
```

**Comment by ajwhite** [comment]
I like that option 4 conforms to the React API, however, I am trying to better my understanding of what this would actually look like. Since the `context` uses the `__glamorous__` name (`CHANNEL`), `theme` wouldn't technically be on the React `context` as a `contextType`, as nothing defines `theme` as a `childContextTypes`.

This leads to a couple thoughts:
- It sounds like we'd be "patching" `theme` onto `context`, which if the motivation is to conform to the React API, this detail deviates away from it, which undermines the original motivation
- To access values on `context`, the component needs to define them on `contextTypes`. To truely conform to the React APIs, users looking to use `theme` would now have to specifically "opt in" by adding `contextTypes = {theme: PropTypes.hopefullyTheyKnowWhatType}`. Does this feel a bit like a leaky abstraction? 
- If we add `them` to the `context`, is this too generic of a name that it could lead to collisions?

At face value `glamorous.div((props, context) => ..)` sounds beautiful, but achieving this comes with a few questions/concerns

**Comment by kentcdodds** [comment]
So here's the issue as I see it:

Mirroring the React function component API says we should do:

```js
(props, context) => ...
```

However, because of the leaky abstraction as you referenced, it would be nice to add a theme:

```js
(props, context, theme) => ...
```

However, it's unlikely that folks will often need `context` as often as they would need `theme`, so having `context` first would be super annoying. Could do this:

```js
(props, theme, context) => ...
```

But then it's not the same as the function component API which could be confusing. So we could just embrace the difference:

```js
(props, {theme, context}) => ...
```

Or we _could_ have the function component API if we didn't care about monkey-patching `theme` onto `context`:

```javascript
(props, context) => ...
// most folks would just do:
(props, {theme}) => ...
```

But then there's the potential name collision. I'm ok with that if there's a workaround. What could we do to workaround that problem?

**Comment by ajwhite** [comment]
Great - we're in the same headspace. Here's what I see as a good workaround: 

glamorous' `theme` is monkey-patched onto `context`. As `contextTypes` defined by the user are also made available on `context`, if there is a `theme` collision, the user's `context.theme` takes priority.

----

By default, glamorous' `theme` is monkey-patched onto `context`.

```js
(props, {theme}) => ({ /* theme is from glamorous */ })
```

If the developer has a `theme` `context` in their application, they'd access **theirs** by adding it as a `contextTypes` definition, per usual:

```js
const MyDiv = glamorous.div((props, context) => ({ /* theme is from user's context */ }))
MyDiv.contextTypes = {theme: customThemeShape}
```

This should achieve what we want here, while also gracefully handling conflicts by deferring priority to the specified `contextTypes`

**Comment by kentcdodds** [comment]
Sounds great to me! And based on the votes this is the most popular option :+1: Let's go forward with this. Who wants to implement it? 😄

**Comment by ajwhite** [comment]
Happy to throw up a PR

**Comment by kentcdodds** [comment]
Here's the beginnings of a codemod: https://astexplorer.net/#/gist/ea198ff18c51954cc6ef3f682257c469/7aeaa5687f42eac78852aaa8f6277a2f04f28272

If someone could package this up so folks can use [babel-codemod](https://github.com/square/babel-codemod) with it, that'd be super cool. Who wants to do that?

**Comment by kwelch** [comment]
@kentcdodds, May want to add a case to that codemod to catch destructing the theme. I know that is my go to usage of theme.

**Comment by kentcdodds** [comment]
Haha, yeah, [just realized that](https://github.com/paypal/glamorous/pull/127#discussion_r118080709) 😅 I may be able to get to it eventually. I don't personally use `theme`, so I'm not sure I'll get to it. Do you wanna handle that? :)

**Comment by ajwhite** [comment]
https://github.com/paypal/glamorous/pull/127 is all merged up; docs are next ✍️ 📖

**Comment by kentcdodds** [comment]
Oh yeah 😅, forgot we need that still :)

**Comment by kwelch** [comment]
I forked and gave a shot at it put, I am having issues with using the `objectPattern` as the value of the new `objectProperty`. 

Here is the fork is anyone wants to take it further. 

https://astexplorer.net/#/gist/8a5451d073317c91eab45bf595ea5d3e/c0f73028c0ff7fefe7f175807db9bea801157d60

**Comment by kentcdodds** [comment]
Looks like this is a bug that was just fixed: https://github.com/babel/babel/pull/5762

**Comment by jfrolich** [comment]
I don't like this. First because context should not be used directly as the API is going to change later. And secondly it's a breaking change. If we do this, and most probably you don't want to do this because of (1), why not pass it in as a third argument and not have a breaking change in the API. Honestly you can use the themeprovider not to use context directly in your glamorous components. If you have other context I would suggest to use a withOtherContext HOC that passes that specific conext as a prop.
Also I don't use theme, but branding as a variable name, so the change is going to run more ugly.

**Comment by kentcdodds** [comment]
Thanks for adding in your perspective @jfrolich! You've convinced me! I think I got lost in finding the solution so much that I didn't think about the value of actually solving the problem. Now I'm thinking that it's actually _more_ valuable to preserve the current API than it is to have the dynamic styles have a similar API to function components. So how about this:

```javascript
(props, theme, context) => ...
```

That way it's possible to use context, but most folks will never have to care about it.

The use-case of the router context being relevant for styles is also bunk as I've realized because folks would use the `withRouter` HoC anyway.

Luckily, we only merged the changes to the `next` branch, so it hasn't actually been released yet. @ajwhite, would you be willing to make another PR to `next` to change things to `props, theme, context`? I think it'll simplify a lot of things and it wont actually be that terrible an API anyway.

Thank you so much @jfrolich. Your feedback was very helpful!

**Comment by jfrolich** [comment]
If supporting context I like it more that way. Yeah it will be a bit less accessible, *but* it is for a exceptional use case and it does not break any API.

I am not the only one, so perhaps the popular opinion will be different. But thanks for listening :)

**Comment by kentcdodds** [comment]
@jfrolich 
> perhaps the popular opinion will be different. 

I expect that many folks hearing your perspective will agree. But at the end of the day, sometimes it's better to go with the less popular opinion to do the right thing. We're going to do this :)

**Comment by ajwhite** [comment]
@kentcdodds since #127 was the only breaking change in `next` (#128), WDYT about 🔥 `next`, or at least reverting #127, and then putting a PR into `master` with the compatible approach described here?

**Comment by kentcdodds** [comment]
I'm working on updating `next` for these changes and I'll merge that. I don't mind keeping this history in the repo :)

**Comment by ajwhite** [comment]
Okay! Will target `next` 👍

**Comment by ajwhite** [comment]
Oh sweet, looks like you've got got this over in 6a25d74

**Comment by kentcdodds** [comment]
Ok, here we go: https://github.com/paypal/glamorous/pull/130

**Comment by kentcdodds** [comment]
Looks great! And this was commit `100`!

**Comment by jfrolich** [comment]
I was looking at the docs of styled components, and there the `theme` is passed as part of the `props`. What do you think of that. I am not sure, but maybe that makes it simpler than passing it as a separate argument?

**Comment by kentcdodds** [comment]
That's interesting. I think I like that better. Not keen on making a breaking change. However, there is an effort to standardize around a single theming solution: https://github.com/iamstarkov/theming

I haven't used it or looked at it yet, but it seems like we may be able to just use that instead. At that point we could have a breaking change like this 🤔
