### ISSUE TITLE
Create a website

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#129]
I started some work on the glamorous website a while back and haven't had as much time as I would like to actually finish it. Here's the [CodeSandbox](https://codesandbox.io/s/59XX9B1MR).

I think that our docs are sufficiently large that a website would be really helpful. I would love it if someone take this over and be in charge of shipping the website.

Localization is important, so I'd like that to be possible. I was playing around with some i18n abstractions and think it's actually pretty good (though it currently requires all translations to be shipped with the JavaScript). For the actual documentation pages, I expect to have them in markdown files in the repo. I'd love to do what the [babel-handbook has done](https://github.com/thejameskyle/babel-handbook/blob/master/CONTRIBUTING.md) to do translations. I think that would be great.

I'm not married to the website that I've worked on. If someone else wants to build something from scratch that'd be great. I think that it'd be cool to put the website in the `/site` folder. Who wants to help with this?

**Comment by hozefaj** [comment]
@kentcdodds I can help here. But will need some guidance on this, as have experience in creating  a site for documentation on github.

**Comment by kentcdodds** [comment]
Cool. How can I help?

**Comment by sirJconny** [comment]
@kentcdodds @hozefaj let me know if I can be give assistance!

**Comment by kentcdodds** [comment]
Why don't ya'll just give it a go whenever you have time and report back here with your progress :)

**Comment by hozefaj** [comment]
Guessing we can use the CodeSandbox and move forward with it. @sirJconny created a fork of it(https://codesandbox.io/s/NxjjDKQ9v). Lets use this for further work.

**Comment by liadbiz** [comment]
I would like to help with this :smile:

**Comment by kentcdodds** [comment]
Everyone can feel free to get started and we'll see where everyone gets in their progress :)

**Comment by liadbiz** [comment]
I have add chinise locale on my fork. Here is the [codesandbox](https://codesandbox.io/s/869zwrqQg). 
I have no idea what to do next....so what's your idea?
@kentcdodds @hozefaj @sirJconny

**Comment by kentcdodds** [comment]
I think the next steps would be to download the codesandbox and put it into a new `/docs` directory in this repo (in your fork). Then to wire up loading the `md` files for the docs and guides pages.

**Comment by paulmolluzzo** [comment]
I recommend we use `[next](https://github.com/zeit/next.js)` to build the site. We'll get SSR and can rehydrate styles with a custom `_document`. [Here is an example built with `next`](https://github.com/zeit/next.js/tree/master/examples/with-glamorous).

`styled-components` just released their v2 and [their new website](https://www.styled-components.com/), also built with `next`. You can view the source here: https://github.com/styled-components/styled-components-website. Not only is their site gorgeous, it's super fast.

**Comment by kentcdodds** [comment]
Agreed. Let's do that. Their site is amazing!

**Comment by liadbiz** [comment]
ok, I have time all day now, but I have no experience build site with next before.
I will post here if I have made progress.

**Comment by sirJconny** [comment]
@liadbiz you can reach out to me personally on Gitter if you need any help. I am available to talk but won't have time to really code until later this evening 🙂

**Comment by kentcdodds** [comment]
Feel free to use the [glamorous gitter](https://gitter.im/paypal/glamorous) as well if you like.

**Comment by jonmajorc** [comment]
That sounds good to me @paulmolluzzo. @kentcdodds let us know when 1 and 2 are completed.

**Comment by kentcdodds** [comment]
https://github.com/kentcdodds/glamorous-website

What do you all think of https://glamorous.rocks/ ?

**Comment by hozefaj** [comment]
https://glamorous.rocks/ rocks!!! Lets go with that.

**Comment by kentcdodds** [comment]
Done! I'm unsure what I need to do with DNS settings to get `now` working. Anyone know?

**Comment by paulmolluzzo** [comment]
@kentcdodds https://zeit.co/world#1.-point-your-domains-to-our-nameservers

**Comment by kentcdodds** [comment]
I _think_ that I've got the nameservers updated, so we could give it a try right now :)

**Comment by paulmolluzzo** [comment]
I'm seeing the site! 🎉

**Comment by kentcdodds** [comment]
Closing this. The effort is definitely going! People are welcome to [help](https://github.com/kentcdodds/glamorous-website/issues)!
