### ISSUE TITLE
Support custom props

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#133]
So styled-components v2 was released with a cool new [`attrs` API](https://www.styled-components.com/docs/basics#attaching-additional-props).

With glamorous, in our examples, we say you can do:

```javascript
const Password = glamorous.input({})
Password.defaultProps = { type: 'password' }
```

That works great unless you want the value to be dynamic and derived from props. The example they have is a little unnecessary, but I could see a situation where you'd want to have the props you pass to a wrapped component be mapped to some other value. So I wonder whether folks think this would be useful or just make things more complex.

### Option 1: Leave things as they are:

```javascript
const ValidatedInput = glamorous(({validationType, ...rest}) => {
  let extraProps = {type: validationType}
  if (validationType === 'credit-card') {
    extraProps = {pattern: creditCardPattern}
  }
  return <input {...extraProps} {...rest} />
}, {rootEl: 'input'})({
  /* styles */
})
```

### Option 2: Add an API:

```javascript
const ValidatedInput = glamorous.input({/* styles */}).props(({validationType}) => {
  if (validationType === 'credit-card') {
    return {pattern: creditCardPattern}
  }
  // validationType could be `email`, `url`, etc.
  return {type: validationType}
})
```

I value small APIs, but I also value ergonomics. I would love to hear people's perspectives on this. I'll open this up for a vote after we hear what folks have to say about this.

**Comment by liadbiz** [comment]
IMO option2 is better because it's more consistent to style the component.
Only write css in api like glamorous.input(), and do not add custom property stuff to that.
if user want to add custom properties, just use another api like `.props` or `.attrs`

**Comment by jfrolich** [comment]
or maybe:
```es6
import glamorous, { withProps } from 'glamorous'
const ValidatedInput = withProps(() => ())(glamorous.input({}))
```
An API that specifies the prop manipulation first before the glamorous component is a bit more intuitive for me because the prop manipulation happens first.

**Comment by kentcdodds** [comment]
I like that. How about:

```javascript
import glamorous from 'glamorous'
const ValidatedInput = glamorous.input.withProps(props => ({}))(styles)
const ValidatedInput2 = glamorous(Input).withProps(propsFun)(styles)
```

I think that should be fairly straightforward :+1:

**Comment by kentcdodds** [comment]
Let's do that. Who wants to work on this!? :smile:

**Comment by marzelin** [comment]
This feature is super useful but is this a concern that a styling library should tackle? :thinking: 
I'm proponent of a Unix philosophy "do one thing and do it well".
Can we focus on solving styling components and this great feature move to a different library?

**Comment by kentcdodds** [comment]
I've been considering this as well. Why don't we just have:

```javascript
import {withProps} from 'with-props'

const StyledInput = glamorous.input({/* styles */})

const ValidatedInput = withProps(StyledInput)({validationType}) => {
  if (validationType === 'credit-card') {
    return {pattern: creditCardPattern}
  }
  // validationType could be `email`, `url`, etc.
  return {type: validationType}
})
```

Fun fact, this already exists! [`recompose.withProps`](https://github.com/acdlite/recompose/blob/master/docs/API.md#withprops).

So maybe instead of doing this built-into the library, we should make an integration example with recompose?

`withStyles` does make sense though 🤔 I don't think that we could use recompose with that. However maybe we could make the API be more out-of-band:

```javascript
import {withStyles} from 'glamorous/with-styles'
```

Rather than making it part of the glamorous component API itself? Let's continue discussion on https://github.com/paypal/glamorous/issues/145

**Comment by marzelin** [comment]
Integration example would be great but in a separate document. Our Readme is waaay to long already IMHO.

I can also imagine an umbrella library for react helpers named `rodash` or `lodashr` if we invent something new or will be dissatisfied with existing solutions.

**Comment by kentcdodds** [comment]
Yes, this would go in the examples folder. We're working on a website right now. Help is appreciated! Anyone can feel free to add an example in the mean time. See the continuing guidelines 😀

**Comment by jfrolich** [comment]
Great point @marzelin!

**Comment by wellguimaraes** [comment]
For non dynamic props, how pricey would be `glamorous(<input type="password" />)({ ... })`?

**Comment by ajwhite** [comment]
Not pricey at all, @wellguimaraes!

The `glamorous` function requires a component definition, rather than a JSX element, so you'll want to do:

```jsx
glamorous(() => <input type="password" />)({ ... })
```

Or you could also use [recompose's `withProps`](https://github.com/acdlite/recompose/blob/master/docs/API.md#withprops)

```jsx
const PasswordInput = withProps({type: 'password'})(input);
glamorous(PasswordInput)({ ... })
```

**Comment by paulmolluzzo** [comment]
> Or you could also use recompose's withProps
> 
> ```js
> const PasswordInput = withProps({type: 'password'})(input);
> glamorous(PasswordInput)({ ... })
> ```

TIL. 🙌  @ajwhite !

![](https://media.giphy.com/media/83QtfwKWdmSEo/giphy.gif)

**Comment by ajwhite** [comment]
Many, many gems in that library @paulmolluzzo! Definitely suggest skimming through

**Comment by wellguimaraes** [comment]
@ajwhite Yep, I know, but the idea on using a JSX element is to simplify things (pure sugar), and than glamorous could do the job.

**Comment by Pajn** [comment]
>Can we focus on solving styling components and this great feature move to a different library?
Many React components gets styled by props however. I think how styled-components `.attrs` function works is very natural with that library and would work equally great in this.

I use recompose as well and withProps sure works great but when migrating from styled-components to glamorous having to add withProps to a lot of styled components just to pass a style prop as well do feel clunky,

**Comment by kentcdodds** [comment]
Hmmmmm... I'm not promising that I'll accept it, but I'd be willing to look at a pull request that adds this feature.

**Comment by kentcdodds** [comment]
lol, I just realized... we _already_ have a pull request that adds this feature! :P

**Comment by kentcdodds** [comment]
I just can't bring myself to want to add this to core. "When does it stop?" is the question I just can't answer if we bring something like this in. Going to stick with the `recompose` suggestion.

@Pajn, could you give an example of what kind of stuff you're doing that requires `withProps`?

**Comment by Pajn** [comment]
>"When does it stop?"

With props. State (as discussed in the PR) has nothing to do with styling while props usually do. And you already have the ability to replace the component which could be argued is in the same realm.

>could you give an example of what kind of stuff you're doing that requires withProps?

Requires is a strong word as I'm using recompose and thus can do it "anyway" and there are other ways to do it like creating a SFC while creating the styled component. But examples on things were I prefer the props API that styled-components provides is:
- Sometimes I like to base my styled components on things like [these](https://github.com/beanloop/styled-material/blob/master/src/layout.ts) or [flexbox-react](https://github.com/nachoaIvarez/flexbox-react) as "a centered column with a red border" is more clear than "this div with CSS properties for layout, styling, animations etc."
- When I use a component framework for styling but want to change something, for example react-toolbox. Often there are some props to control styling (`<Button>` in react-toolbox have things like `raised`, `flat` etc.) but I might have to use custom CSS properties for things like setting a specific width or something.
- If I have a hierarchy of styled components I might have to take some properties in the base layer components to have them general enough and then the very specific components on top of them provide these props as well as additional CSS properties. Sure, I could move some of these CSS properties to the more specialized components but that does in some cases defeat separation and generalization a bit. For example if I implement material design I might make a base component for text that depending on a light prop for setting the text to 54% instead of 87% opacity and when I use that to implement all defined type sizes I no longer have to know the exact percentages of text color material design uses.

In my mind libraries like this and styled-components takes a generic component and turns it into a specialized component, I don't really care where that generic component comes from. If that generic component comes from html and is for example a `<button>` the current behavior fully allows me to style that to an `<ActionButton>` that is customized for my app. But if I instead base my button on `<Button>` from react-toolbox I have to use other techniques as well which feels like there's a hole in the API for me.

**Comment by marzelin** [comment]
@Pajn out of curiosity, why are you switching from `styled-components` to `glamorous`?

**Comment by Pajn** [comment]
@marzelin 
Currently I'm just experimenting in personal project. I still use styled-components professionally but the reasons that I'm doing that is mostly Typescript typings but other connected stuff like not needing to ship an CSS parser, not having to think in two languages is a bonus too.
styled-components works great so there is no big reason. I just see how some of the decisions taken by glamorous may fit better in the way I code.

**Comment by marzelin** [comment]
@Pajn 
I thought about your arguments and that's what I think:
`props` are for describing component 'state', not for its presentation.
Writing something like
```javascript
<Flexbox flexDirection="column" minHeight="100vh">
```
instead of directly specifying css for the component saves a few keystrokes but pollutes props namespace. The place for presentational description is in css, not in props.

What people should do is start sharing just styles, not whole components, ie:
```javascript
export FlexboxStyle = {
    display: "flex",
    minHeight: "100vh"
}
```
and then
```javascript
import { FlexboxStyle } from "style-lib"

const Comp = glamorous.div(FlexboxStyle)
```
or
```javascript
import { FlexboxStyle } from "style-lib"
import { otherStyle } from "other-style-lib"

const Comp = glamorous.header({
    ...FlexboxStyle, 
    ...otherStyle
})
```

btw I've noticed you use typescript (I :heart: typescript!). What do you think about `typestyle`?

**Comment by ericm546** [comment]
I have an application that is themable, so a user can change colors for hours. I also have a place where some styles depend on the mouse position. In these 2 scenarios, if I just use glamorus, I could easily have thousands of unused styles in the head tag. 
I could use recompose for these cases, but I still think it would be nice to have a .props and set everything related to styling in glamorous without external dependencies.

**Comment by kentcdodds** [comment]
@ericm546, I think we should clarify that:

1. Every time a component's styles change, it gets a new class.
2. glamor takes care of things so the head tag doesn't get overloaded with styles.

This feature would not help (or hurt) you with regards to the concerns you mentioned.

**Comment by ericm546** [comment]
what I was thinking of doing was :
glamourous.div({position:'absolute', other static styles})
.props(props=> {style: {left: props.x, other highly dynamic style}})

but what you are saying is that if just do
glamourous.div(props => {position:'absolute', left: props.x}),  it should be performant even if it change every 12ms and eventually glamorous will clean up the head tag?

**Comment by kentcdodds** [comment]
Oooooh! I see now :+1: That does make sense. Hmmm... Yeah, ok, I think ya'll have convinced me of this! 🎉 

Let me ask you this question now. What part of this API do you not like? Would you like all of it, some of it, or none of it?

```javascript
import glamorous, { withProps } from 'glamorous'

const withPropsObject = {propA: 'a', propB: 'b'}

// withProps functions accept the same arguments that glamorous style functions accept.
const withPropsFunction = (props, theme, context) => ({propG: 'g', propH: 'h'})

// we'll call these withPropsThing, meaning when you see withPropsThing it could be either a function or object

const Div1 = glamorous.div({}).withProps(withPropsThing)
<Div1 /> // renders div with the props, filters out invalid `div` props like we do currently.

const Div2 = Div1.withProps(withPropsThing)
<Div2 /> // renders div with the props. Overrides any conflicting props. Still filters

const Div3 = withProps(Div1, withPropsThing)
<Div3 /> // what you'd expect

const Div4 = withProps(glamorous.div({}), withPropsThing)
```

What do you all think?

**Comment by kentcdodds** [comment]
Oh, and WRT your question @ericm546, I think @threepointone could answer that better...

> but what you are saying is that if just do
> glamourous.div(props => {position:'absolute', left: props.x}), it should be performant even if it change every 12ms and eventually glamorous will clean up the head tag?

**Comment by threepointone** [comment]
No, I'm afraid. Would not recommend glamor for values that change across large ranges many times (like animations). Recommend inline styles for the same.

**Comment by ericm546** [comment]
@kentcdodds, Personally, I would love to have the syntax glamorous.div({}).withProps(withPropsThing), but I have no opinion about the other ways of doing it.

**Comment by kentcdodds** [comment]
@ericm546, I think that we'll just support that to start. Then we can expand it later if folks thinks it's necessary.

**Comment by kentcdodds** [comment]
I realized that this could be really simplified if we could get refactoring needed to prep for #175 finished. It's not as simple as I thought. If anyone wants to try it out, that'd be cool.

**Comment by kentcdodds** [comment]
The refactor is done and @ajwhite says he should be able to get the feature done soon.

I think that I want to have it as part of our next breaking release. We'll be releasing the website and a bunch of other stuff at the same time. #hype :wink:

Should hopefully be in a week or two.

**Comment by kentcdodds** [comment]
This has been merged into `next` which will be released 🔜 (within a week hopefully)
