### ISSUE TITLE
Improve Server Side Rendering

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#134]
The [styled-components v2 announcement blogpost](https://medium.com/styled-components/announcing-v2-f01ef3766ac2) states:

> When you server-side render an app with 💅 styled-components it will automatically only send the critical CSS down to the client.

I'm pretty sure that we don't actually do that right now. As soon as you say:

```javascript
const Button = glamorous.button({ /* styles */})
```

Those styles get added to glamor... wait...

jkjk, we totally don't add them to glamor until rendering time. Just verified this with:

```javascript
import React from 'react'
import ReactDOM from 'react-dom'
import {styleSheet} from 'glamor'
import glamorous from '../'

const Button = glamorous.button({marginLeft: 20})
console.log(styleSheet.inserted)
// -> {}
const x = <Button />
console.log(styleSheet.inserted)
// -> {}
ReactDOM.render(x, document.createElement('div'))
console.log(styleSheet.inserted)
// -> { '140tz9x': true }
```

So I think we're good. EXCEPT!

We _could_ probably improve the experience a bit. If you look at the Next.js example for server side rendering [here](https://github.com/zeit/next.js/blob/master/examples/with-glamorous) there's a bit of boilerplate, and the styled-components blogpost says:

> On top of that we support concurrent server-side rendering to avoid blocking your process with every request and we automatically rehydrate your styles in the browser.

And further:

> All it takes is four lines of code

Let's see if we can improve this experience a bit taking inspiration (again) from styled-components :)

**Comment by nitin42** [comment]
I'd like to work on it (assuming this is still open).

**Comment by kentcdodds** [comment]
Awesome! Yeah! Let me know what you're thinking for doing :)

**Comment by nitin42** [comment]
Sure!

**Comment by nitin42** [comment]
Possible solution :

Whenever an app is rendered on the server, we need to include the generated styles on the pages. This can be done by passing a component to a callback which will return html or array of React elements. Further, taking inspiration from styled-components, we could gather all the style tags and include the extracted css in the html  by creating an instance of `ServerStyleSheet` and pass array of React elements (return by the callback, eg - renderToStaticMarkup) to the body.

```html
<html>
  <head>
    {style_tags}
  </head>
  <body>
    <div className="root">
      {react_elements_to_be_render}
    </div>
  </body>
</html>
``` 

Let me know what you think (I am still not sure about this).

**Comment by kentcdodds** [comment]
Thanks! I'm not certain I follow though... What would the API look like?

**Comment by nitin42** [comment]
Ya I am working on an example and will upload soon. Just a question! When we use `glamorous.div({...})`, it will forward a `className` prop to the component we tell it to render. This is done by calling `css()` from `glamor` internally. Right ?

Because if we are calling `css()` internally, we could collect all the calls to it and this would be help in doing SSR (rehydration).

**Comment by kentcdodds** [comment]
Yes, that's correct. That's how we accomplish it today (via glamor's APIs). Just looking for a simpler way to do it.

**Comment by nitin42** [comment]
```javascript
// Performing server side rendering

import { StyleSheetServer } from "glamorous";
import ReactDOMServer from "react-dom/server";
import AnyComponent from "./AnyComponent";

// Pass this callback, ReactDOMServer.renderToString(<AnyComponent />) to StyleSheetServer.renderStaticMarkup which will return the generated html.
// All of the calls to the css() (glamorous calls css() internally using glamor) will be collected which will return css.

/**

High level Picture - 

renderStaticMarkup(fn) {
  return {
    html,
    css: {
      content: getContent(),
      renderedClassNames: getClassNames()
    }
  }
}

*/

let { html, css } = StyleSheetServer.renderStaticMarkup(
  ReactDOMServer.renderToString(<AnyComponent />)
);

// Base html file

return `
  <html>
    <head>
      <style>${css.content}</style>
    </head>
    <body>
      <div id='app'>${html}</div>
      <script src="bundle.min.js"></script>
      <script>
        rehydrate(${JSON.stringify(css.renderedClassNames)});
        ReactDOM.render(<AnyComponent />, document.getElementById('app'));
      </script>
    </body>
  </html>
`;
```

This is the high level picture. Let me know if I am going in the right direction !

**Comment by nitin42** [comment]
Further, we can optimize the `renderStaticMarkup` method to include only generated styles on the page (glamor's `renderStatic` includes all the css).

**Comment by kentcdodds** [comment]
Cool! I like the direction. Could we accomplish the same API as styled-components?

```js
import { renderToString } from 'react-dom/server'
import { ServerStyleSheet } from 'styled-components'

const sheet = new ServerStyleSheet()
const html = renderToString(sheet.collectStyles(<YourApp />))
const css = sheet.getStyleTags()
```

I think that's pretty simple...

Also, glamor has [`renderStaticOptimized`](https://github.com/threepointone/glamor/blob/master/docs/server.md) which should do the heavy lifting for us 😀

**Comment by kentcdodds** [comment]
Actually, now that I think more about it, I think I like this (similar to your solution) better: 

```js
let { html, css } = StyleSheetServer.extractCSS(
  () => ReactDOMServer.renderToString(<AnyComponent />)
);
```

It has to be a callback I think. Otherwise we don't know when to start/stop tracking calls to css right?

**Comment by nitin42** [comment]
Yes! We can definitely abstract everything inside `ServerStyleSheet` and achieve same. Didn't knew about `renderStaticOptimized` 😅

**Comment by nitin42** [comment]
`extractCSS` ? we need to extract both the html and string 😅 I think. Yes it has to be a callback!

**Comment by kentcdodds** [comment]
Haha, yeah, good point!

**Comment by nitin42** [comment]
So which API design should we use ?

**Comment by kentcdodds** [comment]
```js
let { html, css } = StyleSheetServer.renderStaticMarkup(
  () => ReactDOMServer.renderToString(<AnyComponent />)
);
```

This is good

**Comment by nitin42** [comment]
Great! So I can start working on this I think !?

**Comment by kentcdodds** [comment]
Go for it! Thanks!

**Comment by kentcdodds** [comment]
This is going to actually just be a matter of documentation on the website. Not too much to improve beyond that.

**Comment by nitin42** [comment]
I will start working soon on creating examples !!

**Comment by nitin42** [comment]
I've created a gist explaining the process. Here - https://gist.github.com/nitin42/559fe988c59194357ce868416c390273

**Comment by kentcdodds** [comment]
Oh, that's perfect. You could just stick that directly in [here](https://github.com/kentcdodds/glamorous-website/blob/master/pages/advanced/content/ssr.md) and that'd be awesome :clap:

**Comment by mbrochh** [comment]
Hmm... I tried to follow that guide:

My server.js looks a bit like this:

```
  const app = (
    <ApolloProvider client={client}>
      <Router context={{}} location={req.url}>
        <Pages />
      </Router>
    </ApolloProvider>
  )
  getDataFromTree(app)
    .then(() => {
      const content = renderStatic(() => ReactDOMServer.renderToString(app))
      console.log(Object.keys(content))
      console.log(content.css)
      ...
```

`renderStatic` does return my markup, and some divs have classes generated by glamor, but my return value `content` does not have anything in `ids`, and `css`.

Does anyone have a pointer what I might be missing here?

**Comment by nitin42** [comment]
Try `ReactDOMServer.renderToStaticMarkup `  and let me know if this works!

**Comment by mbrochh** [comment]
@nitin42 just tried that, same result :(

**Comment by kentcdodds** [comment]
Hmmm... It's working for me on my site: https://github.com/kentcdodds/kentcdodds.com

It's a bit hacky, but it's pretty raw so maybe that'll enlighten you :think:

**Comment by mbrochh** [comment]
@kentcdodds I ended up deleting my node_modules folder and trying again. It works now. Sorry for wasting everyone's time :(

**Comment by nitin42** [comment]
No problem! That's great 😀
