### ISSUE TITLE
Add the ability to use a component as a selector in CSS

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#136]
In [the styled-components v2 blogpost announcement](https://medium.com/styled-components/announcing-v2-f01ef3766ac2) it says:

> You can now reference another component in your CSS, for cases where you really need to make a contextual override.

I think this could definitely be handy! @threepointone said that he'd be willing to make a PR to make this happen, because he's just really nice :)

**Comment by liadbiz** [comment]
The blog also said:

> We recommend using this sparingly, as there are usually alternatives (passing a prop or using a theme, for instance) that are more explicit

actually, you can do css overrides in glamorous now by passing props, using theme, or just extend a component by using function `glamorous`

```js
const MyComposedStyledDiv = glamorous(MyStyledDiv)({fontSize: 4, padding: 4})
```

I personaly prefer this. but, add an api like this is also handy:

```js
<MyComposedStyledDiv link={MyStyledDiv} />
``` 

just some thoughts :)

**Comment by kentcdodds** [comment]
I think you're misunderstanding the feature actually. I'll share more when I'm at a keyboard.

**Comment by kentcdodds** [comment]
Here's an example:

```javascript
const RedDiv = glamorous.div({color: 'red'})
const ContainerDiv = glamorous.div({
  [RedDiv]: {
    color: 'blue',
  }
})

<ContainerDiv><RedDiv>Hello</RedDiv></ContainerDiv>

// Renders <div><div>Hello</div></div>
// with "color: blue" applied to <div>Hello</div>
```

Hopefully that makes sense. @threepointone said he wanted to implement this, but I'm sure he'd be happy for anyone else to implement it :)

**Comment by kentcdodds** [comment]
Quite honestly, I think that this could be accomplished outside of glamorous via a plugin 🤔

**Comment by kentcdodds** [comment]
The challenge with a glamor plugin is that `[RedDiv]` up there will be `.toString()`-ed which results in the function string being the key which is kinda odd. We may not be able to have this API at all I'm afraid. Hmmm.... Any ideas?

**Comment by kentcdodds** [comment]
So [here's](https://codesandbox.io/s/JlPNY9YP) one way to do it currently:

```javascript
// red-div.js
import glamorous from 'glamorous';

const redDivClassName = 'red-div-class-name';
const RedDiv = glamorous.div({ color: 'red' }, redDivClassName);
RedDiv.className = redDivClassName;

export default RedDiv;
```

```javascript
// index.js
import React from 'react';
import { render } from 'react-dom';
import glamorous from 'glamorous';
import RedDiv from './red-div';

// so you don't have a bunch of output in
// the console every time you make a change
console.clear();

const ContainerDiv = glamorous.div({
  [`& .${RedDiv.className}`]: {
    color: 'blue',
  },
});

function App() {
  return <ContainerDiv><RedDiv>Hello</RedDiv></ContainerDiv>;
}

render(<App />, document.getElementById('root'));
```

I think this is _the_ way to do it. Maybe we could make it easier though... Any ideas for that?

**Comment by liadbiz** [comment]
@kentcdodds  Thanks for your explaination :+1: 
but I am stil don't understand what kind of problem can this feature solve. :sob:

**Comment by ntkoso** [comment]
@liadbiz Styling sibling components based on element state (:active, :hover, etc...).

**Comment by antoinerey** [comment]
Why not add a `toString()` method to Glamorous components ?

As far as I understand the source code, [you already compute de full classname](https://github.com/paypal/glamorous/blob/master/src/create-glamorous.js#L97). Why not use this, and return it when calling the `toString()` method ?

@kentcdodds Here is an exemple based on your own: https://codesandbox.io/s/jqrDvX6gz

**Comment by kentcdodds** [comment]
I like the idea. Let's think about this some more. The problem with your proposal is it assumes that we already know the class name of the component, but we don't actually know until the component is rendered (which is when the styles are created and the hash is generated). A lot of things go into the class name and it changes over time (dynamic CSS, merging styles, etc, will change the hash). So we can't rely on the generated class name.

That said, we _could_ give each component a unique class name. We actually sort of do that based on the `displayName` if you enable [certain config](https://github.com/paypal/glamorous#config). But I wouldn't want it to be tied to the `displayName`. I also wouldn't want it to be guessable (otherwise folks may rely on it). What if we generated a random className for the component if the `toString` method is ever called and applied that to the component? I think that would work!

Thoughts?

As for implementation.... Probably add `toStringClassName: ''` and the `toString() {}` around [here](https://github.com/paypal/glamorous/blob/964bd6cfc70cda977d9c0480e345551115d3ef5d/src/create-glamorous.js#L174-L188), then change [this](https://github.com/paypal/glamorous/blob/964bd6cfc70cda977d9c0480e345551115d3ef5d/src/create-glamorous.js#L107) to: `const className = `${fullClassName} ${debugClassName} ${GlamorousComponent.toStringClassName}`.trim()`

With that, we should probably also add some tests (I'd favor a new file called `index.toStringClassName` in [`__tests__`](https://github.com/paypal/glamorous/tree/964bd6cfc70cda977d9c0480e345551115d3ef5d/src/__tests__)) and documentation (I know the README's getting huge, we're working on [a website](https://glamorous.rocks/)), and we should be solid!

Anyone wanna take that on!?

**Comment by kentcdodds** [comment]
I'm going to start working on this.

**Comment by kentcdodds** [comment]
I've started work on it in #183

**Comment by paulmolluzzo** [comment]
> but I am stil don't understand what kind of problem can this feature solve. 😭

@liadbiz You can select a child component without knowing it's DOM element contents and can avoid needing to update your CSS selectors when components are updated independently. For example using @kentcdodds' previous example as a starting point:

```js
const RedAlert = glamorous.div({color: 'red'})
const ContainerDiv = glamorous.div({
  [RedAlert]: {
    color: 'blue',
  }
})

<ContainerDiv><RedAlert>Hello</RedAlert></ContainerDiv>
```

Later you update `RedAlert` to use a `span` and nothing else changes:

```js
const RedAlert = glamorous.span({color: 'red'})
const ContainerDiv = glamorous.div({
  [RedAlert]: { // doesn't change
    color: 'blue',
  }
})

<ContainerDiv><RedAlert>Hello</RedAlert></ContainerDiv>
```

It's more valuable with child selectors even:

```js
import externalComponent from 'externalComponent'
const ContainerDiv = glamorous.div({
  ['${externalComponent} p']: {
    color: 'blue', // make all the p tags in that specific component blue, even if it updates in the future
  }
})
```

**Comment by liadbiz** [comment]
@paulmolluzzo Thank you! That makes  sense to me!

**Comment by wellguimaraes** [comment]
What about self reference?

**Comment by kentcdodds** [comment]
@wellguimaraes, self-references? Like nesting your component in itself? This would support that as well. Though, if you look at [the pull request](https://github.com/paypal/glamorous/pull/183), you'll see that it's quite possibly not going to happen.

**Comment by kentcdodds** [comment]
That is to say, we wont add this feature because it can be done already with relative ease without making glamorous more complex.

**Comment by kentcdodds** [comment]
We're going to make this a docs-only improvement. Closing in favor of https://github.com/kentcdodds/glamorous-website/issues/222
