### ISSUE TITLE
Add component name to the class name

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#137]
In [the styled-components v2 blogpost announcement](https://medium.com/styled-components/announcing-v2-f01ef3766ac2) it says:

> To circumvent this limitation we’ve built a Babel plugin which allows us to generate classes that include your components’ names! While we were at it we also made sure the correct names show up in the React DevTools, so rather than seeing <styled.div> or <styled(Component)> you’ll now see <Wrapper> and <styled(Link)> !

We already have [a babel plugin](https://github.com/bernard-lin/babel-plugin-glamorous-displayname) to make the display name be more helpful (thank you @bernard-lin), but the className does _not_ include the component name and that would be really helpful.

I just had an idea as I was typing this that would be really easy... What if we take the `displayName` value and attach it as part of the className. I don't think that's too bad of a solution now that I think of it 🤔 

Hmm... I'm just going to make a PR for this... Would love some feedback on that. Stand by :)

**Comment by jfrolich** [comment]
Cool!
