### ISSUE TITLE
Is GlamorousComponent.propTypes incorrect?

### ISSUE THREAD

**Issue by quicksnap** [paypal/glamorous#140]
- `glamorous` version: Latest
- `glamor` version: Latest
- `react` version: Latest

When I try something like:

```javascript
<glamorous.Ul className={glamor.css({ border: '1px solid green' })} >
```

I get a propTypes warning due to this: https://github.com/paypal/glamorous/blob/master/src/create-glamorous.js#L110

Should we change the propType so it accepts `PropTypes.oneOfType([PropTypes.string, PropTypes.object])`?

**Comment by kentcdodds** [comment]
Great question, I guess we could do that. But honestly the reason this works is actually incidental to the fact that the `toString` method on `glamor.css()` returns the class name (which is pretty clever actually). So you could just do: `<glamorous.Ul className={glamor.css({ border: '1px solid green' }).toString()} >` or `<glamorous.Ul className={`${glamor.css({ border: '1px solid green' })}`} >` and that'd work.

But I realize that's not very ergonomic, so I'd be happy to accept a PR to update the prop types :)

**Comment by quicksnap** [comment]
The reason I brought it up is because the docs illustrate that usage: https://github.com/paypal/glamorous/blame/master/README.md#L430-L431

Perhaps instead we should update the README so that we show stringify

**Comment by quicksnap** [comment]
Oh, and I get that, in this case, it's automatically stringified due to string interop, but it lead me astray when I decided to pass the result directly to className

**Comment by kentcdodds** [comment]
Yeah, we should probably just allow you to do that :+1:

**Comment by marzelin** [comment]
I'd rather vote against changing `propTypes` of `className`. What if somebody put there some object by mistake? I'd rather be warned that something is wrong.

**Comment by quicksnap** [comment]
I agree @marzelin

**Comment by kentcdodds** [comment]
Ok, I'm good with that. In that case, maybe we could document things so folks aren't tripped up by this. Any takers?

**Comment by marzelin** [comment]
What if we add `withStyles` helper method instead?

`glamorous(glamorous.Ul)({ border: '1px solid green' })`
would become
`glamorous.Ul.withStyles({ border: '1px solid green' })`

and
`<glamorous.Ul className={glamor.css({ border: '1px solid green' })} >`
can be replaced with
`<glamorous.Ul.withStyles({glamor.css({ border: '1px solid green' }) >`

The big selling point of css-in-js for me is that I don't have to deal with `className` and `styles` any more.
I can create more specific versions of `div`s `header`s etc. I don't have to deal with source order, cascading model of css - it's handled automatically by `glamorous`.

Lets make `glamorous` simpler abstraction over css. Let's make `css` just internal low level API and provide users with something more convenient.

**Comment by kentcdodds** [comment]
Thanks for the input @marzelin. One thing I want to avoid is making it too difficult for folks to do regular CSS. While I don't think that it's a great way to build UIs, having an escape hatch is useful.

All that said, this is actually not the way that people should be doing things anyway. Normally if I see code like @quicksnap showed above:

```jsx
<glamorous.Ul className={glamor.css({ border: '1px solid green' })} >
```

I'd refactor it to:


```jsx
<glamorous.Ul css={{ border: '1px solid green' }} >
```

Which works today and is what I think you're suggesting with the `withStyles` function.

**Comment by marzelin** [comment]
I agree @kentcdodds, `css` has its use but it shouldn't be treated as something to use only in special cases. There should be at the bottom of the docs about `css` as an advanced tool for handling edge cases. `css` is flexible which unfortunately makes it also complex. So I'd rather suggest users not to use it and rely on awesome features of `glamorous`. Your refactor is fantastic :)

**Comment by kentcdodds** [comment]
Moving this issue to https://github.com/kentcdodds/glamorous-website/issues/221
