### ISSUE TITLE
Document really awesome use case?

### ISSUE THREAD

**Issue by quicksnap** [paypal/glamorous#142]
So, I have been playing around and found that Glamorous components accept nested arrays for CSS:

```jsx
<Div css={ [stylesObj, {fontSize: 20}, [ {fontSize: 30}, {fontSize: 40} ] ] }>
  I am fontSize: 40!
</Div>
```

This is really awesome for composition: all I need to do is pass along component CSS props and append them to the end of the array and then:

- Styles work as expected
- Jest Snapshots actually show the combined object outputs, making for great PR reviews.

Should we document this better?

**Comment by kentcdodds** [comment]
Yes! Thanks for bringing it up in the issues. Let's document this better. It's documented slightly in the examples [here](https://github.com/paypal/glamorous/tree/master/examples#dynamic--static-styles) but we should call it out better.

Several awesome folks are working on a website for glamorous where things like this will be easier to call out. Would you like to help out [there](https://github.com/kentcdodds/glamorous-website)?

For now, if you have an idea of where we call this out better feel free to make a PR!

**Comment by kentcdodds** [comment]
Moving this issue to https://github.com/kentcdodds/glamorous-website/issues/221
