### ISSUE TITLE
Support dynamic style function which returns a static custom class name

### ISSUE THREAD

**Issue by zillding** [paypal/glamorous#146]
First of all, thanks for the awesome work! 👍 💯 

I have been playing around with glamorous and really like the way it helps styling components.

The current component factory in glamorous can take in either a static string class name or a style function which takes in the props and return a glomor css style object.

I found it would be better to support a style function that takes in the props etc, and return a static class name.

example:

```js
const StyledDropdown = glamorous(Dropdown)(
  props => props.open ? 'is-open' : 'is-close'
)
```

Though this could be worked around by adding some extra code in the `Dropdown` component to append the class based on the props. It could make the code cleaner if glamorous can support this feature. 😊

**Comment by kentcdodds** [comment]
Hi! Have you tried this? I'm fairly certain it's supported 👍

**Comment by zillding** [comment]
Yep, I tried this and it throws this error:

![screen shot 2017-05-27 at 9 10 16 pm](https://cloud.githubusercontent.com/assets/2175447/26521678/f612a6b8-4320-11e7-8d50-4d6a4b887aa8.png)

**Comment by kentcdodds** [comment]
Rats, well it should be supported. Would you like to [make a pull request](http://makeapullrequest.com)?

**Comment by liadbiz** [comment]
@zillding This codesandbox maybe what you want: https://codesandbox.io/s/4RP21JJPk
you can pass a function that receives props argument and return css object.

**Comment by kentcdodds** [comment]
Thanks @liadbiz. I think he wants to be able to return a class name string instead. Which we should support but apparently don't.

**Comment by zillding** [comment]
@kentcdodds I will try~ 😊

**Comment by liadbiz** [comment]
@kentcdodds  sorry for that...I didn't understand what could this feature be used for.. :sob:
