### ISSUE TITLE
README table of contents item links to wrong section

### ISSUE THREAD

**Issue by ajwhite** [paypal/glamorous#150]
The `glamorous` link in the Table of Contents links to the `# glamorous` heading at the top of the README, rather than the `### glamorous` section further down in the documentation.

Not sure of the best way to fix this, as we use [doctoc](https://www.npmjs.com/package/doctoc). Off the top of my head I'd normally add a `<span name="unique-name">`.

![example of problem](http://g.recordit.co/QoIm3PvPQe.gif)

**Comment by kentcdodds** [comment]
How about instead of doing:

```
# glamorous
```

At the top we do:

```
<h1>glamorous</h1>
```

Or something 🤔

**Comment by ajwhite** [comment]
That's pragmatic 👍

**Comment by kentcdodds** [comment]
See the PR. That doesn't appear to work. I think this is a `wontfix`.
