### ISSUE TITLE
Trying to understand performance implications of using glamorous over plain CSS files

### ISSUE THREAD

**Issue by jannisg** [paypal/glamorous#151]
I'm part of a team building a company-wide internal framework of components that will ultimately end up in applications serving hundreds of thousands of people.

I've been trying to understand how glamorous would impact the rendering performance of our components, especially when it comes to dynamic CSS as part of providing different themes or responding to local props in our CSS.

I've been looking at the performance docs in `glamor` itself and though it mentions being able to cache style objects in a WeakMap cache, I am wondering whether `glamorous` does anything like that by default for example to optimise the performance of styles in my presentational components.

Also, is there any guidance on how `glamorous` might compare to `css-modules` or even just loading plain `.css` files that as part of the component file?

Right now, I feel as though `glamorous` would be a great library to allow for easy theming and great DX for this component library but given the scale of some of these applications that will ultimately consume these components, people around me are a bit nervous and so far I've been having a hard time finding any definite performance benchmarks comparing "css in js" to traditional css files.

Lastly, is there any way of optimising a glamorous component which uses the `<ThemeProvider />` wrapper to apply common colour values and strip this out at compile time?
This would allow us to generically allow for custom theme values in all components but allow on the application level for any potential overhead to be stripped away if the application is compiled only for a single brand/theme.

Any tips or pointers would be much appreciated.

**Comment by kentcdodds** [comment]
These are great questions! I'm away from the keyboard right now, but I talk about some of this stuff at the end of my talk here: https://youtu.be/R1_nGU0x3Wk
I can answer things more directly later.

**Comment by jfrolich** [comment]
Hi @jannisg,

Performance will always be worse than straight css. Glamorous uses glamor internally so the caching you read about also applies to glamorous. This is mostly because the browser first need to parse js and then needs to parse css instead of just parsing the css. After parsing though the difference is not that big due to caching.

One performance benefit of glamorous vs css  is that you only load download the css that is necessary to show the current UI (if you apply code splitting).
Mostly it is just improving the developer experience and being able to ship fast.
There are some efforts underway to statically analyze some of the code and create plain css at compile time (#86, https://github.com/threepointone/glam and https://github.com/facebook/prepack). When we have this the performance will be the same as just shipping plain CSS.

We use glamorous in a medium sized app, and we do not have any performance bottlenecks because of glamor(ous). I don't think this is a bottleneck in most apps, but yes definitely be aware of the performance implications.

**Comment by kentcdodds** [comment]
Hi there :) In addition to what @jfrolich shared...

> is there any guidance on how glamorous might compare to css-modules or even just loading plain .css files that as part of the component file?

No, there's no guidance. It will definitely perform worse. No getting around that.

> people around me are a bit nervous

I expect none of them have actual benchmarks/experience and are just assuming that it'll be no good. This is understandable. There's really not much I can say other than many companies have been using styled-components (v1 was a clearly and significantly less performant solution) and have been loving it. glamorous performs much better than styled-components (especially without the babel plugin), so hopefully that makes you feel a bit better about it.

> Lastly, is there any way of optimising a glamorous component which uses the `<ThemeProvider />` wrapper to apply common colour values and strip this out at compile time?

This is definitely an understandable desire. You want the developer experience of the ThemeProvider, but you want to avoid the possible perf hit. There's currently nothing that can do this and it would probably be tough to create. But there is prepack which could be helpful in the future. I honestly wouldn't be too concerned with the perf hit. It's really remarkably fast.

I realize that's not really hard-solid help and mostly anecdotal, but I think that's the best kind of evidence I can give you. Best of luck to you.

I'm going to go ahead and close this, but if you feel that we could add some more information to the docs, please feel free to [make a pull request](http://makeapullrequest.com)

**Comment by ndugger** [comment]
@kentcdodds Hey Kent, sorry to necro this issue, but do you have any benchmarks or a talk that references the performance gains of glamorous over styled-components? I'd like to learn more about performance, specifically.

**Comment by kentcdodds** [comment]
Hi @ndugger,
I don't have any benchmarks myself. But I can tell you that all the popular CSS-in-JS solutions are super duper fast and you're unlikely to have any trouble with them.

That said, if you _really need_ the highest performance, just use [emotion](https://github.com/tkh44/emotion) 🤷‍♂️
