### ISSUE TITLE
Typings don't export withTheme?

### ISSUE THREAD

**Issue by debradley** [paypal/glamorous#152]
I'm new to TypeScript so I'm probably missing something obvious, but it seems that the typings don't export the `withTheme` function. Is there a reason for that? Or an alternative I'm missing?

**Comment by ErikCupal** [comment]
No, we simply forgot to add the typings for it. Thanks for finding it out. I'll take a look at it tommorow. Or if you want, you can make PR with fixed typings 😉.

**Comment by debradley** [comment]
I'd like to help with it but I've never done it before and don't know how to correctly manage all the moving parts of forks and branches and pull requests and such properly; I've even less sure how to turn my fork into an alternate npm I can use in my project instead of the real glamorous to be able to test my changes before submitting... I'd appreciate any links anyone has on how do all of that (particularly the npm part). It's overwhelming to the uninitiated.

**Comment by kentcdodds** [comment]
Welcome! You can learn about this here: http://makeapullrequest.com

You don't need to bother with publishing to test it 😀

If you'd really like to test it, you might look into how to use `npm link` but that shouldn't be necessary 😀

Again, welcome. This is a very beginner friendly community and we're happy to have you with us. Let us know how we can help!

**Comment by ErikCupal** [comment]
[This course](https://egghead.io/lessons/javascript-how-to-fork-and-clone-a-github-repository) on Egghead also helped me a lot.

For testing the changes in real project, you can make the typings changes directly in `node_modules` folder of your project and then just copy the final changes to your fork. It may be often more comfortable. Or you can directly work in the fork and test that it works in `test/glamorous.test.tsx`. Hope I expressed myself clearly 😀.

Ask if something is not clear 😉. If you think you would rather leave the PR to us just tell.

**Comment by debradley** [comment]
Your comments make perfect sense - thank you for that. And though I would like to go through the process to help and for the benefit of learning, I'm afraid that what I'd submit might be worse than nothing, giving that I just started using TypeScript today. My submission would compile but I have little confidence it would be correct. And if you have to tell me what to type in, I'm not sure that's really saving you any work.

**Comment by kentcdodds** [comment]
We're more interested in helping you land a successful pull request than getting it done quickly. You do your best and we'll help!

**Comment by ErikCupal** [comment]
Closing because the PR was merged. Thanks, great work 😉
