### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by vesparny** [paypal/glamorous#16]
Would you consider theming support as s-c does?
If so, do you need help?

**Comment by kentcdodds** [comment]
Yep! That's on [the roadmap](https://github.com/paypal/glamorous/blob/master/other/ROADMAP.md#want-to-do). Definitely looking for help!

**Comment by vesparny** [comment]
Great, will look into it.

**Comment by kwelch** [comment]
This can be closed 🎉

**Comment by kentcdodds** [comment]
Wahoo!
