### ISSUE TITLE
Improve README to really explain the difference with styled-components

### ISSUE THREAD

**Issue by alanzanattadev** [paypal/glamorous#162]
Hi,

I find the README not explicit enough about how glamorous is different from styled-components. It seems to be only like a different api (objects instead of real css).

Thank you !

**Comment by ooade** [comment]
@alanzanattadev It's [here](https://github.com/paypal/glamorous#inspiration) right?
> The biggest inspiration for building this is because I love the API offered by styled-components, but I wanted:
> ...

**Comment by kentcdodds** [comment]
Perhaps could be improved further. I think that the docs could be improved in general. There's an effort on an official glamorous website (https://glamorous.rocks) right now. Once that's done, then stuff like this will be much more straightforward :)

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
