### ISSUE TITLE
Crazy Idea: min-margin

### ISSUE THREAD

**Issue by alanzanattadev** [paypal/glamorous#163]
Hi,

I don't know how crazy / impossible / bad it is, but I suggest it anyway.

As front-end developers, we often have to deal with cases where we don't know what margin to put on something because: 
  - either it's badly sticked and we have to wrap the component with a box
  - either it conflicts with another element and make a really big margin (10px right for A + 10px left for B)
  - either we have to use some complex selectors to avoid this but it's not very component friendly / thinking.

What I suggest is having a min-margin (with min-margin-left etc) attribut, that can automatically takes the min-margin of the differents components around, to automatically set the lowest min-margin between two components.

For example, if you have a component A and a component B, placed side by side, with min-margin: 10px on A and min-margin: 20px on B, the margin between both won't be 30px, but 20px.

I don't know what are the current limits of the DOM / browsers to do this, but maybe you can find a solution for having this. It would drastically improve component reusability, component thinking and component readability.

Maybe you have another idea to solve this issue ?

Tell me what you think about it ! :)

Thank you !

**Comment by schnerd** [comment]
IMO – glamorous shouldn't really be inventing new non-standard CSS properties. This is definitely a pain point but might be solvable through clever componentization. Using your second example–10px right for A, 10px left for B–maybe they should both have no margin by default and then a parent HorizontalList component should [overrides the styles](https://github.com/paypal/glamorous#overriding-component-styles) of A and B and inject a margin rule.

**Comment by kentcdodds** [comment]
I agree with what's been said. Another thing I've done is used helpers like `spaceChildrenHorizontally`:

```javascript
import React from 'react';
import { render } from 'react-dom';
import glamorous from 'glamorous';

function spaceChildrenHorizontally(space) {
  return {
    '& > *': {
      marginLeft: 0,
      marginRight: 0,
      '&:not(:first-child)': {
        marginLeft: space / 2,
      },
      '&:not(:last-child)': {
        marginRight: space / 2,
      },
    },
  };
}

const Container = glamorous.div(
  {
    display: 'flex',
    justifyContent: 'center',
    backgroundColor: 'gray',
    padding: 20,
  },
  spaceChildrenHorizontally(20),
);

const Child = glamorous.div({
  backgroundColor: 'lightgray',
  padding: 10,
});

// so you don't have a bunch of output in
// the console every time you make a change
console.clear();

function App() {
  return (
    <glamorous.Div maxWidth={600} margin="auto" fontSize={24}>
      <Container>
        <Child>Child 1</Child>
        <Child>Child 2</Child>
        <Child>Child 3</Child>
        <Child>Child 4</Child>
      </Container>
    </glamorous.Div>
  );
}

render(<App />, document.getElementById('root'));
```

Try it [here](https://codesandbox.io/s/MY92jlMA).

I think that the general feeling is correct though. This seems like something another library should solve and not something glamorous should be getting into. Thanks though!
