### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#165]
Analytics will help give us an idea of what people are looking at most and where to focus efforts.

I don't think Google analytics in the browser will be good enough because many of our target audience blocks those. Any ideas?

**Comment by vesparny** [comment]
I've been working on a thing.

https://github.com/vesparny/fair-analytics

**Comment by kentcdodds** [comment]
That looks great! One thing. I really like the user privacy thing. Is there any way to get the country and/or language preference of the user? This will help us know what languages to focus on getting translations for.

**Comment by kentcdodds** [comment]
Whoops! Agreed this to the wing repo! lol
