### ISSUE TITLE
Can I refer to other components?

### ISSUE THREAD

**Issue by martinhorsky** [paypal/glamorous#174]
Hello, I am new to *glamorous* and I am curious about *styled-components* feature "[Refer to other components](https://www.styled-components.com/docs/faqs#can-i-refer-to-other-components)". Is it possible do the same thing using *glamorous*?

Thanks for the answer

**Comment by kentcdodds** [comment]
Not yet, but we have [a solution decided](https://github.com/paypal/glamorous/issues/136) on and someone just needs to work on it. Should be pretty small. Want to [make a pull request](http://makeapullrequest.com/)?

**Comment by kentcdodds** [comment]
I'm going to close this issue in favor of https://github.com/paypal/glamorous/issues/136
