### ISSUE TITLE
Deprecate/remove ThemeProvider in favor of theming?

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#175]
@iamstarkov created a new library called [`theming`](https://github.com/iamstarkov/theming) (with help from many folks, including @vesparny who built our implementation). It's intended to unify theming for React CSS in JS libraries. I'm in support of this effort and would like to propose we consider deprecating/removing our own ThemeProvider in favor of documenting an integration with `theming`. [Here's](https://codesandbox.io/s/n53mYgQ9D) our current Theming example which uses `theming` instead of `glamorous.ThemeProvider`. Works great.

An alternative would be that we remove our own implementation and just use `theming`. This would be totally unobservable to developers using glamorous and everything would keep working the same. I say we at _least_ do this.

Thoughts?

**Comment by iamstarkov** [comment]
as far as `glamorous` offers theming support beyond `ThemeProvider` and `withTheme`, you need  deeper theming integration as we discussed in https://github.com/iamstarkov/theming/pull/3. That said, you need to re-export theming from within glamorous, so breaking changes for deep integration and for themeProvider/withTheming will be happening at the same time, so it will be in sync.

**Comment by iamstarkov** [comment]
regarding "breaking change" badge, i wouldnt agree. `theming` has the same surface api for the consumers as glamorous's implementation. The only different part is channel, but to address that there is `createTheming` to create `theming` with custom channel.

```
// ./src/theming.js
import { createTheming } from `theming`;

export const { ThemeProvider, withTheme } = createTheming('__glamorous__');
```

and its not breaking change anymore

**Comment by kentcdodds** [comment]
I don't think that `glamorous` needs more than what we get with `ThemeProvider` and `withTheme`. So I'm thinking that we could do as you suggest and remove our own implementation.

I'm actually thinking that instead of use `createTheming` with `__glamorous__` was just use the default. That way we would interop well with anyone else using `theming` which I think would be cool (and is really the dream right?)

**Comment by iamstarkov** [comment]
related https://github.com/cssinjs/react-jss/pull/95

**Comment by iamstarkov** [comment]
I'm quite sure glamorous is using theming beyond themeprovider and withtheme. Just take a look at theming examples https://github.com/paypal/glamorous/blob/master/README.md#theming

```js
const Title = glamorous.h1({
  fontSize: '10px'
}, (props, theme) => ({
  color: theme.main.color
}));
```

Theme here is not a prop and component is not wrapped into withtheme

**Comment by iamstarkov** [comment]
Though, I might be wrong

**Comment by kentcdodds** [comment]
Ah, I see what you mean. Yes, we return a component which we would ourselves wrap in `withTheme` :+1:

**Comment by iamstarkov** [comment]
@vesparny what do you think?

**Comment by vesparny** [comment]
I am from mobile now. will read all the thread and reply as soon as possible

**Comment by vesparny** [comment]
I think we have 2 options:

1) We remove theming from glamorous, and we encourage people to use `theming` if they need to
2) We remove our own implementation from glamorous, and we replace it with `theming`

It would be really helpful to know if the community uses <ThemeProvider /> a lot.
In that case option 2 would probably be the best one. 

I'd personally go for option 1 because I do not always need theming capabilities in my apps.

By removing it we can also shave off some bytes from glamorous, which is always good :)

On the other hand option 2 is the easiest and less invasive one (not a breaking change at least)

**Comment by kwelch** [comment]
I really like the ability to theme, but the argument for bytes is valid. What if `glamorous` implemented `themeing`, and `glamorous.tiny` trimmed it as it is more appealing to those saving bytes?

**Comment by kentcdodds** [comment]
I say let's go with option 2. Anyone who cares enough about size will be tree shaking anyway and that will be just like we didn't have theming at all. Option 2 will simplify our codebase, so that'll be nice. Anyone want to open up a pull request for this?

**Comment by vesparny** [comment]
That would be a nice one for first contributors 😃 
Otherwise I can take it

**Comment by kentcdodds** [comment]
Unfortunately I don't think it'll be totally straightforward. But if you'd like to outline exactly what needs to be done, then we can guide a first time contributor on this one which would be super!

**Comment by vesparny** [comment]
@kentcdodds uhm...you are probably right.

I think as first step we can try to replace our `ThemeProvider` and `withTheme` with the ones exported by `theming` in tests and see what happens.

**Comment by vesparny** [comment]
Ideally we would also remove [those lines](https://github.com/paypal/glamorous/blob/45635c4111b668a9ec90c1c35e858dd0799c984a/src/create-glamorous.js#L63-L79) and use `withTheme`.

cc @iamstarkov

**Comment by iamstarkov** [comment]
@vesparny for that particular use case where theming functionality is baked in into `ComponentFactory` we would need themeListener from https://github.com/iamstarkov/theming/pull/3

**Comment by kentcdodds** [comment]
Hmmm... I'm unsure I understand. We could just remove those lines and use `withTheme` around the `GlamorousComponent` instead right? Aren't those lines what `withTheme` is supposed to take care of for us? In fact, without those lines `GlamorousComponent` could just be a function component I think...

**Comment by iamstarkov** [comment]
@kentcdodds if i am correct, then right now `GlamorouseComponent` is exactly one component. if we would wrap it into `withTheme`, then it becomes exactly two, so if the app is built entirely with glamorous, then we double amount of components in react tree and in dev tools, which seems to me like an overkill. Instead, we can integrate themeListener which will receive initial theme and any theme updates inside of `GlamorousComponent` and then `GlamorousComponent` will proceed as before. So themeListener will abstract implementation details of theming support for `GlamorousComponent`

I'll show what i mean shortly

**Comment by kentcdodds** [comment]
Actually, a `GlamorousComponent` is uniquely created for _every_ time you call `glamorous.div()` so we're at the same spot either way :)

**Comment by iamstarkov** [comment]
well, "shortly" was a exageration, maybe tomorrow morning

**Comment by kentcdodds** [comment]
I've been implementing this and I now know what you meant. But don't worry about, my implementation actually makes it so we don't add another component into the tree :)

**Comment by kentcdodds** [comment]
Please see #184, I think we'll need `theming` to support some of this stuff if we want to use it.

**Comment by kentcdodds** [comment]
Ok, so #184 has been merged, so we're ready to do this as soon as we get these two things implemented: https://github.com/iamstarkov/theming/issues/13 https://github.com/iamstarkov/theming/issues/14 :+1:

**Comment by iamstarkov** [comment]
@vesparny can you take a look as well in iamstarkov/theming#3 and how it can help her?

**Comment by vesparny** [comment]
@iamstarkov I took a look at your implementation and looks very good to me.
Only difference I see is that on Glamorous we set theme also based on props.
For instance if you pass a `theme` prop to a component, it takes precedence over the one stored in `context`.

https://github.com/paypal/glamorous/blob/0bfda9fa8e33453b9b71e95ea5683634d1900184/src/with-theme.js#L37-L40

What happens in the same case with `theming`?

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this unless it comes up again and would simplify things for us. Thanks!

**Comment by goodmind** [comment]
@kentcdodds why this is closed?

**Comment by kentcdodds** [comment]
Because `theming` doesn't _quite_ support our use cases. Specifically [this](https://github.com/paypal/glamorous/blob/645315571fabda36393915af1b3410e691c1a5ca/src/with-theme.js#L63-L76). I kinda doubt that theming will be changed to support that. But if that happens that'd be great :)

**Comment by kentcdodds** [comment]
We'd like to re-evaluate this and see if we can make it work.

**Comment by kentcdodds** [comment]
I think this would be great, but I'm honestly not too motivated to do this personally. If anyone else wants to pick it up be my guest and we can reopen it. Thanks!
