### ISSUE TITLE
Breakpoint specific CSS

### ISSUE THREAD

**Issue by parvezk** [paypal/glamorous#176]
It's not clear how to write media-query specific styles when composing components using glamor. For example below, how to target style or control layout for a specific breakpoint:

`const MyStyledDiv = glamorous.div({
  fontSize: 20,
  textAlign: 'center',
})`

**Comment by kentcdodds** [comment]
Hi @parvezk,
See [this section in the README](https://github.com/paypal/glamorous#example-style-objects).

Let us know if that could be more clear. Thanks!

**Comment by parvezk** [comment]
@kentcdodds Thanks! this helps.
