### ISSUE TITLE
Possible to export a stylesheet?

### ISSUE THREAD

**Issue by kirkstrobeck** [paypal/glamorous#178]
I acknowledge this does not fit issue guidelines

---

Is it possible to export the CSS that `glamorous` generates as a static file?

**Comment by kentcdodds** [comment]
Hi @kirkstrobeck! :wave:

Allow me to redirect you to #86

**Comment by kirkstrobeck** [comment]
Thx! Looks like I was able to achieve what I had expected with https://github.com/threepointone/glamor/blob/5e7d988211330b8e2fca5bb8da78e35051444efd/docs/server.md

**Comment by kentcdodds** [comment]
Ah yes, server-rendering is great too :+1:
