### ISSUE TITLE
Border-Color properties acting strangely based on the amount of CSS properties on the element.

### ISSUE THREAD

**Issue by bhough** [paypal/glamorous#18]
- `glamorous` version: 1.0.1

### Relevant code or config. Or even better, [a reproduction][help-pen]
https://codesandbox.io/s/48EKDv5wg

### What you did:
Was testing compatibility with polished (polished.js.org) and came across a strange bug with border-colors.

### Problem description:
It seems to only set one of the directional properties properly while setting the remaining to `initial`. 
As seen here: http://d.pr/i/7ng6/53ZbyvnT

Adding properties after the `border-color` properties affects which property is set properly, until adding enough eventually means all are set to `initial`. Move the border-color declarations to the top and they all work.

This happens with both the camelCased versions of the property names as well as the hyphenated versions, with or without polished.

**Comment by kentcdodds** [comment]
Thanks for this! Is this an issue with glamor? Or is it just glamorous with this issue?

**Comment by paulmolluzzo** [comment]
Possibly related: https://github.com/threepointone/glamor/issues/226

**Comment by paulmolluzzo** [comment]
Same issue if you just use `glamor` alone. See here: https://codesandbox.io/s/qY3G75453

**Comment by kentcdodds** [comment]
Thanks @paulmolluzzo. Considering this is a glamor issue and not glamorous-specific, I'm going to go ahead and close this in favor of that issue. Thanks for bringing it up. I hope we can work together to get it resolved. Interesting discussion going on threepointone/glamor#226
