### ISSUE TITLE
Support react 15.6: bug version detection causes usage of React.Proptypes

### ISSUE THREAD

**Issue by ndelangen** [paypal/glamorous#185]
versions:
```json
{
    "glamor": "^2.20.25",
    "glamorous": "^3.23.2",
    "global": "^4.3.2",
    "next": "^3.0.0-beta15",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
}
```

Relevant code.
https://github.com/paypal/glamorous/blob/55b3f07f8b9926ecf0576821614c0306bc50af2e/src/react-compat.js#L6

```javascript
if (React.version.slice(0, 4) === '15.5') {
```

What you did:
- I used the newest version of React + glamorous
- This causes this warning to appear:
<img width="705" alt="screen shot 2017-06-16 at 18 20 14" src="https://user-images.githubusercontent.com/3070389/27235296-81ff1734-52c0-11e7-955c-9cf9d3888c2a.png">

Suggested solution:
```javascript
if (ParseFloat(React.version.slice(0, 4)) >= 15.5) {
```

**Comment by kentcdodds** [comment]
Ah yes! This is a great first timers only issue! Let me prep it :)

**Comment by kentcdodds** [comment]
Hi there! 👋

This is a ["first-timers-only"](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issue. That means that we will only accept a pull request from someone who's never contributed to open source before! :tada: If that's you, read on. If that's not you, spend the time instead setting up an issue like this for someone else in one of your own projects :wink:

So here's how things are going to go, I'll explain clearly what needs to happen for this issue to be closed. You "claim the issue" by commenting on here saying that you'd like to work on it as soon as you're able to start. Then you follow the steps I've outlined. Feel free to ask any questions if you get stuck along the way.

1. Make sure to claim the issue by commenting that you're working on it right now.
2. Probably the most useful thing you could do before getting started is to watch [this free video course](http://kcd.im/pull-request). That will help you understand the terms and concepts of the following steps.
3. Read [the contributing guidelines](https://github.com/paypal/glamorous/blob/master/CONTRIBUTING.md)
4. Fork the repo
5. Clone your fork
6. Create a branch for your changes (`git checkout -b pr/fix-react-version-detection`)
7. Open the directory in your favorite text editor
8. Normally, this is the part that you'd write a test to verify the bug exists, or enable one that I've written for you, but testing this particular bug is more work than it's worth, so we'll skip that part.
9. Open the file [`src/react-compat.js`](https://github.com/paypal/glamorous/blob/55b3f07f8b9926ecf0576821614c0306bc50af2e/src/react-compat.js) and change [this line](https://github.com/paypal/glamorous/blob/55b3f07f8b9926ecf0576821614c0306bc50af2e/src/react-compat.js#L6) to: `if (ParseFloat(React.version.slice(0, 4)) >= 15.5) {`
10. Run `npm start contributors.add` and follow the prompt (you're contributing `code`)
11. Commit your changes following our commit message format (you can use `npm start commit` if you want, but I normally just write it manually). You can do something like: `git commit -am "fix(compat): improve react version detection"`
12. Push your changes to your forked repo
13. Open a pull request
14. Fill out the prefilled PR description
15. Wait patiently for a response
16. Address any feedback you receive and push updates (if necessary)
17. Get merged
18. Celebrate and tweet! Woo! :tada:

Thanks so much for your contribution! We're here to help you land it!

**Comment by Oalbacha** [comment]
I would like to work on it

**Comment by srajappa** [comment]
I would like to work on it :)

**Comment by kentcdodds** [comment]
Super! @Oalbacha was first so we'll leave this one to you! But maybe there's something we could find for @srajappa too 🤔

**Comment by srajappa** [comment]
@kentcdodds  :) thanks for helping us first timers out :) I will be in a look out here and in twitter

**Comment by kentcdodds** [comment]
How are things coming @Oalbacha? How can we help?

**Comment by Oalbacha** [comment]
Hi Kent,
I will be working on this and finishing it hopefully by tomorrow. I am in Dubai and it is 1140pm. Unless these is a deadline and it needs to be finished tonight? Please advise.

**Comment by kentcdodds** [comment]
No worries! You're good. This can be done tomorrow no problem. I'll need another maintainer to merge it though because I'm on a family vacation for a week starting tomorrow.

One important lesson in open source is never do any more than you're able/want to do. We can wait until you can get to it. If it's high enough priority for someone, they can fix it. That mentality is how you avoid becoming a slave to OSS.

**Comment by vesparny** [comment]
@Oalbacha take your time and do not hesitate to ask for help if you need it.
I'll be around during the week end.
Cheers and thanks a lot

**Comment by Oalbacha** [comment]
Thanks guys! I will get on it right away first thing inthe morning. Will keep you posted if I hit a brickwall :-)

**Comment by kentcdodds** [comment]
Oh no! I totally just merged a pull request from someone else thinking it was @Oalbacha 😞 I'm so sorry about that @Oalbacha. This particular issue has now been resolved. But if I think of something else I'll reach out to you first! That was my mistake.

**Comment by Oalbacha** [comment]
No worries, thanks! As long as I get the next one for sure :)

**Comment by paulmolluzzo** [comment]
@oalbacha Opening issues is just as valuable of a contribution as the PRs that solve them. 😀 Thank you!

If you want to take on a PR that helps `glamorous` there are some issues that are great first PRs on the repo to build the `glamorous` website: https://github.com/kentcdodds/glamorous-website/issues

Take a look, claim one if you think it's interesting, and ask questions if you need any guidance. Thanks! 🙌
