### ISSUE TITLE
CI tests broken

### ISSUE THREAD

**Issue by luke-john** [paypal/glamorous#191]
```
[test]  FAIL  src/__tests__/should-forward-property.js (8.597s)
[test]   ● should forward a random react-supported html attribute
[test] 
[test]     expect(received).toBeTruthy()
[test]     
[test]     Expected value to be truthy, instead received
```

What you did:

Opened a PR which didn't touch the main library or tests.

What happened:

Build failure on non typescript tests

Reproduction:

https://travis-ci.org/paypal/glamorous/builds/244838873?utm_source=github_status&utm_medium=notification

Problem description:

The current tests are failing on master

Suggested solution:

Investigate why and fix tests/library

I should get time to look into this tomorrow if no one solves it first :).

**Comment by ajwhite** [comment]
@luke-john are you sure it's only happening on CI? If you run `npm start test` locally on your #438 branch, do you get the same error?

Running the tests against `master` passes locally

**Comment by ajwhite** [comment]
Hrm, I pulled your branch down locally and, sure enough, tests are passing. Going to restart the build to see if something funky happened..

**Comment by ajwhite** [comment]
Restarting the build fixed the problem - not sure if it was a blip, or if you force pushed at it was showing an old status? Weird..

**Comment by luke-john** [comment]
Weird indeed. Thanks for looking into it 👍 .

Will close this issue.
