### ISSUE TITLE
Add exports for React Primatives

### ISSUE THREAD

**Issue by kwelch** [paypal/glamorous#192]
After reading the `styled-components` article, "Creating truly universal React Component systems". The use of [`react-primitives`](https://github.com/lelandrichardson/react-primitives), appeared to be a good fit for `glamorous` as well. 

Not sure if this is a better fit for `glamorous-native`, but thought I would propose it as an option to move forward with.

**Comment by kentcdodds** [comment]
I'm definitely open to adding support for `react-primitives` whether in the main lib, in `glamorous-native`, or in a totally separate lib. I'm really not sure what would be best. I probably would not personally use it so we'd need someone who would use it to champion the feature and commit to maintaining it. Any takers?

**Comment by kentcdodds** [comment]
Anyone wanna work on this? Would be super awesome to announce support for `react-primitives` when we do our website unveil and major release! #hype

**Comment by nitin42** [comment]
I'm interested. I was thinking about something like `glamorous/primitives`. I could dig into this further. Let me know @kentcdodds 😄

**Comment by kentcdodds** [comment]
Yep, `glamorous/primitives` would be perfect :+1:

Start with making changes to the `src/` directory, we can talk about the build process for it later :smile: Thanks a ton!

**Comment by nitin42** [comment]
I've started working and have something to show.

An example using `react-primitives` and `glamorous/primitives` - 
```javascript
import React, { Component } from 'react';
import glamorousComponent from 'glamorous/primitives';
import { View, Text } from 'react-primitives';

const StyledView = glamorousComponent(View)({ color: 'red' });

class App extends Component {
  render () {
    return (
      <StyledView>
        Hello World
      </StyledView>  
    ) 
  }
}

```
 
`./src/primitives.js`

```javascript
import reactPrimitives from 'react-primitives';
import glamorous from 'glamorous-native';

function createComponent (componentConstructor, tag) {
  if (typeof tag !== 'string' && typeof tag !== 'function') {
    throw new Error(`Cannot create glamorous component for ${tag}`) 
  }
  return componentConstructor(tag);
}

const glamorousComponent = (tag) => createComponent(glamorous, tag);

const aliases = 'Image View Text Touchable';

aliases.split(/\s+/m).forEach(alias => Object.defineProperty(glamorousComponent, alias, {
  enumerable: true,
  configurable: false,
  get() {
    return glamorousComponent(reactPrimitives[alias])
  },
}))

export default glamorousComponent;
```

We will be rendering the primitive interfaces with the help of `glamorous-native`.  But I am getting an error `You may need an appropriate loader to handle this file type.` when running the example. Seems like we will need to construct a native model for React Native which will style the aliases - `View, Text, Image, Touchable`.

**Comment by nitin42** [comment]
Woah!! I was experimenting with `react-primitives` and made a little hack along with `glamorous` api. Here is the demo - 

Uses `View` and `Text` components - http://recordit.co/zrXCiqFPSy

Uses `Image` component

![image](http://g.recordit.co/r0E989MdZJ.gif)

Seems like `glamorous` will soon support primitive interfaces 😄  (still experimenting though) !

**Comment by kentcdodds** [comment]
This is amazing! Thanks for your work on it!

How much glamorous code are you using? I'm wondering whether it makes more sense to make this a separate package (like glamorous-native) or if there's enough code sharing to justify keeping it in the main `glamorous` repo... 🤔 

Seriously, I'm way excited about this :smile:

**Comment by nitin42** [comment]
There will be no need of separate package. I created a new folder in `src` with name `primitives`. Also there are only two files,   `index.js` and `primitives.test.js` (will move this file to `__tests__` afterwards). The use of glamorous api is minimal (just for defining the properties for primitive interfaces). Let me know what you think !

**Comment by kentcdodds** [comment]
Cool, sounds good. I'm looking forward to seeing the PR!

**Comment by nitin42** [comment]
Oh! I totally forgot `ThemeProvider` and `withTheme` 😄  

![ThemeProvider](http://g.recordit.co/7qmzLR3KlD.gif)

One more thing, I think we should export `ThemeProvider` and `withTheme` along with the glamorous primitive constructor explicitly. Because I think this would be better 

```javascript
import glamorousComponent, { ThemeProvider, withTheme } from 'glamorous/primitives';
```

rather than 

```javascript
import glamorousComponent from 'glamorous/primitives';
import { ThemeProvider, withTheme } from 'glamorous';
```

Let me know !

**Comment by kentcdodds** [comment]
I agree!

**Comment by kentcdodds** [comment]
This is now supported via [`glamorous-primitives`](https://github.com/nitin42/glamorous-primitives)!

**Comment by kwelch** [comment]
Nice work @nitin42! Thanks!

**Comment by nitin42** [comment]
Awesome!! Let me know what you're working on!
