### ISSUE TITLE
use prop-types module

### ISSUE THREAD

**Issue by ryuken** [paypal/glamorous#193]
- `glamorous` version: 3.23.3
- `glamor` version: 2.20.25
- `react` version: 15.5.3

Relevant code.
https://github.com/paypal/glamorous/blob/master/src/react-compat.js#L16
```javascript
PropTypes = PropTypes || React.PropTypes
```

What you did:
I executed a Jest test script (also happens if you just use glamorous with a new react version

What happened:
 console.error ../../node_modules/fbjs/lib/warning.js:36
      Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
    console.error ../../node_modules/fbjs/lib/warning.js:36
      Warning: Portal: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

Reproduction:

-- paste your link here --

Problem description:

Suggested solution:
PropTypes = PropTypes || React.PropTypes <- React.PropTypes should be changed with the prop-types npm module?

**Comment by ajwhite** [comment]
That's precisely what the [react-compat](https://github.com/paypal/glamorous/blob/master/src/react-compat.js#L9) does -- it loads `prop-types`, but if the module doesn't exist, it will try to fallback to `React.PropTypes`.

If you were to install `prop-types` in the project you're running, it should pick that up and use it. We have this behavior in order be compatible with both scenarios: users running `prop-types`, and those running solely `react`. Both will work depending on what dependencies your project uses 😃

**Comment by ajwhite** [comment]
Let's quickly verify you have the `prop-types` module installed, and if you don't, then try installing it. I'd like to make sure nothing funky is going on with [this line](https://github.com/paypal/glamorous/blob/master/src/react-compat.js#L6), which is the predicate to attempt to load `prop-types`

**Comment by ryuken** [comment]
Aaah I understand. But I have version 15.5.8 of prop-types installed lol

**Comment by ajwhite** [comment]
Interesting. After reviewing the git blame, @acgrdumlu do you see where this could go wrong?

And @ryuken - is this something reproducible you could share through a github repo?

**Comment by ryuken** [comment]
Yes ill make a reproduceable repo tomorrow. It's 01:05 AM now :P

**Comment by ryuken** [comment]
uhm i found the problem when trying to make a reproduceable repo...
it has nothing to do with glamorous lol, it was an older version of react-bootstrap

**Comment by ajwhite** [comment]
Glad to hear you've figured it out 👍
