### ISSUE TITLE
Change `theme` docs

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#198]
A while back, we changed the way theming works slightly. It's now available as part of the props in addition to the second argument to the dynamic styles function.

I think that accessing the theme via props is better than using the second argument. It's less confusing. Also, I'm hoping that in the next breaking change, we can remove the `theme` as the second argument entirely (so the second argument would be `context` which is currently the third argument).

So anywhere we do something like this:

```javascript
glamorous.div(({big}, theme) => ({margin: big ? 20 : 10, color: theme.colors.main}))
```

Should be changed to:

```javascript
glamorous.div(({big, theme}) => ({margin: big ? 20 : 10, color: theme.colors.main}))
```

It's really nice if you're only accessing the theme as well. It means instead of:

```javascript
glamorous.div((propsThatAreNotUsed, theme) => ({}))
```

You can just do:

```javascript
glamorous.div(({theme}) => ({}))
```

Thoughts?

**Comment by paulmolluzzo** [comment]
Awesome! I find myself using the theme for most components and seldom use the props.

**Comment by kentcdodds** [comment]
I figured you would like this in particular @paulmolluzzo :smile:

**Comment by WillowHQ** [comment]
So you just need someone to go thru the docs and update those code blocks ?

**Comment by kentcdodds** [comment]
Pretty much!
