### ISSUE TITLE
React support should be `>=0.14` instead of `>=14` in package.json

### ISSUE THREAD

**Issue by majapw** [paypal/glamorous#199]
- `glamorous` version: v3.23.4
- `glamor` version: N/A
- `react` version: 0.14

*Relevant code.*
In your `package.json`, you have 
```javascript
"react": ">=14"
```
listed as the react version supported in your peer deps. This suggests that glamorous supports react 14, but unfortunately, because react was using `0.14` for previous version, it doesn't actually match on react 14.

*What happened:*
You can see our npm install failing on peer deps here - https://travis-ci.org/airbnb/react-dates/jobs/248137271

*Suggested solution:*
The relevant line should be updated to:
```javascript
"react": ">=0.14"
```
I can put up a quick fix for this if desired.

**Comment by kentcdodds** [comment]
Ah, yeah, my bad. A fix would be appreciated. Thanks! I realize it'd be really easy to use the GitHub editor to fix this, but I really appreciate contributions like this one, so if you're up for it, 
would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)? However you'd like to do it is good with me.

Also: Airbnb is using glamorous!?!?!?! :heart_eyes: :heart_eyes:

**Comment by ljharb** [comment]
@kentcdodds airbnb uses storybook, which uses glamorous - so, transitively, yes! <3

**Comment by kentcdodds** [comment]
Hey, I'll take all the transitive-ness I can get :heart: :wink:

**Comment by kentcdodds** [comment]
Also that explains the spike in downloads I just noticed http://npmcharts.com/compare/glamorous 😅

**Comment by kentcdodds** [comment]
Fixed! Thanks a bunch :tada:
