### ISSUE TITLE
Support jsxstyle components

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#20]
https://github.com/smyte/jsxstyle experts several components. Glamorous exports element components that resemble the API. In addition to those element components, I'd like to also export the jsxstyle components because they have merit and make it more straightforward for people used to that API. We could learn from what glamor did to support this: https://github.com/threepointone/glamor/blob/master/src/jsxstyle.js

I expect this would just add a handful of lines of code...

**Comment by paulmolluzzo** [comment]
This can be closed I think now that there's [`glamorous-jsxstyle`](https://github.com/paulmolluzzo/glamorous-jsxstyle/). 😀

**Comment by kentcdodds** [comment]
Next up, #25!

**Comment by paulmolluzzo** [comment]
Yeah but that should be done in this package directly.

**Comment by kentcdodds** [comment]
Correct :+1:
