### ISSUE TITLE
Debugging classnames

### ISSUE THREAD

**Issue by mattcolman** [paypal/glamorous#209]
Hi, 

I've come from using jss to glamorous and my life is now ~250% better.

The only thing I miss from jss is that debugging in the Chrome Elements tab was much easier as classnames were named by the developer, rather than the auto-generated name from glamorous. You can see here it's very hard to figure out what component is what...

![2017-07-05 10-26-42](https://user-images.githubusercontent.com/1013215/27845032-a3faa41e-616d-11e7-96da-e6e9cde2cd5c.png)

I can't really think of a solution for this. I guess if I could name the class that would be helpful, although it would seem like double handling as I've already named the component.

I know about this https://github.com/bernard-lin/babel-plugin-glamorous-displayname but it only works in the React tab, and actually I can't get this plugin working anyways...

Thanks!!!!

**Comment by kentcdodds** [comment]
Check this out: https://github.com/paypal/glamorous/blob/master/README.md#config
Will be the default in the next breaking change 😀

**Comment by kentcdodds** [comment]
In addition, you can always provide whatever class names you want:

```js
glamorous.div({}, 'my-custom-class-name')
```

Or also:

```js
const MyDiv = glamorous.div({})
<MyDiv className="my-custom-class-name" />
```

**Comment by mattcolman** [comment]
oh cool! I guess I need to get that plugin working then...
Thanks!
