### ISSUE TITLE
Add example using jest-glamor-react

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#21]
https://github.com/kentcdodds/jest-glamor-react
Because it's super cool!

**Comment by pksjce** [comment]
Hey! I wanted to pick this up. I think I should create an example folder for this as we'd like to have the snapshots also? Do you recommend I make the example here or in `jest-glamor-react` ?

**Comment by kentcdodds** [comment]
Hi @pksjce! I think you're right, we should probably have an `examples` directory for stuff like this. I'm thinking: `examples/with-jest-glamor-react` and it'd have a `README.md` explaining why, what, and how for the example. It should probably have a `package.json` but definitely exclude the `node_modules`.

If you want to take it on, you could also move the `other/EXAMPLES.md` to `examples/README.md` and update the examples badge link on the README.md to point to `examples/READEME.md` :+1:

Thanks a bunch!
