### ISSUE TITLE
add component factory props to typescript typings

### ISSUE THREAD

**Issue by sjansen** [paypal/glamorous#211]
Component factory props are not included in the Typescript typings.

When using a stateless component function, I get the following error: `error TS2459: Type '{ children?: ReactNode; }' has no property 'className' and no string index signature.`

I'm playing with Glamorous and Typescript in order to learn both. I've learned just enough to create a work around, but not enough to improve the typings:

```typescript
interface glamorousComponentFactoryProps {
  children?: React.ReactNode;
  className?: string;
}
const Arrow = glamorous(
  ({className}: glamorousComponentFactoryProps) => (
    <svg className={className} viewBox="0 0 100 50">
      <polyline points={`0,0 100,0 50,50`} />
    </svg>
  )
)({
  fill: '#fff',
  height: 5,
  margin: 5,
  width: 10,
});
```

Perhaps someone with more Typescript experience could propose a fix?

**Comment by luke-john** [comment]
Hey @sjansen great to hear you're giving typescript and glamorous a go.

This should already be typed, the structure you are looking for I think is the following.

```
interface Props {
    classname: string
}

const ComponentToWrap: React.SFC<Props> = (props) => (
    <svg className={props.classname} viewBox="0 0 100 50">
        <polyline points={`0,0 100,0 50,50`} />
    </svg>
)

const Arrow = glamorous(ComponentToWrap)({
    fill: '#fff',
    height: 5,
    margin: 5,
    width: 10,
})
```

I've just put our internal styleguide up as a [gist](https://gist.github.com/luke-john/b62e7343fd7859f5fd100afd9a3bccb6) which you may find helpful for using typescript with glamorous.

This would also be a good example to add to the [typescript usage guide](https://github.com/paypal/glamorous/blob/master/other/TYPESCRIPT_USAGE.md) if you'd feel comfortable [submitting a pull request](http://makeapullrequest.com/).

**Comment by kentcdodds** [comment]
Thanks @luke-john! I'm moving this issue over to the [glamorous website repo](https://github.com/kentcdodds/glamorous-website/issues/223). Feel free to open a PR there! Thanks!
