### ISSUE TITLE
[Proposal] Passing the computed styles object to each dynamic function?

### ISSUE THREAD

**Issue by wsmd** [paypal/glamorous#213]
- `glamorous` version: 3.23.5
- `glamor` version: 3.0.0-2
- `react` version: 15.6.1

**First of all:**
- sorry I couldn't think of a better title
- this is a not an "issue" per se, but rather a question or an idea
- I'm not sure if this issue should be posted on this repo or on `glamor` itself

but I think it's worth the shot.

**The "Problem"**

Assuming that

> the `glamorousComponentFactory` accepts any number of style object arguments. These can be style objects or functions which are invoked with props on every render and return style objects.

Is it possible to pass the computed/accumulator style object to each function in the list of arguments? It's kinda like how `Array#reduce` work.

Here's an example:

```javascript
glamorous.span({
  props => ({ /* return dynamic style from props */ }),
  (props, theme, styles /* 👈 accumulator */) => ({
    /* another dynamic object base on the output of the previous dynamic object */
  });
});
```

**Relevant code:**

E.g. say I have a button component that accepts an **_optional, arbitrary_** `backgroundColor`. I'd like to get the contrast text `color` (either black or white) that fits well on the background:

<img src="https://user-images.githubusercontent.com/2100222/27991626-7067cbf0-644b-11e7-823f-0372ab14276e.png" width="188" />

 For example:

```javascript

function getContrastColor(color) {
  return /* do some magic */ ? 'black' : 'white';
}

const defaultStyles = { backgroundColor: 'blue' };
const dynamicStyles = props => ({ backgroundColor: props.backgroundColor });
const dynamicColor = (props, theme, styles) => ({
  // getting the contrast color regardless if it was dynamic or static
  color: getContrastColor(styles.backgroundColor),
});

const Button = glamorous.button(defaultStyles, dynamicStyles, dynamicColor);
```

I can obviously do it this way:

```js
const defaultStyles = { backgroundColor: 'blue', color: 'white' };
const dynamicStyles = props => ({
  backgroundColor: props.backgroundColor,
  color: props.backgroundColor && getContrastColor(props.backgroundColor)
});
```

but that's the only example I can think of right now 😕. I wonder if it something that can be beneficial for other use cases 🤔

Can this potentially be part of `glamorous`? Anything would prevent implementing it? Are there any other ways to achieve something similar?

**Comment by luke-john** [comment]
Hey @wsmd, I can see where that sort of pattern would be useful.

You could use a helper method like follows to achieve what you've described above.

```js
/*
export type StyleObject = Styles
export type StyleFunction = (
  props: Props,
  theme?: Theme
) => Styles
type arrayOfStyleObjectOrMethod = Array<StyleObject | StyleFunction>
*/

const evaluateSequentiallyComputedStyles = (...arrayOfStyleObjectOrMethod) => (props, theme) => {
  let styles = {}

  for (const styleObjectOrMethod of arrayOfStyleObjectOrMethod) {
    if (isFunction(styleObjectOrMethod)) {
      styles = {
        ...styles,
        ...styleObjectOrMethod(props, theme, styles)
      }
    }

    styles = {
      ...styles,
      ...styleObjectOrMethod,
    } 
  }
  
  return styles
}

const sequentialCompoutedStyles = evaluateSequentiallyComputedStyles(
  defaultStyles,
  dynamicStyles,
  dynamicColor
)


const Button = glamorous.button(
  sequentialCompoutedStyles
);
```

[codesandbox example](https://codesandbox.io/s/76qJyl00G)

**Comment by wsmd** [comment]
Thanks for such a detailed answer, @luke-john. It's more than I was expecting! I feel really motivated to turn this idea into a package. Especially if you don't think it should be part of glamorous. I'm sure many folks would find it useful.

Maybe one day it will make its way to glamorous 😉 .

**Comment by kentcdodds** [comment]
Thanks @luke-john!

Note: Rather than using `object spread` use an array. Otherwise merging nested styles/media queries/etc wont work as expected. If you return an array, glamor will merge it as you would want it to be merged.

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this. Please let us know when you've made a package and we can add it to the `integrations` on the [new website](https://github.com/kentcdodds/glamorous-website)!
