### ISSUE TITLE
Make config.useDisplayNameInClassName default to true

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#216]
This would be a breaking change, but we'll be doing one of those soonish so let's make a PR to prepare for that :+1:

EDIT: Turning this into a `first-timers-only` issue! And I'm letting @Oalbacha have first dibs (because I kinda messed up his chances on #185). So I'm not going to actually label this `first-timers-only` for a few hours just to make sure he gets a shot at it.

Hi there! 👋

This is a ["first-timers-only"](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issue. That means that we will only accept a pull request from someone who's never contributed to open source before! 🎉 If that's you, read on. If that's not you, spend the time instead setting up an issue like this for someone else in one of your own projects 😉

So here's how things are going to go, I'll explain clearly what needs to happen for this issue to be closed. You "claim the issue" by commenting on here saying that you'd like to work on it as soon as you're able to start. Then you follow the steps I've outlined. Feel free to ask any questions if you get stuck along the way.

1.  Make sure to claim the issue by commenting that you're working on it right now.
2.  Probably the most useful thing you could do before getting started is to watch [this free video course](http://kcd.im/pull-request). That will help you understand the terms and concepts of the following steps.
3.  Read [the contributing guidelines](https://github.com/paypal/glamorous/blob/master/CONTRIBUTING.md)
4.  Fork the repo
5.  Clone your fork
6.  Create a branch for your changes (`git checkout -b pr/default-display-name`)
7.  Open the directory in your favorite text editor
8.  Normally, this is the part that you'd write a test to verify the bug exists, or enable one that I've written for you, but testing this particular bug is more work than it's worth, so we'll skip that part.
9.  Open the file [`src/create-glamorous.js`](https://github.com/paypal/glamorous/blob/5e9b34e6a0e249e8b224ddec477096fff5a1aa05/src/create-glamorous.js) and change [this line](https://github.com/paypal/glamorous/blob/5e9b34e6a0e249e8b224ddec477096fff5a1aa05/src/create-glamorous.js#L14) to: `glamorous.config = {useDisplayNameInClassName: process.env.NODE_ENV !== 'test'}` (and remove the `TODO` comment above)
10. Update [the `docs/FAQ.md`](https://github.com/paypal/glamorous/blob/5e9b34e6a0e249e8b224ddec477096fff5a1aa05/docs/FAQ.md) to remove the words: "and [this config](https://github.com/paypal/glamorous#usedisplaynameinclassname)" (because that's the default now)
11. Update [the `README.md`](https://github.com/paypal/glamorous/blob/5e9b34e6a0e249e8b224ddec477096fff5a1aa05/README.md) in the docs for [`useDisplayNameInClassName`](https://github.com/paypal/glamorous/blob/5e9b34e6a0e249e8b224ddec477096fff5a1aa05/README.md#usedisplaynameinclassname) to say: "Defaults to `process.env.NODE_ENV !== 'test'`".
12.  Run `npm start contributors.add` and follow the prompt (you're contributing `code`)
13. Run `npm start test.update` to run tests and update snapshots for these changes (if anything fails, go ahead and continue anyway, we'll help you figure it out)
14.  Commit your changes. You can do something like: `git commit -am "feat(config): change the default of useDisplayNameInClassName" --no-verify`
15.  Push your changes to your forked repo
16.  Open a pull request
17.  Fill out the prefilled PR description
18.  Wait patiently for a response
19.  Address any feedback you receive and push updates (if necessary)
20.  Get merged
21.  Celebrate and tweet! Woo! 🎉

Thanks so much for your contribution! We're here to help you land it!

**Comment by Oalbacha** [comment]
Thanks Kent, let me try 😁

**Comment by Oalbacha** [comment]
Working on it now! :-)

**Comment by kentcdodds** [comment]
Nice! Thanks @Oalbacha!

**Comment by Oalbacha** [comment]
Hi Kent,
I am amending the README.md

Do I delete:
"Defaults to `false` (will default to `true` in a future major release).
This should _only_ be used for debugging purposes. It is strongly discouraged
from referencing this className in your CSS due to the level of indirection that
will add (making it easier for you to break something when refactoring in the
future)."

when I add
"Defaults to process.env.NODE_ENV !== 'test'"

**Comment by kentcdodds** [comment]
Make that whole section look like this:

````
Defaults to `process.env.NODE_ENV !== 'test'`. This should _only_ be used for debugging purposes. It is strongly discouraged from referencing this className in your CSS due to the level of indirection that will add (making it easier for you to break something when refactoring in the future).

Example:

```jsx
import glamorous from 'glamorous'
glamorous.config.useDisplayNameInClassName = true

const MyComponent = props => <div {...props} />
const myGlamorousComponentFactory = glamorous(
  MyComponent,
  {displayName: 'MyGlamorousComponent'}
)

const MyGlamorousComponent = myGlamorousComponentFactory()
<MyGlamorousComponent />
// renders <div class="css-nil MyGlamorousComponent" />
```

If you don't want to provide the `displayName` for all of your components, then you can use [this babel-plugin](https://www.npmjs.com/package/babel-plugin-glamorous-displayname). Otherwise, the className will be simply: `glamorous(MyComponent)`
````

The only change is the first sentence :smile:

**Comment by Oalbacha** [comment]
I am getting this error when I run step 12 `npm start contributors.add` in my git bash

```
npm ERR! path C:\Users\o_alb\Desktop\glamorous\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\o_alb\Desktop\glamorous\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\o_alb\AppData\Roaming\npm-cache\_logs\2017-07-10T17_23_13_874Z-debug.log
```

**Comment by kentcdodds** [comment]
Hmmm... Could you paste more of the output?

**Comment by Oalbacha** [comment]
$ `npm start validate`
```
npm ERR! path C:\Users\o_alb\Desktop\glamorous\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\o_alb\Desktop\glamorous\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\o_alb\AppData\Roaming\npm-cache\_logs\2017-07-10T17_27_08_857Z-debug.log

```

**Comment by kentcdodds** [comment]
Is that all you see? There should be a lot more output. Please share all of that :smile:

**Comment by Oalbacha** [comment]
npm version 5.0.3 but when i try to `npm start validate` as per the contributing.md doc I get an error

![image](https://user-images.githubusercontent.com/17005317/28031002-f752dc9c-65b6-11e7-88be-629cad2621d9.png)

**Comment by kentcdodds** [comment]
Huh, that's weird! It's saying that there's no `package.json` file. Could you verify that you didn't delete it locally or something? There should definitely be a `package.json` file. Make sure you're in the repo and that there's a `package.json` in the root directory of the repo.

Also, it mentions that you should commit the `package-lock.json` file, don't do that :smile:

**Comment by Oalbacha** [comment]
package.json is part of the directory, look:

![image](https://user-images.githubusercontent.com/17005317/28031224-a8eefbac-65b7-11e7-90fb-523346e5c89b.png)

**Comment by Oalbacha** [comment]
Please note I haven't staged or committed changes to the file yet before running n`pm start validate` or `npm start contributors.add`

**Comment by kentcdodds** [comment]
Yes, that's very odd. Have you made any changes to the `package.json` file?

**Comment by Oalbacha** [comment]
Not at all. Shall I start over?

**Comment by kentcdodds** [comment]
I suppose so... If that doesn't work, then maybe we can do a video chat to figure out what's going on.

**Comment by Oalbacha** [comment]
Perfect. Give me a minute to start over

**Comment by Oalbacha** [comment]
Same issue :(

**Comment by kentcdodds** [comment]
Jump in here: https://hangouts.google.com/hangouts/_/aklcylu5nvgbjbiziv5zw4xwkme

**Comment by Oalbacha** [comment]
```
npm start contributors.add

> glamorous@0.0.0-semantically-released start C:\Users\o_alb\Desktop\glamorous
> nps "contributors.add"

'nps' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! glamorous@0.0.0-semantically-released start: `nps "contributors.add"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the glamorous@0.0.0-semantically-released start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\o_alb\AppData\Roaming\npm-cache\_logs\2017-07-10T18_00_07_036Z-debug.log

```

**Comment by kentcdodds** [comment]
Install dependencies with `npm install --no-pacakge-lock`

**Comment by Oalbacha** [comment]
https://hangouts.google.com/hangouts/_/aklcylu5nvgbjbiziv5zw4xwkme

**Comment by kentcdodds** [comment]
Sorry, having lunch right now.

**Comment by Oalbacha** [comment]
Ok please let me know when you are done :)

**Comment by kentcdodds** [comment]
Did you get dependences installed?

**Comment by oalbacha** [comment]
Yes but selected wrong enty of contribution option. Can you hangout for a minute?

(https://hangouts.google.com/hangouts/_/aklcylu5nvgbjbiziv5zw4xwkme)

**Comment by oalbacha** [comment]
Hi Kent, Sorry can you help me make a PR. I am not sure what I'm doing :)

**Comment by kentcdodds** [comment]
Sure, how can I help?

**Comment by oalbacha** [comment]
https://hangouts.google.com/call/aklcylu5nvgbjbiziv5zw4xwkme

**Comment by kentcdodds** [comment]
Thanks @oalbacha! This has been merged into `next` and will be released when `next` is merged into `master` (soonish hopefully)
