### ISSUE TITLE
Help implementing something in jest-glamor-react

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#217]
We're planning a breaking change and a release of the website soonish (hopefully in a week or two) and I would love some help implementing [this](https://github.com/kentcdodds/jest-glamor-react/issues/11) breaking change in `jest-glamor-react` to go out at around the same time. Anyone wanna help with that?

**Comment by nitin42** [comment]
Can I help with this ?

**Comment by kentcdodds** [comment]
Someone's started working on it. Feel free to [review this though](https://github.com/kentcdodds/jest-glamor-react/pull/12) :smile:

**Comment by nitin42** [comment]
Any other fresh issues or something? 
(I've plenty of time before my college starts so I'll be happy to help with anything)

**Comment by kentcdodds** [comment]
Oh, that's awesome of you @nitin42! Check out [this list](https://twitter.com/kentcdodds/status/884551155031912448) :smile:

Also, if you're interested in another challenge, you might look into [nps](https://github.com/kentcdodds/nps) which is highly useful but could use a little love :smile:

**Comment by kentcdodds** [comment]
This is done and released!
