### ISSUE TITLE
remove the theme argument

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#219]
The theme argument can be removed because it's now available in the `props`. Documentation has already [been updated](https://github.com/paypal/glamorous/pull/207), so this change requires that we remove references to `theme` [here](https://github.com/paypal/glamorous/blob/4ea5b3161f65c30b8dbed110a85e4afaf211d973/src/get-glamor-classname.js#L28-L78) and [here](https://github.com/paypal/glamorous/blob/0bfda9fa8e33453b9b71e95ea5683634d1900184/src/create-glamorous.js#L54-L67) (which also means that we can probably remove [these tests](https://github.com/paypal/glamorous/blob/0bfda9fa8e33453b9b71e95ea5683634d1900184/src/__tests__/index.js#L338-L372) as well) :+1:

**Comment by kentcdodds** [comment]
For the benefit of anyone reading this...

You once had code like this:

```javascript
const MyDiv = glamorous.div((props, theme) => ({
  fontSize: theme.main.fontSize,
}))
```

You can now write that like this:

```javascript
const MyDiv = glamorous.div(({theme}) => ({
  fontSize: theme.main.fontSize,
}))
```

**Comment by kentcdodds** [comment]
For anyone else who wants to help, [this](https://github.com/paypal/glamorous/issues/220) would be really helpful.

**Comment by tdeschryver** [comment]
Is it OK if I'm taking this one? (I want to get familiar with the code-base :smile:)
Normally I should be able to take a look at the codemod tomorrow too, if no one has taken it by then.

**Comment by kentcdodds** [comment]
Sounds awesome!

**Comment by kentcdodds** [comment]
This has been merged into `next`. Will be released 🔜ish
