### ISSUE TITLE
make a codemod for the theme argument change

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#220]
We're making [a breaking change](https://github.com/paypal/glamorous/issues/219) and it'd be super to get a codemod for this!

If you've never written a codemod before, never fear! This is a lot of fun! You can basically just write a babel plugin (even if it's just in [astexplorer.net](https://astexplorer.net/)) and I'll help you turn it into a codemod people can run on their code to automatically upgrade their components. See [this](https://youtu.be/CFQBHy8RCpg?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf). It should help give you an idea of what to do :smile:

If you want to contribute, but are unsure you are ready to write the plugin, you could really help by writing some examples (just in comments on this issue is fine) of code that would need to be changed to handle this breaking change.

**Comment by liadbiz** [comment]
Can I help with this? I have some experience on making babel plugin...

**Comment by kentcdodds** [comment]
Go for it! Thanks!

**Comment by tdeschryver** [comment]
@liadbiz During the day I've set up a testing environment with the plugin already there (with no code inside). Don't know if its handy, but thought I would share.

See [here](https://github.com/tdeschryver/glamorous/tree/codemod-remove-codemod/other/codemod).

The thought was to add some examples inside the fixtures folder, and run `jest` to test out the desired result.

**Comment by kentcdodds** [comment]
Nice! You might wanna add [`babel-plugin-tester`](https://github.com/babel-utils/babel-plugin-tester) to that :smile: Could make your life much easier.

**Comment by tdeschryver** [comment]
Oh, indeed! I didn't know that existed.
I'll definitely check it out in detail this week, thanks!

**Comment by liadbiz** [comment]
@tdeschryver  oh you are so efficient, seems like you have finished code stuff :+1: You can go for it !

**Comment by tdeschryver** [comment]
What is the desired result if you have something like this:
```
// input
const Three = glamorous.div((props, theme) => ({
  fontSize: theme.main.fontSize,
  color: props.important ? 'red' : 'black',
}))

// output 1
const Three = glamorous.div(props => ({
  fontSize: props.theme.main.fontSize,
  color: props.important ? 'red' : 'black',
}))

// output 2
const Three = glamorous.div(({theme, important})=> ({
  fontSize: theme.main.fontSize,
  color: important ? 'red' : 'black',
}))

// output 3???
```

I would say, lets go for output 2!

---

And another question; I currently have these simple test cases, is it OK to open a PR if all of these are correctly being transformed and then ask for more test cases? 
(if someone has some, please feel free to post them here)

```
// should transform, only use theme
const One = glamorous.div((props, theme) => ({
  fontSize: theme.main.fontSize,
}))

// should transform, only use theme, third argument stays
const Two = glamorous.div((props, theme, tripple) => ({
  fontSize: theme.main.fontSize,
}))

// should transform, combine props and theme
const Three = glamorous.div((props, theme) => ({
  fontSize: theme.main.fontSize,
  color: props.important ? 'red' : 'black',
}))

// should not transform
const Four = glamorous.div(({theme}) => ({
  fontSize: theme.main.fontSize,
}))
```

**Comment by kentcdodds** [comment]
> What is the desired result if you have something like this

I like Option 2. In addition:

```javascript
// input
const Three = glamorous.div(({important}, theme) => ({
  fontSize: theme.main.fontSize,
  color: important ? 'red' : 'black',
}))

// should output
const Three = glamorous.div(({important, theme}) => ({
  fontSize: theme.main.fontSize,
  color: important ? 'red' : 'black',
}))
```

> I currently have these simple test cases, is it OK to open a PR if all of these are correctly being transformed and then ask for more test cases?

Sure!

Thanks!

**Comment by tdeschryver** [comment]
Yep, that was a case I was just testing out. Thanks for pointing it out.
I must say this AST thing is a real roller coaster (in a good way)!

**Comment by tdeschryver** [comment]
I think I have some decent test cases ready - [AST explorer](https://astexplorer.net/#/gist/8ca6290fb86a601610f228a6f05d5e37/b19e148e656efe72e6f3744fcd0dda0decbd3bbe) or [my branch](https://github.com/tdeschryver/glamorous/tree/codemod-remove-codemod/other/codemod). 
Would be helpful if someone can take a look and check if this is the desired output, if so I'll try to send a PR tomorrow.

**Comment by kentcdodds** [comment]
Looking pretty great!

This is wrong:

```javascript
// should transform, merge props (object) and theme (properties)
const Five = glamorous.div((props, {main}) => ({
  fontSize: main.fontSize,
  color: props.important ? 'red' : 'black',
}))

// should actually transpile to:

// should transform, merge props (object) and theme (properties)
const Five = glamorous.div((props) => ({
  fontSize: props.theme.main.fontSize,
  color: props.important ? 'red' : 'black',
}))
```

And this:

```javascript
// should transform, merge props (properties) and theme (properties)
const Six = glamorous.div(({important}, {main}) => ({
  fontSize: main.fontSize,
  color: important ? 'red' : 'black',
}))

// should transpile to:

const Six = glamorous.div(({important, theme: {main}}) => ({
  fontSize: main.fontSize,
  color: important ? 'red' : 'black',
}))
```

Also, I wonder how hard it would be to transpile this:

```javascript
const Six = glamorous.div(({important}, {main: {fontSize: theFontSize}}) => ({
  fontSize: theFontSize,
  color: important ? 'red' : 'black',
}))

// should be:

const Six = glamorous.div(({important, theme: {main: {fontSize: theFontSize}}}) => ({
  fontSize: theFontSize,
  color: important ? 'red' : 'black',
}))
```

And this:

```javascript
const Six = glamorous.div((props, {main: {fontSize: theFontSize}}) => ({
  fontSize: theFontSize,
  color: props.important ? 'red' : 'black',
}))

// should be:

const Six = glamorous.div(props) => ({
  fontSize: props.theme.main.fontSize,
  color: props.important ? 'red' : 'black',
}))
```

Do you think you could handle that? If not, then don't worry about it. That's probably a bit of an edge case :smile:

**Comment by tdeschryver** [comment]
I'll give it a shot and see how it goes.
Thanks for the feedback!

**Comment by tdeschryver** [comment]
Seems like the first edge case is already solved with fixing `Six` :sweat_smile: 
The second one is almost correct, should be doable!

**Comment by tdeschryver** [comment]
Hmmm... I've been able to transform all of the cases, but in a hack-y way...
Then added some real world examples (from the glamorous website) and bumped into this example which is being transformed wrong.
```
const EditorContainer = glamorous.div(
  {
    display: 'flex',
    justifyContent: 'stretch',
    alignItems: 'stretch',
  },
  ({theme: {misc, mediaQueries}}) => ({
    boxShadow: misc.boxShadow,
    flexDirection: 'column',
    [mediaQueries.mediumUp]: {
      flexDirection: 'row',
    },
  }),
)
```
Maybe someone else can take a look at this issue? Because to be honest I think I'm not right guy for taking this one. 
Examples can be found [here](https://github.com/tdeschryver/glamorous/tree/codemod-remove-codemod/other/codemod)

**Comment by tdeschryver** [comment]
I've added some more test cases, but I feel like missing some (edge) cases,
@kentcdodds Could you let me know what to do with this please (add more cases, drop it, create a PR, ...), because I'm unsure about my skills for solving this issue :confused:

**Comment by kentcdodds** [comment]
Ok, I've successfully run this on the glamorous website and made a few modifications. I think this codemod is ready!
