### ISSUE TITLE
How to use :before :after pseudo-classes?

### ISSUE THREAD

**Issue by mbrochh** [paypal/glamorous#223]
I'm sorry, I know this is a stupid question, but I'm kind of having a blackout here (in 10 years of web-design I somehow got away with almost never using pseudo-classes, shame on me)...

I want to create a React component `<IconDiamond>`, stealing the CSS code from here: https://css-tricks.com/examples/ShapesOfCSS/ (scroll down to `Diamond Square`).

So, naive as I am, I tried this:

```
from glamorous import 'glamorous'

const IconDiamond = glamorous.div(
  {
    width: 0,
    height: 0,
    border: '50px solid transparent',
    border-bottom-color: 'red',
    position: ;relative',
    top: '-50px',
    ':after': {
      content: '',
      position: 'absolute',
      left: '-50px',
      top: '50px',
      width: '0',
      height: '0',
      border: '50px solid transparent',
      border-top-color: 'red',
    }
  },
)
```

I also tried this:

```
import { after } from 'glamor'

const IconDiamond = glamorous.div(
  {
    width: 0,
    height: 0,
    border: '50px solid transparent',
    border-bottom-color: 'red',
    position: ;relative',
    top: '-50px',
  },
  after({
    content: '',
    position: 'absolute',
    left: '-50px',
    top: '50px',
    width: '0',
    height: '0',
    border: '50px solid transparent',
    border-top-color: 'red',
  }),
)
```

Both versions don't work... the `after` part is never applied.

My guess is that in the example, the styles are applied to `#diamond` and `#diamond:after` but when using glamorous, I'm not really applying `after` to any known className? Is my syntax wrong? Or do I need write a React component that has a div with `className` and then use `#myClassName:after` in the glamorous style definition?

**Comment by luke-john** [comment]
Hey @mbrochh, great to hear you're giving glamorous a go.  You're quite close to achieving what you want.

A couple of things to keep in mind with glamorous however.

* css properties must be camel-cased along the lines of react https://facebook.github.io/react/docs/dom-elements.html#style
*  when using the content property you need to ensure the the quotes are included in the passed string ie `content: `''`

See below for a link to working example of what you're trying to achieve and the code snippet of how that should look.

[code sandbox example](https://codesandbox.io/s/gPZxvVAk)

```js
const IconDiamond = glamorous.div(
  {
    width: 0,
    height: 0,
    border: '50px solid transparent',
    borderBottomColor: 'red',
    position: 'relative',
    top: '-50px',
    '&::after': {
      content: `''`,
      position: 'absolute',
      left: '-50px',
      top: '50px',
      width: '0',
      height: '0',
      border: '50px solid transparent',
      borderTopColor: 'red',
    }
  },
)
```

This would be a helpful information to add to the README for other users who have not used css-in-js before if you'd feel comfortable [submitting a pull request](http://makeapullrequest.com/).

**Comment by mbrochh** [comment]
@luke-john thank you so much! It works.

I'm sorry, I messed up my code example pretty bad, was just copy and pasting code from the CSS shape website and then just fixing indentation, semicolons and adding quotation marks... I forgot to also rename the css attributes to camelCase etc.

My real problem was that mysterious `&::after` selector. So now I did some more digging and I found this: https://github.com/threepointone/glamor/blob/master/docs/selectors.md - so I learned that `&` refers to the element itself.

Then I also found this: https://www.w3schools.com/cssref/css_selectors.asp and learned that `::after` is actually the correct syntax for that CSS selector.

Days where I learn new things are the best days \o/

Thanks again!

**Comment by kentcdodds** [comment]
Glad things got worked out here (thanks @luke-john)!

We're still working on the website, but the beginner tutorial should help people about this (very common) pitfall. https://rc.glamorous.rocks/getting-started/

Please join us in contributing if you are able! There are many [things](https://github.com/kentcdodds/glamorous-website/issues) that could use your help 😀

**Comment by razat249** [comment]
How to use **text selection** pseudo selector. I mean `::selection` in css
