### ISSUE TITLE
Support kebab-case

### ISSUE THREAD

**Issue by mattcolman** [paypal/glamorous#224]
Hi, 

Docs say you support `polished` but certain helpers in polished produce standard css names (kebab-case) which throw warnings in the console.

See my use of polished.padding here https://codesandbox.io/s/nJ6nE73R

Notice in the console there are warnings `Warning: Unsupported style property padding-left. Did you mean paddingLeft?`

Thanks!

**Comment by kentcdodds** [comment]
Hi @mattcolman!

Hmmm... I was under the impression `polished` was supposed to always produce `camelCase` properties. cc @nikgraf @bhough 

In any case, this wouldn't be resolved by glamorous, this would have to be done in [glamor](https://github.com/threepointone/glamor). glamorous simply forwards these properties to `glamor`. With that in mind I'll close this issue, do you mind filing an issue there and suggesting a solution?

Thanks! And good luck!

P.S. if this isn't something that will be resolved, it may be good to add a note to the polished integration example on [the new website](https://github.com/kentcdodds/glamorous-website/blob/master/pages/integrations/content/polished.md)...

**Comment by bhough** [comment]
@kentcdodds @mattcolman this has been merged into our V2 branch which I'm aiming to get out by the end of the month, so that should resolve this issue.

**Comment by kentcdodds** [comment]
Wonderful! :tada: thanks so much!

**Comment by bhough** [comment]
✨ polished 1.3 moves to camel-casing and is out now: https://github.com/styled-components/polished/releases/tag/v1.3.0

**Comment by mattcolman** [comment]
Thanks!!!
