### ISSUE TITLE
Glam-props (like styled-props) ?

### ISSUE THREAD

**Issue by bulby97** [paypal/glamorous#225]
There is already a good explanation about the utility of this lib [here](https://github.com/RafalFilipek/styled-props)

I found this very useful with styled-components and I would like to do it for glamorous too.
The problem is that glamorous don't support functions as rule values like this : 

```js
let MyDiv = styled.div({
   color: 'red',
   fontSize: props => props.big ? '20px' : '10px',
})
```

So it's not possible to do the following

```js
let MyDiv = styled.div({
   color: 'red',
   fontSize: glamProps(styles.fontSize)
})
```

So I did it by passing an object instead

```js
const styles = {
  size: {
    big: 30,
    medium: 21
  },
  lineHeight: {
    big: 30,
    medium: 24
  },
  fontFamily: {
    primaryFont: globals.font.title,
    secondaryFont: globals.font.heading
  },
  color: {
    default: globals.color.black,
    reverse: globals.color.white
  }
}

const Title = glamorous.text(
  glamProps({fontSize: styles.size, default: 'size'}),
  glamProps({lineHeight: styles.lineHeight, default: 'lineHeight'}),
  glamProps({fontFamily: styles.fontFamily, default: 'fontFamily'}),
  glamProps({color: styles.color, default: 'color'})
)

Title.defaultProps = {
  color: 'default',
  size: 'big',
  lineHeight: 'big',
  fontFamily: 'primaryFont'
}
```

And here is glamProps function
```js
export default obj => props => {
  const objKey = Object.keys(obj)[0]
  const map = obj[objKey]
  const keysFromProps = Object.keys(map).filter(key => props[key] !== undefined)

  const keyFromProps = keysFromProps[0]
  if (map[keyFromProps]) {
    return { [objKey]: map[keyFromProps] }
  }

  const fallback = Object.values(obj)[1]
  if (fallback) {
    if (props[fallback] && map[props[fallback]]) {
      return { [objKey]: map[props[fallback]] }
    }
  }
}
```

My question is the following : is this useful ? Is there a better way to do it ? What if I want to use theme variables :( ? 

How do you guys handle that kind of glamorous components when dealing with a lot of css properties modified by props ?

```jsx
<Button primary small />
<Button secondary big />
```

**Comment by luke-john** [comment]
Hey @bulby97, looks like a fairly handy helper method.

You could setup a `useGlamProps` helper method to be passed to a glamorous component factory which would then allow you to write something like follows and follow the existing `styled-props` style of writing `css-in-js`.

```
const MyDiv = styled.div(
    ...
    useGlamProps((glamProps) => ({
        fontSize: glamProps(styles.size)
    }))
)
```

I've setup a [codesandbox example with useGlamProps](https://codesandbox.io/s/EkJ0DYlg) that shows how this would work.

If you do end up using this pattern and turning it into a package please let us know as it would be great to add it to the `integrations` section on the [new website](https://github.com/kentcdodds/glamorous-website)! 


At my workplace we've built some internal helpers to achieve something similar. See below for some non working example code that demonstrate how it works.

```
const theme = {
    // this is used by createComponentTheme to select component theme
    'toplevel-theme-key': 'toplevel-theme-key-value',

    font: 'Sans',
}

// the toplevel-theme-key-values accept either an object or a function which has props similar to glamorouses interface.
const componentTheme = createComponentTheme({
    'toplevel-theme-key-value': (props) => ({
        fontWeight: props.large ? 600 : 400,
    }),
    'toplevel-theme-key-othervalue': {
        fontWeight: 500,
    },
})

const MyDiv = glamorous.div(
    { /* static styles */ },
    // theme is the glamorous theme passed to the glamorous component factory argument
    productTheme((theme) => ({
        fontFamily: theme.font,
    })
    // theme is based on the current product theme and selects the component theme above
    componentTheme((theme) => ({
        fontWeight: theme.fontWeight,
    })
)

const Component = () => (
    <ThemeProvider theme={theme}>
        <MyDiv large>
    </ThemeProvider>
)
```

**Comment by kentcdodds** [comment]
Thanks for that @luke-john!

Another thing to consider is that even though glamorous doesn't support inline functions, it does support something like this:

```javascript
const MyDiv = glamorous(
  {color: 'red'},
  props => ({fontSize: props.big ? 20 : 10}),
  // ... add as many of these as you like
)
```

Not quite as ergonomic, but if you're building helper functions (like with `styled-system`) it actually [looks quite nice](https://codesandbox.io/s/mNEBG3OR):

```javascript
import { space, width, fontSize } from 'styled-system'

const Box = glamorous.div(space, width, fontSize)
```

**Comment by kentcdodds** [comment]
Oh, also:

> If you do end up using this pattern and turning it into a package please let us know as it would be great to add it to the `integrations` section on the [new website](https://github.com/kentcdodds/glamorous-website)!

That would be awesome. You could also add it as [an example](https://github.com/kentcdodds/glamorous-website/tree/master/pages/examples/content) if you'd rather not worry about making it into a package.

I think that this is as far as we'll go in glamorous though, so I'm going to go ahead and close this. Please feel free to continue to comment and if you have any suggestions, we can reopen and discuss :smile:

**Comment by bulby97** [comment]
Thanks guys !

**Comment by bulby97** [comment]
@luke-john Will do !

What do you think about this ?
I did find a way to pass theme, dunno if it's the best. 
I implemented bindStyles too, like styledProps did.

https://codesandbox.io/s/qYv7QqlMD

**Comment by luke-john** [comment]
@bulby97 looking great. You may want to consider simplifying the useBindStyles along the following lines.

```
  bindStyles(stylesToBind)(styles => ({
    padding: styles.padding,
    borderRadius: styles.borderRadius,
  }))
```

See below for a codesandbox example of how this could work.

https://codesandbox.io/s/Q1oMKrQg9

**Comment by bulby97** [comment]
Awesome! Thank you! I really need to increase my coding skills 😅

**Comment by bulby97** [comment]
@luke-john @kentcdodds here we go ! https://github.com/bulby97/glam-props

**Comment by kentcdodds** [comment]
Sweet! Wanna make a PR to add it to the [related projects](https://github.com/paypal/glamorous#related-projects)? :smile:

**Comment by bulby97** [comment]
I'm having a talk with the creator of styled-props. Seems like he's planning to make styled-props compatible with most css-in-js libs, so I'll let you know ;)

**Comment by kentcdodds** [comment]
That's great!
