### ISSUE TITLE
Glamorous with glamor v3. glamor/server issue

### ISSUE THREAD

**Issue by grundmanise** [paypal/glamorous#226]
- "glamorous": "3.23.5"
- "glamor": "3.0.0-1",
- "glamor-server": "3.0.0-1"
- "react": "15.6.1",

_**What happened:**_

`glamor/server`: `renderStatic` - works as expected.
`glamor-server`: `renderStatic` - does not work - return empty string.

I thinks it's the compatibility issue between `glamor v3` and `glamorous`.

_**Reproduction:**_

https://github.com/zeit/next.js/tree/v3-beta/examples/with-glamorous

try this project as is:
`renderStatic` -> works as expected.

try this project with "glamorous": "3.23.5" , "glamor": "3.0.0-1" , "glamor-server": "3.0.0-1":
`renderStatic` -> empty string.

**Comment by kentcdodds** [comment]
Thanks for looking into this. It's rather interesting. Do you mind digging further to identify the core issue?

**Comment by grundmanise** [comment]
Have a really busy schedule now.. will try as soon as time will free.

**Comment by kentcdodds** [comment]
Seems like this is probably related: https://github.com/kentcdodds/jest-glamor-react/issues/14

**Comment by threepointone** [comment]
please use glamor v2.

**Comment by kentcdodds** [comment]
Considering v2 is the latest supported version of glamor right now I'll close this. But we're watching and participating in the creation of v3 so don't worry, we'll know when changes need to be made.
