### ISSUE TITLE
Is `tabindex` supported?

### ISSUE THREAD

**Issue by kirkstrobeck** [paypal/glamorous#228]
"glamor": "^2",
"glamorous": "^3.23.5",
"react": "^15.6.1",:

Not sure `tabindex` attribute is supported.

**Comment by kentcdodds** [comment]
It should be. Please follow [the instructions here](https://help.glamorous.rocks) to get help/make an example.

**Comment by kentcdodds** [comment]
[It works](https://codesandbox.io/s/o2j4QkLwA) :smile:

**Comment by felipecocco** [comment]
I just ran into this issue trying to make tabbable divs - passing data-* attributes worked just fine, but  tabindex was never passed onto the html element.
[Minimalist reproduction](https://codesandbox.io/s/jnojvnx655)

**Comment by kentcdodds** [comment]
Hi! The problem in your reproduction is that, in JSX, to set `tabindex`, you use `tabIndex` (capital `I`) :)

**Comment by felipecocco** [comment]
D'oh! There it is! Many thanks, Kent :-)

![](https://media.giphy.com/media/3ornjXIIShZ2MgyyHu/giphy.gif)
