### ISSUE TITLE
Grid properties GridColumnStart and GridRowStart values are being passed as "px" 

### ISSUE THREAD

**Issue by WillowHQ** [paypal/glamorous#232]
- `glamorous` version: using codesandbox
- `glamor` version: codesandbox
- `react` version: codesandbox

Relevant code.

```javascript

```

What you did:

Trying to set the gridColumnStart or gridRowStart property

What happened:

When trying to use grid layout the gridColumnStart or gridRowStart property is not being set. It is attempting to set it to pxs instead of a row or column number. 

![image](https://user-images.githubusercontent.com/5257243/28242106-fce3ed50-6970-11e7-84fc-7bf9b6319870.png)

Reproduction:

https://codesandbox.io/s/MQGn08JLG

Problem description:
I've tested 

Suggested solution:

I think this property value is being turned into pixels and it shouldn't be.

**Comment by WillowHQ** [comment]
When I enter the property manually in the styles tab of dev tools it accepts it.

**Comment by tdeschryver** [comment]
Seems like its already mentioned at threepointone/glamor#274

**Comment by WillowHQ** [comment]
Noted, but since it's not on the main fork, when I searched for it I found nothing. Is there something I should have done differently to prevent this duplication? Second, I'm going to take a look and see if I can fix this, since it's a pretty low priority and that just sounds like a fun time.

**Comment by tdeschryver** [comment]
Don't think so, I was just curious about the bug.
I already opened a PR to fix this.

**Comment by kentcdodds** [comment]
I'll go ahead and close this since it's a glamor issue that's being tracked :+1:

**Comment by kentcdodds** [comment]
Also, thanks for bringing it up @WillowHQ and for addressing it @tdeschryver!

**Comment by tdeschryver** [comment]
Fyi, PR has been accepted and should be included in the next minor release (likely within a week).

**Comment by tdeschryver** [comment]
Fyi, is live in live in glamor@2.20.26.
