### ISSUE TITLE
`react-html-attributes` has peer dependency that is not handled

### ISSUE THREAD

**Issue by fvgs** [paypal/glamorous#236]
- `glamorous` version: 3.23.5
- `glamor` version: 2.20.26
- `react` version: 15.4.2

**What you did:**

Installed `@storybook/react` which depends on Glamorous

**What happened:**

`npm ls` using npm 2 will fail with an extraneous dependency error due to `html-element-attributes` being viewed as an extraneous dependency

**Reproduction:**

Run `npm ls` using npm 2 after installing Glamorous

**Problem description:**

Glamorous depends on react-html-attributes whose package.json includes the following (duplicate) peer dependency:

```json
{
  "dependencies": {
    "html-element-attributes": "^1.0.0"
  },
  "peerDependencies": {
    "html-element-attributes": "^1.0.0"
  },
}
```

Glamorous does not register html-element-attributes as a dependency or as a peer dependency. Thus, npm 2 automatically installs the peer dependency which is treated as an extraneous dependency.

See jackyho112/react-html-attributes#6 for additional context.

**Suggested solutions:**

1) Remove react-html-attributes as a dependency if possible
2) Add html-element-attributes as a dependency or peer dependency to Glamorous
3) Wait for a resolution to jackyho112/react-html-attributes#6

**Comment by kentcdodds** [comment]
Hey @fvgs! Thanks for bringing this to our attention. I'm going to wait on https://github.com/jackyho112/react-html-attributes/issues/6 as that's where the problem lies and where the solution will be made.

I'll go ahead and close this as it's being tracked in https://github.com/jackyho112/react-html-attributes/issues/6 already :+1: thanks again!

**Comment by kentcdodds** [comment]
I've opened https://github.com/jackyho112/react-html-attributes/pull/7
