### ISSUE TITLE
Styles output representation in README

### ISSUE THREAD

**Issue by morajabi** [paypal/glamorous#238]
I saw something in some of code snippets in `README.md`. e.g. in [glamorousComponentFactory](https://github.com/paypal/glamorous#glamorouscomponentfactory) section

In this code snippet: 
``` 
const UnstyledComp = ({ className, children }) => <div className={`${className} other-class`}>{children}</div>
const MyStyledComp = glamorous(UnstyledComp)({ margin: 1 })

<MyStyledComp>content</MyStyledComp>
// rendered output: <div class="<glamor-generated-class> other-class">content</div>
// styles applied: {margin: 1}
```

This part is unclear: 
```
// styles applied: {margin: 1}
```

When we are applying styles with CSS classes and not with JS objects, why we should represent applied styles with objects? In reality the styles applied are like this `margin: 1px;` not `{margin: 1}`. This is what we are passing in to get that out.

**Comment by paulmolluzzo** [comment]
You're right, that could be more clear.

If you'd like to make a PR to update the README, that'd be great. It'd be great to also change it on the coming `glamorous` [website](https://rc.glamorous.rocks). You can change it for the website here: https://github.com/kentcdodds/glamorous-website/blob/master/pages/api/content/glamorous-component-factory.md

**Comment by morajabi** [comment]
I'd love to @paulmolluzzo. I will do it tomorrow.
