### ISSUE TITLE
change `innerRef` to just `ref` and add `glamRef`

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#243]
99% of the time, people want to get an actual reference to the element that glamorous is rendering. I can't think of a scenario where you'd want the glamorous component. So what if we remove `innerRef` and just forward `ref` and add `glamRef` instead? Would that even work? Or does React disallow accepting the `ref` prop (similar to the `key` prop).

**Comment by kentcdodds** [comment]
> Would that even work? Or does React disallow accepting the `ref` prop (similar to the `key` prop).

Just verified that this is the case. How disappointing :-(

**Comment by ex3ndr** [comment]
Shouldn't we reopen this and support forwardRef?

**Comment by kentcdodds** [comment]
Feel free to open a new issue about it. This issue predates the new API.
