### ISSUE TITLE
Typescript tests in src/__tests__ fail on windows

### ISSUE THREAD

**Issue by luke-john** [paypal/glamorous#248]
- `glamorous` version: next
- `glamor` version:
- `react` version:

Relevant code.

```javascript
// https://github.com/paypal/glamorous/blob/next/src/__tests__/typescript.js
const typescriptCompilation = spawnSync('./node_modules/.bin/tsc', [
    '-p',
    './tsconfig.json',
  ])
```

What you did:

Ran the tests on windows.

What happened:

Test's fail due to that command erroring and not snapshot being generated

Reproduction:

Run the tests on windows

`yarn start test`

Problem description:

spawnSync is erroring and there is no stout on it.

Suggested solution:

Either replace that command with something that works cross platform, or build a simple module that provides a js api to achieve the same thing.

**Comment by kentcdodds** [comment]
`cross-env` uses [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn). That should probably work :)
