### ISSUE TITLE
Support all of jsxstyle props

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#25]
jsxstyle has [this](https://github.com/smyte/jsxstyle#pseudoclasses) which I think is rad:

```javascript
var MyComponent = React.createClass({
  render: function() {
    return <Block color="red" hoverColor="yellow">Hello, world!</Block>;
  }
});
```

We should look into supporting that for our "Element Components" (`glamorous.Div`, `glamorous.Img`, etc).

**Comment by kentcdodds** [comment]
We really should just take a hint from what [glamor-jsxstyle](https://github.com/threepointone/glamor/blob/5e7d988211330b8e2fca5bb8da78e35051444efd/src/jsxstyle.js) does and basically do the same thing (with some exceptions and utilities afforded us via glamorous).

**Comment by kentcdodds** [comment]
It's important to note that the actual element's have already been implemented as [`glamorous-jsxstyle`](https://npmjs.com/package/glamorous-jsxstyle). We just need to support the additional props that jsxstyle supports.

**Comment by newyork-anthonyng** [comment]
If nobody else has started on this, I'd like to work on this.

**Comment by kentcdodds** [comment]
Hey @newyork-anthonyng! Thanks for reaching out! Now that the built-ins support the `css` attribute, I'm actually unsure what more we need. It's not exactly the same API, but it's equally powerful (if not more so). I'm unsure whether we need much more 🤔

**Comment by newyork-anthonyng** [comment]
@kentcdodds Yes, agreed. The think the `css` attribute is more flexible than the `jsxstyle` props. Should we close this issue?

**Comment by kentcdodds** [comment]
Yeah, let's do that 😀
