### ISSUE TITLE
Using glamorous composition with built-in components

### ISSUE THREAD

**Issue by bulby97** [paypal/glamorous#256]
Take a look at this : 
https://codesandbox.io/s/ByNJyz5n
```jsx
const { Div } = glamorous;

const MyStyledDiv = glamorous(Div)({

});

const App = () => (
  <MyStyledDiv backgroundColor="black">
    I should be black :(
  </MyStyledDiv>
  <Div color="blue">I'm blue</Div>
);
```

Shouldn't `backgroundColor` work ?

**Comment by kentcdodds** [comment]
I hadn't considered that! But maybe we should! Would be pretty easy to do I think. I would leave it to you but there's something else I want to do so I'll just implement this myself really quick. Thanks!

**Comment by kentcdodds** [comment]
Please review: https://github.com/paypal/glamorous/pull/258

**Comment by bulby97** [comment]
![image](https://user-images.githubusercontent.com/3509412/28681267-31e48a00-72f9-11e7-83ee-cc1b2cb4364b.png)

Awesome !
