### ISSUE TITLE
Evaluate static styles during initialization phase

### ISSUE THREAD

**Issue by ajwhite** [paypal/glamorous#261]
Currently all styles are processed during render phases, however, there's a subset of styles that can be evaluated during the factory phase to prevent additional computations that can be avoided during the render phases.

----

An example can be pointed to in `glamorous-native`:

1. When the factory is called, the provided styles are [immediately evaluated](https://github.com/robinpowered/glamorous-native/blob/v1.1.0/src/create-glamorous.js#L29) to [process any static styles](https://github.com/robinpowered/glamorous-native/blob/v1.1.0/src/create-glamorous.js#L14-L16).
2. During the render phase, the styles (which include the processed static styles) are [sent off for processing](https://github.com/robinpowered/glamorous-native/blob/v1.1.0/src/create-glamorous.js#L92).
3. When processing we now only care to process [style functions](https://github.com/robinpowered/glamorous-native/blob/v1.1.0/src/get-styles.js#L3-L5), and the rest are handled by react native (in your case, `glamor`)

**Comment by kentcdodds** [comment]
I love this plan. Need two caveats.

1. The user could manipulate static style objects and expect that to change styles on next render. So I wonder if we could warn the user if they try that in development mode. If that's not reasonable then we can just document it...
2. Do lazy evaluation. So we don't pay for what's not rendered. So yes it's only evaluated once, but it's only evaluated when it's first rendered if that makes sense.

Thanks for the issue. This would be great!

**Comment by ajwhite** [comment]
> So I wonder if we could warn the user if they try that in development mode. 

I like this -- `Object.freeze` in dev? 

> Do lazy evaluation.

Brilliant - so run on first render, rather than on factory initialization?

**Comment by kentcdodds** [comment]
> I like this -- `Object.freeze` in dev?

Unfortunately `Object.freeze` wont warn the user. We'd have to replace all properties with getters and setters. Probably not worth it but maybe?

> so run on first render, rather than on factory initialization?

Yes

**Comment by kentcdodds** [comment]
In any case, this could technically be a breaking change so I'd prefer to get this implemented before v4 is pushed out :smile:

**Comment by luke-john** [comment]
Just looking into this, it appears glamor already does some* of this when passed predefined objects.

https://github.com/threepointone/glamor/blob/master/docs/weakmaps.md

so this could be as simple as adding something like 

```
      warmUpGlamorCache(GlamorousComponent.styles)
      return GlamorousComponent
...
/**
 * This function takes styles and runs css on them to ensure they
 * end up in the glamor WeakMap cache
 * https://github.com/threepointone/glamor/blob/master/docs/weakmaps.md
 */
export function warmUpGlamorCache(...styles) {
  let current
  const cacheableStaticStyles = []
  for (let i = 0; i < 3; i++) {
    current = styles[i]
    if (typeof current !== 'function' &&
      typeof current !== 'string' &&
      Array.isArray(current) === false
    ) {
      cacheableStaticStyles.push(current)
    }
  }
  css(...cacheableStaticStyles)
}
```

* note only for the first three args.

**Comment by kentcdodds** [comment]
I'd thought that maybe glamor already optimized for this! Considering we wanted to do lazy evaluation, I think it's actually it's probably best as it is now. So I'm going to close this.

However, if anyone wants to make a benchmark and see what's actually faster that'd be cool 😉

**Comment by kentcdodds** [comment]
Thank you for looking into that @luke-john!

**Comment by ajwhite** [comment]
Oh that is awesome. Sunil killing it ofc.
