### ISSUE TITLE
Component-specific `css` is overridden by child selector of parent `css` with lower CSS selector precedence

### ISSUE THREAD

**Issue by kirkstrobeck** [paypal/glamorous#266]
## Reproduction:

https://codesandbox.io/s/Y6gkw8980

## Problem description:

Component-specific `css` is overridden by child selector of parent `css` with lower CSS selector precedence.

## Suggested solution:

Treat like CSS rule precedence.

**Comment by kentcdodds** [comment]
Thanks for bringing this up @kirkstrobeck. This may be a point of confusion that we could add to the docs so others don't run into it (would you like to add it to the new website?)

Your example is not quite correct on the CSS side. Here's an updated example: https://codesandbox.io/s/gJQovgLyl

You'll notice that the result is the same either way when using class names (which is what's going on in both cases). You worked around the problem using raw CSS by using IDs and style attributes. We have to do the same thing with css-in-js. There are many ways to do it (just like there are many ways to do things in regular CSS). Here's one way: [with id](https://codesandbox.io/s/rR0x9YND4) and here's another: [with inline style](https://codesandbox.io/s/vo6oMwAP8)

css-in-js is powerful, but it still has to obey the rules of specificity. We should remind folks that most of the concern of specificity goes away when using CSS-in-JS unless you start doing nested styling like your example does.

Docs PRs are appreciated on the [glamorous website](https://github.com/kentcdodds/glamorous-website)
