### ISSUE TITLE
Working with Storybook

### ISSUE THREAD

**Issue by motleydev** [paypal/glamorous#268]
I'm trying to add Storybook to a project I have but I'm getting a little stuck in how to inject theme? My components are acting like they don't find the properties that the glamorous components depend on. Giving me undefined for colors, etc.

**Comment by ajwhite** [comment]
Storybook operates completely independently from the rest of your application. Think of it as a "harness" for your components to be presented in isolation.

A solution to this is achievable by using [Storybook Decorators](https://storybook.js.org/addons/introduction/).

You can create a mock theme, set up a custom `ThemeProvider` that uses this theme, and add it as a decorator (a wrapper) to your stories:

```js
// storybook/themeProvider.js
import {ThemeProvider} from 'glamorous'

const theme = { ... }

export default ({children}) => (
  <ThemeProvider theme={theme}>
    {theme}
  </ThemeProvider>
)
```

```js
// story file

import ThemeProvider from './themeProvider.js'

...

storiesOf('Your Story', module)
  .addDecorator(getStory => <ThemeProvider>{getStory()}</ThemeProvider>)
  .add('Story Name', () => <YourStory />)
```

I hope this helps!

**Comment by motleydev** [comment]
This does! But just to clarify, did you mean this:

```javascript
export default ({children}) => (
  <ThemeProvider theme={theme}>
    {theme}
  </ThemeProvider>
)
```
or this:

```javascript
export default ({children}) => (
  <ThemeProvider theme={theme}>
    {children} // <-------
  </ThemeProvider>
)
```

**Comment by motleydev** [comment]
Pretty sure it needed `children` - either way, it works with that modification. :)

**Comment by ajwhite** [comment]
Whoops! That's indeed what I meant -- sounds like you got the gist 😃
