### ISSUE TITLE
no package-lock.json

### ISSUE THREAD

**Issue by vesparny** [paypal/glamorous#271]
Hi @kentcdodds,

just out of curiosity,
why there is no more `package-lock.json` in the repo?
I remember it used to be there but I do not see it anymore.

cheers

**Comment by kentcdodds** [comment]
Hey @vesparny!

I've found that lock files like `package-lock.json` and `yarn.lock` often cause merge conflicts. This is a barrier to contributing to my projects, so they're too much trouble than they're worth. That's why I don't include them in my projects anymore.

Thanks for the question.

**Comment by vesparny** [comment]
Thank you for the answer 👍

**Comment by luke-john** [comment]
Just fyi, yarn can now [`auto detect and merge lockfile conflicts`](https://github.com/yarnpkg/yarn/pull/3544).

Though there's still a small barrier to contribution as you need to document how to use that :)
