### ISSUE TITLE
Support function as theme as in styled-components

### ISSUE THREAD

**Issue by goodmind** [paypal/glamorous#272]
```js
const theme = {
  fg: 'palevioletred',
  bg: 'white'
}

const invertTheme = ({ fg, bg }) => ({
  fg: bg,
  bg: fg
})

render(
  <ThemeProvider theme={theme}>
    <ThemeProvider theme={invertTheme}>
      <SomeComponent />
    </ThemeProvider>
  </ThemeProvider>
)
```

Can you support this feature?

**Comment by kentcdodds** [comment]
Oh, that's interesting! Yes, we could totally support that feature. Does `theming` support this? (Assuming so because you posted in #16 :wink:)

If we want to support this I think it'd require a test or two and a few changes [here](https://github.com/paypal/glamorous/blob/master/src/with-theme.js). Would you like to [make a pull request](http://makeapullrequest.com/)?

**Comment by goodmind** [comment]
@kentcdodds shouldn't this be done in `ThemeProvider`?

**Comment by kentcdodds** [comment]
Yes! Sorry, you're correct. Theming is one area that I'm less familiar with. @vesparny implemented most of it :smile: https://github.com/paypal/glamorous/blob/master/src/theme-provider.js

**Comment by vesparny** [comment]
I think the best would be to try making the switch to theming.

**Comment by kentcdodds** [comment]
I agree. I'll file an issue with theming.

**Comment by kentcdodds** [comment]
Would be helpful if you could both chime in your support/feedback: https://github.com/iamstarkov/theming/issues/30

**Comment by goodmind** [comment]
@kentcdodds can't you use your your own `withTheme` but support `ThemeProvider` from `theming`, until it supports  iamstarkov/theming#30 and then just replace your `withTheme` with it?

**Comment by kentcdodds** [comment]
That's a good point! Would you like to make a pull request to do that?

**Comment by goodmind** [comment]
#273 but I don't know how to intergrate `theming` with all this context thing, `CHANNEL` etc. Can you reopen issue about theming support?

**Comment by kentcdodds** [comment]
Reopen which issue?

**Comment by goodmind** [comment]
@kentcdodds this one? https://github.com/paypal/glamorous/issues/175

**Comment by kentcdodds** [comment]
Done :+1:
