### ISSUE TITLE
glamor CSS selectors

### ISSUE THREAD

**Issue by goodmind** [paypal/glamorous#274]
When I use `glamor.css` and className function render getting wrong `class` on component

```js
const active = css({ label: 'active' }); // css-somehash
const Item = glamorous.div(
  props => props.active ? active : {}, 
  {
    height: '50px', width: '50px',
    [`&.${active}, &.${active}:hover`]: { // not works
      backgroundColor: '#000',
    },
  }
);

const SomeNestedComp = glamorous.div({
  [`${active} &`]: { ... }
})

render(
  <div>
     <Item><SomeNestedComp /></Item>
     <Item active={true}><SomeNestedComp></Item>
  </div>
)
```

renders into:
```html
<div>
  <div class="css-styleddialogitem-k6qqiv">...</div>
  <div class="css-styleddialogitem-active-393srd">...</div>
</div>
```

But this works with static string as class

**Comment by kentcdodds** [comment]
Hi @goodmind! :wave:

So you've come across a situation that not many see. The thing is that it's difficult to be deterministic if we apply more than one class name to an element (how do conflicts get resolved?) so glamorous will merge the styles of all glamor-generated class names. So, when you do:

```javascript
const Item = glamorous.div(
  props => props.active ? active : {}, 
  {
    height: '50px', width: '50px',
    [`&.${active}, &.${active}:hover`]: { // not works
      backgroundColor: '#000',
    },
  }
);
```

That would resolve (theoretically) to something like this:

```javascript
const Item = glamorous.div(
  'css-54321', 
  'css-12345',
);
```

And glamorous will make it so glamor merges those together into a single class name so conflicts are resolved in the order you expect (last winning).

So, to get around your issue, you could do this:

```javascript
const activeClassName = 'is-active'
const active = css({ label: 'active' }); // css-somehash
const Item = glamorous.div(
  props => props.active ? [active, activeClassName] : {}, // you could also just inline the active CSS here...
  {
    height: '50px', width: '50px',
    [`&.${activeClassName}, &.${activeClassName}:hover`]: { // not works
      backgroundColor: '#000',
    },
  }
);

const SomeNestedComp = glamorous.div({
  [`${activeClassName} &`]: { ... }
})

render(
  <div>
     <Item><SomeNestedComp /></Item>
     <Item active={true}><SomeNestedComp></Item>
  </div>
)
```

I realize that can be a little annoying, but normally this kind of nesting isn't entirely necessary.

**Comment by kentcdodds** [comment]
If you'd like, I think having an example on [the examples page](https://glamorous.rocks/examples) would be really helpful here I think :smile:

But there's not much we're going to do in this case. Sorry about that. Good luck!
