### ISSUE TITLE
Typescript: Property 'theme' is missing in type {}

### ISSUE THREAD

**Issue by beshanoe** [paypal/glamorous#278]
- `glamorous` version: 4.1.0
- `react` version: 15.6.1

Relevant code.

```typescript
const GlamorousDiv = glamorous.div({
  display: 'flex',
  flexDirection: 'row',
})

export const MyComponent = () =>
  <div>
    <GlamorousDiv />
  </div>
```

What you did:

Tried to use glamorous without any theme and props

What happened:

I can't then use this component in render function since it requires 'theme' prop to be defined explicitly
![image](https://user-images.githubusercontent.com/1383547/29032417-01254f22-7b9a-11e7-853d-c3214675b6e8.png)

Suggested solution:

Use explicit empty object type(I don't like it)
![image](https://user-images.githubusercontent.com/1383547/29032496-3c459c9c-7b9a-11e7-8439-36a4469623e9.png)

Make it same way as styled-components did(add ability to override glamorous instance in order to bind theme object for every created styled component):
https://www.styled-components.com/docs/api#typescript

**Comment by luke-john** [comment]
Hey @beshanoe, sorry to hear the typings don't appear to be working for you.

Looking at your first example hat should already work. (working demo https://stackblitz.com/edit/react-ts-et6y7m?file=index.tsx)

To help me look into it could you please provide what version of typescript you are using?

**Comment by beshanoe** [comment]
Thanks for reply @luke-john ! 
Could you please explain what exactly of 2.4`s features are making these typings incompatible with 2.3?
I'm gonna switch to newest version anyway, just interesting to know though :)
And is there a way to bind theme type to all glamorous-defined components so that when I write this:
```typescript
const MyLink = glamorous.a(
	{
		color: 'blue',
		textDecoration: 'none',
	},
	(props) => ({
		fontSize: props.size === 'big' ? 24 : 16,
	})
)
```

props will include 'theme' typings and optionally my own types as I defined it in generic `glamorous.a<{foo: string}>`

This is the only thing which keeps me from using glamorous actively. Because I have to pass theme type in every glamorous component I'm creating

**Comment by luke-john** [comment]
We (possibly prematurely given the two issues raised about this) jumped on the opportunity to use the following `Omit` helper to give something similar to subtraction types.

https://github.com/paypal/glamorous/blob/master/typings/helpers.d.ts

This is being used to allow withTheme and also props of glamorous component factories to take theme as a key, but not be required on the components they return.

ie.
```
// '... theme.ts'
export interface GlobalTheme {
    theme: { primaryColor: string }
}

// ComponentName.glamorous.ts
import { GlobalTheme } from '... theme.ts'

export const StyledComponent = glamorous.div<GlobalTheme>(
    ({theme}) => ({
        primaryColor: theme.primaryColor
    })
)

// ComponentName.tsx
import { StyledComponent } from './ComponentName.glamorous.ts
...
    <StyledComponent />
```

Currently the only `way to bind theme type to all glamorous-defined components` would be to import a bunch of the mid level typings from glamorous and rebuild them with themw already provided and then assert imports from glamorous and re export, not exactly user friendly...  Would you mind opening a seperate issue describing how `styled-components` works and how you'd expect this to work in glamorous?

It sounds like a handy thing that may be useful for other people using a single theme interface, so I'd be happy to spike out a couple of options for how this could work.

**Comment by luke-john** [comment]
I've created the following issue to track documenting the typescript versions the v4 typings work with.

#287
