### ISSUE TITLE
Error in 4.1 with typescript

### ISSUE THREAD

**Issue by SilasRoswall** [paypal/glamorous#279]
I'm sitting on a project where we are using typescript and I wanted to test glamorous. Writing the minimal code an error was thrown in the JSX. I tried downgrading to 3.1 and it worked.

The following code works in 3.1, but in 4.1 in throws the following error: Property 'theme' is missing in type '{}'.

Minimal code:
```javascript
import * as React from 'react';
import glamorous from 'glamorous';

const DrinksTodayRow = () => {
	return (
		<TestDiv/> //This line throws the error
	);
};

const TestDiv = glamorous.div({
	width: '100%',
});
```

![screen shot 2017-08-08 at 09 33 05](https://user-images.githubusercontent.com/10417842/29061076-9d3dab98-7c1c-11e7-9891-820db5b437f3.png)

I am using  react version 15.6.1.

I'm fairly novice when it comes to coding, so I don't have any suggestions on how to fix it.

**Comment by luke-john** [comment]
Hey @SilasRoswall, thanks for the reproduction and bug report.

This looks related to https://github.com/paypal/glamorous/issues/278.  Could you please confirm what version of typescript you are using?

**Comment by SilasRoswall** [comment]
Hi @luke-john the version ts version is 2.3.4.

**Comment by luke-john** [comment]
Hey @SilasRoswall sorry for the delayed response, at this time the glamorous typings for v4 only work with 2.4+. I've created the following issue to track documenting this and also investigate adding support for lower versions.

https://github.com/paypal/glamorous/issues/287
