### ISSUE TITLE
TypeScript: component factory return type

### ISSUE THREAD

**Issue by kylelamse** [paypal/glamorous#282]
- `glamorous` version: ^4.1.0
- `glamor` version: ^2.20.39
- `react` version: ^15.61

```typescript
import glamorous from 'glamorous';
const { button } = glamorous;

const ButtonContainer: any = button({
  color: 'blue'
});
```

I am using glamorous with typescript and have been having to use `any` for the return type of a glamorous component factory.  Is there an appropriate return type I should use for the above snippet?

**Comment by kentcdodds** [comment]
Importing the functions is not supported. Strictly speaking they're not exported at all. Please use the default export and call the functions on that 👍

**Comment by kentcdodds** [comment]
Also, thanks for using glamorous ❤️

**Comment by kylelamse** [comment]
Ok thanks.  So I changed my code from the above snippet to:
```typescript
import glamorous from 'glamorous';
const ButtonContainer: any = glamorous.button({
  color: 'blue'
});
```

Do you know what the return type I should be using is instead of `any` for Typescript?

**Comment by kylelamse** [comment]
And no problem.  It solves my annoyances with css and React!  Definitely have gotten into open source more lately and see myself contributing whenever possible.  Love this project!

**Comment by kentcdodds** [comment]
I don't use TypeScript, but my guess is that you don't need to cast it to any type at all. TS should just pick up the built-in typings... 🤔

**Comment by luke-john** [comment]
It should do yes.  Great to hear you're giving glamorous and typescript a go 💖.

**Comment by kylelamse** [comment]
@kentcdodds @luke-john this is what solved my specific issue:

```typescript
import glamorous from 'glamorous';
import { CSSProperties, GlamorousComponent, ExtraGlamorousProps } from 'glamorous';

```

**Comment by kylelamse** [comment]
For anyone wondering, the reason I was stuck on this is because I like to have every variable I created to not have any implicit `any` or even explicit `any` type when writing TypeScript.

**Comment by kylelamse** [comment]
@luke-john Are you one of the contributors that made the typings?  Because I have a question.  Here is the type in question:
```typescript
export type GlamorousComponent<ExternalProps, Props> =
  & React.ComponentClass<ExtraGlamorousProps & ExternalProps>
  & WithComponent<ExternalProps, Props>
  & WithProps<ExternalProps, Props>
```

What are `ExternalProps` and `Props`?  It's not very clear.

**Comment by luke-john** [comment]
@kylelamse ahh looks like that's definitely a bug if you are getting `any` when using the typings.

The ExternalProps are props on the glamorous component (ie. dom tag properties) that are unrelated to the style arguments.

Props are internal Props available to style arguments.

Some comments in the typings would likely be useful, apologies for any difficulty you had reading them.

**Comment by luke-john** [comment]
@kylelamse I just tried this locally and can't seem to replicate the any locally with the following versions of typescript (note the typings only work properly on 2.4+).

* 2.4.2
* 2.4.0
* 2.3.1
* 2.3.0

We've also got noImplicitAny turned on in the tsconfig https://github.com/paypal/glamorous/blob/master/tsconfig.json that we run the test file https://github.com/paypal/glamorous/blob/master/test/glamorous.test.tsx with and haven't seen any issues.

I have however been able to replicate on stackblitz https://stackblitz.com/edit/react-ts-u9qiu6?file=components%2FApp%2FButton.glamorous.tsx which is using 2.4.1 https://github.com/stackblitz/core/issues/42#issuecomment-320568265.

So there's definitely an issue, I'm just unable to find it :/.  If you're able to help look into this that would be great.

**Comment by kylelamse** [comment]
@luke-john I'm not sure if I'm communicating the specific issue/misunderstanding I had properly.  By convention, I like to have the most specific type annotations on all the variables I declare.  Example:
```typescript
const str: string = 'foo'; // good
// vs
const str: any = 'foo'; // bad
```

Both are perfectly acceptable, and will run just fine, but I prefer the `str` that is declared with type `string` instead of slapping an `any` on the variable or leaving it off because `string` is more type-specific.  Now the specific scenario I ran into:
```typescript
const StyledButton: any = glamorous.button({}); // bad
// vs
const StyledButton: GlamorousComponent<Props, {}> = glamorous.button({}); // good
```
I just wanted the most specific typing instead of having to use `any`.  It worked just fine without it, but it is a style choice of mine to have specific types on my variable declarations.
`glamorous.button()` didn't return type `any`, it actually returned `GlamorousComponent<React.HTMLProps<HTMLButtonElement> & Props, Props>`.  I was confused on what I put between the `<>` when declaring the variable.   I actually think I'm still doing it wrong, and I would be very thankful if you could check my screenshot and help me.  Here is a screenshot for more context:
![glamorous typing](https://user-images.githubusercontent.com/9343089/29297759-c52e3846-8128-11e7-946b-54c7e152d59d.png)

Hopefully that clears things up.  I'm sorry I wasn't very clear in my previous comments.

**Comment by kylelamse** [comment]
It is a bit verbose, but think I found the correct way:
```typescript
const StyledButton: GlamorousComponent<React.HTMLProps<HTMLButtonElement>
& Props, Props> = glamorous.button({});
```

**Comment by luke-john** [comment]
Ahh right, I guess the issue with stackblitz is unrelated. I'll open up an issue with them for this.

You're first example is the correct one. You need the Props on the first generic parameter as otherwise the resulting react component will not know about them.

```ts
const StyledButton: GlamorousComponent<React.HTMLProps<HTMLButtonElement>
& Props, Props> = glamorous.button<Props>(
  {
    /* ... */
  },
  ({ disabled }) => ({
    /* ... */
  })
);

...
<StyledButton disabled />
```

Adding type annotations against all the glamorous component factory creations seems like a great way to add test coverage. I'll likely spend some time this evening adding type annotations for all the various ways glamorous components can be created. I'll ping you once that's done.

**Comment by kylelamse** [comment]
Awesome, thanks!
