### ISSUE TITLE
Typescript: Only works with typescript version 2.4+

### ISSUE THREAD

**Issue by luke-john** [paypal/glamorous#287]
- `glamorous` version: 4+
- `glamor` version: N/A
- `react` version: N/A

What you did:

Tried using Glamorous v4 with typescript <2.4

What happened:

* https://github.com/paypal/glamorous/issues/279
* https://github.com/paypal/glamorous/issues/278

Reproduction:

Use glamorous with typescript <2.4.

Problem description:

The typings use language features that only landed in 2.4 and result in unexpected behaviour on <2.4

Suggested solution:

Document that the typings only currently work with 2.4+ 

* tracking issue https://github.com/kentcdodds/glamorous-website/issues/266

Investigate reworking the typings to work on 2.3.

**Comment by luke-john** [comment]
Opened up a PR to add this to documentation at https://github.com/kentcdodds/glamorous-website/pull/276

**Comment by kentcdodds** [comment]
Thanks!
