### ISSUE TITLE
Typescript support for prop-styles function

### ISSUE THREAD

**Issue by thomhos** [paypal/glamorous#289]
- `glamorous` version: 3.25.0
- `glamor` version: 2.20.38
- `react` version: 15.6.1

Relevant code.

```typescript
const heading: CSSProperties = {
    display: 'block',
    fontFamily: 'inherit',
    fontWeight: '500',
    lineHeight: '1.1',
}
const largerHeading: CSSProperties = {
    marginTop: '20px',
    marginBottom: '10px',
}

const smallerHeading: CSSProperties = {
    marginTop: '10px',
    marginBottom: '10px',
}

const Text = glamorous.span([[heading], largerHeading, [{ fontSize: '30px'}]])
```

What you did:
I'm trying to use the prop-styles function in a typescript environment. I wrote some annotations for the function, but later found out the typings think the factory cannot receive arrays.

What happened:
I'm getting a type error which indicates I'm not allowed to provide an array of CSSProperties to the factory function. This does work on the codepen to illustrate prop-styles, but not with the current definitions.

codepen: https://codesandbox.io/s/AGRRMl63?from-embed

Reproduction:
Copy paste the above code in a typescript environment, then observe the type error;
```
Argument of type '(CSSProperties | CSSProperties[])[]' is not assignable to parameter of type 'Partial<CSSProperties>'.
  Types of property 'fill' are incompatible.
    Type '(value: CSSProperties | CSSProperties[], start?: number, end?: number) => (CSSProperties | CSSPro...' is not assignable to type 'string'.
```

Problem description:
It seems the typings for glamorous aren't correctly applied for the factory function. I'm not really a typescript expert so I find it hard to exactly pinpoint the issue. With some help I'll gladly submit a PR to get this fixed.

**Comment by thomhos** [comment]
Seems this is fixed in v4+, so should read the release notes more closely 🤕 

Cheers!

**Comment by luke-john** [comment]
@thomhos great to hear you're using glamorous and typescript together.

It's still got some quirks*, but you may find stackblitz handy as a online playground for typescript and glamorous.

https://stackblitz.com/edit/react-ts-u9qiu6

* some of the typings seem to result in `any`s.

**Comment by thomhos** [comment]
Well the quirks are very minor if you compare the type safety with any other css solution for react. It's the go-to solution for our agency, I'm actively getting our team on board with this :D

**Comment by kentcdodds** [comment]
I'm so glad! :clap: to @luke-john for making the typings so good!
