### ISSUE TITLE
Is there any proper way to find the type of glamorous component?

### ISSUE THREAD

**Issue by Ailrun** [paypal/glamorous#292]
- `glamorous` version: 4.2.0
- `glamor` version: 2.20.40
- `react` version: 15.6.1
- `typescript` version: 2.4.2

Relevant code.

```ts
// file1.tsx
import glamorous, { CSSProperties, GlamorousComponent } from 'glamorous';
import { HTMLProps } from 'react';

const ExComp: GlamorousComponent<HTMLProps<HTMLButtonElement>, {}> = glamorous.button({});
export default ExComp;
```

```ts
// file2.tsx
import ExComp from './file1';

// What is the type of props of ExComp?
const props = {
};

render(<ExComp { ...props } />);
```

Problem description:

There's no way to find or use the type of glamorous component.
I mean,

- For ES6 class that extends `React.Component` like `class X extends React.Component<Props>`,
I can easily find the type of props since *I give it to React.Component generic* or by `X['props']` gives me the type of props of `X`.
- For `StatelessComponent`, like `const y: StatelessComponent<Props>`, I also can easily find the type of props, of course, I give the type to that generic.

but for

```ts
const ExComp: GlamorousComponent<HTMLProps<HTMLButtonElement>, {}> = glamorous.button({});
```

there's no way to find the type of props of `ExComp`, since

- It's not a class, so I can't use `ExComp['props']`.
- It doesn't have the props of the type I give to `ExComp`, I don't know the type.

Of course, I can find the type, but, `React.ComponentClass<Props>` take props of 

```ts
JSX.IntrinsicAttributes & JSX.IntrinsicClassAttributes<React.Component<Props, React.ComponentState>> & Props & { children?: React.ReactNode }
```

so the type I should use for props is 

```ts
JSX.IntrinsicAttributes & JSX.IntrinsicClassAttributes<React.Component<ExtraGlamorousProps & React.HTMLProps<HTMLButtonElement>, React.ComponentState>> & ExtraGlamorousProps & React.HTMLProps<HTMLButtonElement> & { children?: React.ReactNode }`
```

and you know, it's too verbose.

Suggested solution:

How about including new type like `GlamorousComponentProps<ExternalProps, Props>` (or just `<ExternalProps>` since it never use `Props`.) and defining it as following?

```ts
type GlamorousComponentProps<ExternalProps, Props> =
  & JSX.IntrinsicAttributes
  & JSX.IntrinsicClassAttributes<
    React.Component<
      & ExtraGlamorousProps
      & ExternalProps,
      React.ComponentState
    >
  >
& ExternalProps
& { children?: React.ReactNode }
```

**Comment by luke-john** [comment]
Hey @Ailrun, thanks for the issue.

> There's no way to find or use the type of glamorous component.

By default all valid usage of glamorous should be typed automatically, so for the example you gave the type would actually be as follows.

```ts
const GlamorousButtonComponent = glamorous.button({});
/**
 * GlamorousButtonComponent has a type of
 * React.ComponentClass<ExtraGlamorousProps & React.HTMLProps<HTMLButtonElement>>
    & WithComponent<React.HTMLProps<HTMLButtonElement>, object>
    & WithProps<React.HTMLProps<HTMLButtonElement>, object>
 */
```

> For StatelessComponent, like const y: StatelessComponent<Props>, I also can easily find the type of props, of course, I give the type to that generic.

Similar to when creating React Components, Glamorous component factories take style props as a generic.

```ts
interface Props { isVisible: boolean }
const GlamorousButtonComponent = glamorous.button<Props>(
    (props) => ({ display: props.isVisible ? 'block' : 'none' })
)
/**
 * GlamorousButtonComponent has a type of
 * GlamorousComponent<React.HTMLProps<HTMLButtonElement> & Props, Props>
 * which evaluates to
 * React.ComponentClass<ExtraGlamorousProps & React.HTMLProps<HTMLButtonElement> & Props>
    & WithComponent<React.HTMLProps<HTMLButtonElement> & Props, Props>
    & WithProps<React.HTMLProps<HTMLButtonElement> & Props, Props>
 */
```

I think refactoring the intersection to pass Props first would likely add value so that consumers would get Props first in intellisense, compiler errors or whatever tool they are using.

**Comment by Ailrun** [comment]
@luke-john 
Sorry for typo. What I mean is

> There's no way to find or use the type of props of glamorous component.

And also in your example, `GlamorousButtonComponent` takes not just `Props`, but also some `React.HTMLProps<HTMLButtonElement>`, and if I pass `const props: React.HTMLProps<HTMLButtonElement> & Props` to `<GlamorousButtonComponent />`, it cause type error.

**Comment by luke-john** [comment]
Ahh I think get the issue now.  So currently you can only type the styleProps before passing

But you're going to get type mismatches if you try and pass anything typed as React.HTMLProps<HTMLButtonElement> to the glamorous button.

It definitely seems like a handy thing to be able to do so if you think something like you suggested above would work a PR would be great.

**Comment by luke-john** [comment]
hey @Ailrun, so after thinking a bit more about this issue this morning I think the following should work for you.

```ts
import * as React from 'react'
import glamorous from 'glamorous'

// note: Omit this is not part of the glamorous public typings
// I'd recommend you set it up in your own project rather than relying on this path
import { Omit } from 'glamorous/typings/helpers'

interface Props { isVisible: boolean }

const GlamorousButtonComponent = glamorous.button<Props>(
    (props) => ({ display: props.isVisible ? 'block' : 'none' })
)

const props: Props & Omit<React.HTMLProps<HTMLButtonElement>, 'ref'> = {
  isVisible: true,
  autoFocus: false,
};

<GlamorousButtonComponent { ...props } />
```

The problem is the `ref` on `HTMLProps` which glamorous doesn't expose anyway, so I _think_ documenting how to do this would be a good solution.

**Comment by Ailrun** [comment]
@luke-john
Does glamorous doesn't expose any `ref` props? Really?
Type inference of TS says `GlamorousButtonComponent` expose `ref` of type of
```
(node: React.Component<ExtraGlamorousProps & ExternalProps, React.ComponentState>) =>
    void
```

If you are sure about

> ref, which glamorous doesn't expose anyway,

Then there's some other type problem related with `GlamorousComponent`.

**Comment by luke-john** [comment]
Sorry what I meant by that is that glamorous doesn't use the ref from `React.HTMLProps<HTMLButtonElement>`.

To get access to the ref of the underlying component in glamorous you use `innerRef`. https://glamorous.rocks/advanced#innerref

Which is currently typed as `innerRef?: (instance: any) => void;`.

**Comment by Ailrun** [comment]
@luke-john 
Anyway props do have `ref` and can handle it, don't that?
Hm...
If I send a PR related with this, could you reconsider about this type?

**Comment by luke-john** [comment]
PRs to improve the typings are always appreciated :) .

> Anyway props do have ref and can handle it, don't that?

The `Props` interface which is being passed are the style argument `Props` which don't have a ref.

But I'm pretty sure you're talking about the Props on the GlamorousComponent returned by glamorous component factories which does have a `ref` and `innerRef`.  Any improvements to the type of these would be awesome 👍 .

**Comment by Ailrun** [comment]
@luke-john 
I added a PR https://github.com/paypal/glamorous/pull/298

**Comment by luke-john** [comment]
Thanks for all your work on this @Ailrun. that should now be published.
