### ISSUE TITLE
Type definition for typescript doesn't include built-in components.

### ISSUE THREAD

**Issue by Kais-DkM** [paypal/glamorous#294]
- `glamorous` version: 4.2.0
- `glamor` version: 2.20.40
- `react` version: 15.6.1

Relevant code.

```typescript
import { Div, Span } from 'glamorous';
```

Problem description:

Currently for typescript, there's no type definition for built-in components other than `Div` and `Svg`.
Of course I can use them as `glamorous.span({...})`, but it would be better if I can use built-in components too.

Suggested solution:

I think adding interface `HTMLComponents` having all those built-in components, and making `GlamorousInterface` extend it would be enough.
Like this:
```
interface HTMLComponents {
  Div: React.StatelessComponent<CSSProperties & ExtraGlamorousProps>,
  ...
}

export interface GlamorousInterface extends HTMLComponents, HTMLComponentFactory, SVGComponentFactory {
  ...
}
```

**Comment by luke-john** [comment]
Hey @Kais-DkM, thanks for reporting that.

That would be a great addition to the types.

Given the size of those interfaces, it would be good if they were in an adjacent file.
ie.

```ts
// built-in-glamorous-components.d.ts
export interface BuiltInComponents {
    Div: React.StatelessComponent<CSSProperties & ExtraGlamorousProps>
    // ...
}
export interface BuiltInComponents {
    Svg: React.StatelessComponent<CSSProperties & ExtraGlamorousProps>
    // ...
}
```

There's also an issue with the typings for these in that they are typed to take the relevant HTMLProps.

```ts
export interface HTMLComponent {
    A: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & React.HTMLProps<HTMLAnchorElement>>
    Div: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & React.HTMLProps<HTMLDivElement>>
    Svg: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & React.SVGAttributes<SVGElement>>
}
export interface SVGComponent {
    Svg: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & React.SVGAttributes<SVGElement>>
}
```

If you're able to open a PR along the lines of either of the above, or another strategy/structure you think would work well, that would be greatly appreciated.

**Comment by Kais-DkM** [comment]
@luke-john 
It would be a pleasure to help you out, and I think second code you suggested is a great solution.
I'm willing to open a PR, but I have a question before that.

Why wasn't this implemented until now?
Is it just because nobody tried to work on it? or were there any issues related to this typing?

**Comment by Ailrun** [comment]
If needed, I will send a PR about  this issue with [my issue](https://github.com/paypal/glamorous/issues/292), since both issues related with typing problem.

**Comment by luke-john** [comment]
> Is it just because nobody tried to work on it? or were there any issues related to this typing?

@Kais-DkM it was because no one had tried to work on it.

Looks like there's already a PR open, but thank you for your offer to work on this 👍.

If you're still interested in helping out with the typings I'll be opening some issues later this week with good first prs to help improve the developer experience.  https://github.com/paypal/glamorous/issues/295

**Comment by Kais-DkM** [comment]
@luke-john 
I'll take a look at it on spare time, and thanks for your offer!
