### ISSUE TITLE
CSS injection vulnerabilities

### ISSUE THREAD

**Issue by jamesknelson** [paypal/glamorous#300]
- `glamorous` version: all (as far as I can tell)
- `glamor` version: all (as far as I can tell)
- `react` version: all (as far as I can tell)

Glamorous is currently vulnerable to CSS injection vulnerabilities.

As an example, you can change the background color of the page via props on `Div` elements:

```jsx
const textColor = `white;}
  body {
    background-color: purple;
  }
  .x{color: red`

<Div color={textColor}>
  Hello!
</Div>
```

Reproduction:

https://codesandbox.io/s/4x56prkp64

Problem description:

If a malicious user is able to feed props into Glamorous components on a page that a target user is viewing, they can inject any styles they'd like into the target's page.

This can result in defacing your app/website, [capturing keystrokes in fields](https://www.curesec.com/blog/article/blog/Reading-Data-via-CSS-Injection-180.html), [finding the characters used in a certain HTML element](http://mksben.l0.cm/2015/10/css-based-attack-abusing-unicode-range.html), or in the case of IE9, possibly even [arbitrary JavaScript execution](http://www.diaryofaninja.com/blog/2013/10/30/executing-javascript-inside-css-another-reason-to-whitelist-and-encode-user-input).

Suggested solution:

I feel like `{`, `}` and `"` (at minimum) should probably be escaped. However, I'm not yet experienced enough with glamorous to understand whether that would cause other problems?

**Comment by kentcdodds** [comment]
Hi @jamesknelson! Thanks for bringing this up. It's really a concern of glamor (the library responsible for inserting CSS into the browser). And I expect that if you were to ask @threepointone about it, he'd say that you should be escaping user input yourself. It's pretty rare that user input is used in styles, so I don't expect it to be a major issue. If you are concerned about it, then you could write [a glamor plugin](https://github.com/threepointone/glamor/blob/master/docs/plugins.md) to do the escaping for you with just a few lines of code.

I'm 99% certain we wont be making any changes to glamorous, and I'm fairly certain that glamor wont be making changes to account for this, but @threepointone can weigh in if he's interested.

Thanks again! If you do create a plugin to do this, then I think you could add an example to the [glamorous examples](https://glamorous.rocks/examples) (like [this one](https://github.com/kentcdodds/glamorous-website/pull/274)).

Thanks! And good luck!
