### ISSUE TITLE
Typescript: Add comments to typings

### ISSUE THREAD

**Issue by luke-john** [paypal/glamorous#302]
Problem description:

The current typings for glamorous don't have much in the way of comments, it would be good to add comments to the typings to improve the user experience. 

As an example [WithComponent in glamorous-component.ts](https://github.com/paypal/glamorous/blob/f20918715b62ce2c71f99ffcae065d932676a959/typings/glamorous-component.d.ts#L21) could be improved as follows.

```ts
export interface WithComponent<ExternalProps, Props> {
  /**
   * Copy the styles of an already created glamorous component with a different tag.
   */
  withComponent: (
    component: string | Component<Props>
  ) => GlamorousComponent<
```

Which would add the handy description to users

<img width="706" alt="screen shot 2017-08-23 at 6 58 07 pm" src="https://user-images.githubusercontent.com/848525/29612689-14f168c2-8835-11e7-8692-5599c615276c.png">

**Comment by Powell-v2** [comment]
Hi there! I'd like to help out with this task (if still relevant), however I'm not entirely sure how to come up with proper comments ... Could you provide a little bit of guidance, please?

**Comment by Powell-v2** [comment]
Thanks @luke-john , I'm on it then : )

**Comment by Powell-v2** [comment]
Hi @luke-john, yesterday I was trying to set up the project locally for the first time but encountered an error while running "validate" script. Asked on gitter channel, but nobody got back to me. Maybe you could advise?
I was only following instructions in the guide for contributors (so stuck on step 3). Here is the error message I've got:

```
> glamorous@0.0.0-semantically-released validate /Users/powell_v2/Downloads/glamorous
> kcd-scripts validate lint,build-and-test,test:cover

/Users/powell_v2/Downloads/glamorous/node_modules/kcd-scripts/dist/utils.js:135
  scripts = Object.entries(scripts).reduce(function (all, _ref3) {
                   ^

TypeError: Object.entries is not a function
    at getConcurrentlyArgs (/Users/powell_v2/Downloads/glamorous/node_modules/kcd-scripts/dist/utils.js:135:20)
    at Object.<anonymous> (/Users/powell_v2/Downloads/glamorous/node_modules/kcd-scripts/dist/scripts/validate.js:32:53)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by luke-john** [comment]
Hey @Powell-v2, sorry about that.

I suspect this is due to kcd-scripts relying on javascript features which are not present in the version of node you're using.

Are you able to try with node v8?

**Comment by Powell-v2** [comment]
That helped, thanks! However validate script complained about unresolved path:

```
[lint] 
[lint] /Users/powell_v2/Downloads/glamorous/other/codemods/theme-move.test.js
[lint]   3:22  error  Unable to resolve path to module 'prettier'  import/no-unresolved
[lint] 
[lint] ✖ 1 problem (1 error, 0 warnings)
[lint] 
[lint] npm run lint --silent exited with code 1
```

Should I ignore it or it has to be fixed before I create PR?

**Comment by luke-john** [comment]
Hmm, I think prettier is used at another step in the kcd scripts so some
other things may not be working if that dependency is missing.

As it's unrelated though I'd ignore for now, we can always update the pr
later.  My Mac just gave up so I won't be able to have a look at the
linting issue tonight, will investigate tomorrow if no one else has ☺️.

Thank you for reporting the issue.

**Comment by kentcdodds** [comment]
My guess is that you're running an old version of npm that's not installing dependencies in a way that kcd-scripts expects them to be installed. Make sure you're on the latest stable node (`>=8`) and npm (`>= 5`). Sorry about that!

**Comment by Powell-v2** [comment]
Thanks @kentcdodds, I had node v6.x - updating to the latest stable version fixed the issue 👍

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
