### ISSUE TITLE
[TypeScript] Single elements in `glamorous.Div` children type check fails 

### ISSUE THREAD

**Issue by renatorib** [paypal/glamorous#313]
- `glamorous` version: ^4.3.1
- `glamor` version: ^2.20.25
- `react` version: ˆ15.6.1
- `typescript` version: 2.4.2

**What I did:**
Tried to put a single element inside a `glamorous.Div`

**What happened:**
Children type check fails

**Brief description/code:**
It works normally:
![image](https://user-images.githubusercontent.com/3277185/29788205-2841765c-8c08-11e7-8157-84f36d4f74ab.png)

It doesn't:
![image](https://user-images.githubusercontent.com/3277185/29788223-356dca2e-8c08-11e7-905e-45f66182487a.png)

Putting a single dot turns to pass again:
![image](https://user-images.githubusercontent.com/3277185/29788241-415448a4-8c08-11e7-894b-3d4d7d5baf69.png)

Or with another elements together:
![image](https://user-images.githubusercontent.com/3277185/29788258-4cf9fa46-8c08-11e7-9091-65f401eafa90.png)

Apparently it fails with any element alone:
![image](https://user-images.githubusercontent.com/3277185/29788294-6f7f0732-8c08-11e7-9b57-0c31809b1b85.png)

**Error:**
![image](https://user-images.githubusercontent.com/3277185/29788134-e9f010e8-8c07-11e7-9ba7-ab1abf3af32f.png)

Full message:
```
Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & SingleOrArray<CSSPropertiesCompleteSingle, "alignContent" | "alignItems" | ...'.
  Type '{ children: Element; }' is not assignable to type 'CSSPropertiesLossy'.
    Property 'children' is incompatible with index signature.
      Type 'Element' is not assignable to type 'string | number | SingleOrArray<CSSPropertiesCompleteSingle, "alignContent" | "alignItems" | "ali...'.
        Type 'Element' is not assignable to type '(string | number | {} | ("initial" | "inherit" | "unset" | "flex-start" | "flex-end" | "center" |...'.
          Property 'length' is missing in type 'Element'.
```

**Additional**
I tried to override children types creating this wrapper:
```tsx
type Props = {
  children?: ReactNode,
}

const Div = glamorous('div', { propsAreCssOverrides: true })<Props>({})
```

But didn't work too. The same error occurs

**Comment by renatorib** [comment]
I've found the problem. Its related to storybook/react with version 3.1.9, which depends on glamorous@3.x.x and it's conflicting, even having as dependency glamorous@4
I just upgraded storybook/react to latest 3.2.8, which uses glamorous@4, and now its working correctly.

**Comment by luke-john** [comment]
@renatorib that was actually only fixed a couple of days ago by @Kais-DkM 😄.

Glad to hear it's working for you 👍.

https://github.com/paypal/glamorous/pull/311

**Comment by renatorib** [comment]
@luke-john great to see glamorous growing bugfixes-wise :)
