### ISSUE TITLE
Allow to filter props passed to child component

### ISSUE THREAD

**Issue by bjoernricks** [paypal/glamorous#314]
- `glamorous` version: 4.5.0
- `glamor` version: 2.10.40
- `react` version: 15.6.1

### Relevant code:

```javascript
const withLayout = Component => {
  return glamorous(Component)(
    'layout',
    ({
      align,
      basis,
      flex = 'row',
      grow,
      shrink,
      wrap,
    }) => {
      if (flex === true) {
        flex = 'row';
      }
     return {
        display: 'flex',
        flexDirection: flex,
        flexGrow: grow,
        flexBasis: basis,
        flexWrap: wrap,
        flexShrink: shrink,
        justifyContent: align[0],
        alignItems: align[1],
      };
    },
  );
};

const Layout = withLayout('div');
```
### Problem description:

The code above is a simplified version of my Layout component. As you might have seen I have created a HOC to be able to add layout style to different HTML elements and Components. As a result I can't use rootEl to filter props and the annoying unknown props warning appears e.g. "Unknown prop `grow` on xyz tag. Remove this prop from the element".  

This problem always appears if glamorous is used within a HOC.

### Suggested solution:

Add another option to the glamorous api to be able to filter specific properties which shouldn't be passed to the child component. According to 'forwardProps' 'filteredProps' would be a good name.

If somebody points me to the right direction how to implement this new option I would create a new pull request.

**Comment by kentcdodds** [comment]
Thanks for this. I'm fine with `filteredProps`. Thanks for being willing to help! Here's what needs to happen:

1. [Test it](https://github.com/paypal/glamorous/blob/master/src/__tests__/) (creating a `index.filter-props.js` file would be best I think). Should also behave [like `forwardProps` here](https://github.com/paypal/glamorous/blob/250bcec203506ef8667b0c14ea611f95609ed1c6/src/__tests__/create-glamorous.with-component.js#L20-L38) I think...
2. Implement it [here](https://github.com/paypal/glamorous/blob/master/src/create-glamorous.js) [and here](https://github.com/paypal/glamorous/blob/6d806889e9991065f1243d4abdce9c0b6cd3a2ae/src/split-props.js) (basically do the same thing we do with `forwardProps`).
3. Document it on [the website](https://github.com/kentcdodds/glamorous-website/blob/master/pages/api/content/glamorous.md) (open a PR on that repo).

Make sure to follow [the contributor guidelines](https://github.com/paypal/glamorous/blob/master/CONTRIBUTING.md).

Thanks!
