### ISSUE TITLE
[Question] How to create nested selectors using another GlamorousComponent generated class

### ISSUE THREAD

**Issue by renatorib** [paypal/glamorous#316]
I searched the documentation, examples and the issues, but I did not find anything about it, so I'm creating this issue. Sorry if it's a duplicate.

I used to do in styled-components this way:
```jsx
const Button = styled.button`
  color: red;
`

const Wrapper = styled.div`
  padding: 20px;

  ${Button} {
    color: blue;
  }
`
```
so:
```jsx
<Button>Red Text</Button>

<Wrapper>
  <Button>Blue Text</Button>
</Wrapper>
```

css-compat is something like that:
```css
.CompA {
  color: red;
}

.CompB {
  padding: 20px;
}

.CompB.CompA {
  color: blue;
}
```

But to do it, I need to access the generated class from CompA and use in StyleAttributes of CompB.

**How do you do it here in glamorous?**

I've debugged GlamorousComponent/API from console but did not find any way (method or property) to extract the generated class to use in my selectors.

I think would have something like that:

```js
const Button = glamorous.div({ color: 'red' })
console.log(Button.className) // css-button-somehash

const Wrapper = glamorous.div({
  padding: '20px',
  [`& ${Button.className}`]: {
    color: 'blue'
  }
})
```

**Comment by pedronauck** [comment]
+1

**Comment by kentcdodds** [comment]
Hey there! This has been discussed and even implemented, but we decided to not implement it. There's a bit of a history here...

But it's starting to be revived and I'm more and more positive that we can and should do this. See more info [here](https://github.com/kentcdodds/glamorous-website/issues/222).

> Ok, it's pretty clear folks want this feature. If someone wants to create a PR on the main repo to add it I'm happy to review (no promises). It needs to be well tested and as simple as possible. Please use [my original PR](https://github.com/paypal/glamorous/pull/183) as a reference because there were a few decisions I made in that PR that I think are important.

> Thanks for the discussion everyone!

I'll leave this issue open to track the development of the feature.

**Comment by renatorib** [comment]
Great to see the positive feedback. I think this is a very common use case, and could be a significant feature.

**Comment by kentcdodds** [comment]
Feel free to work on it! Nobody's really claimed it yet :)

@ anyone: If you want to work on it, comment in here when you're starting.

**Comment by renatorib** [comment]
I am studying the codebase, if I feel comfortable with it, I can create one PR.

**Comment by renatorib** [comment]
@kentcdodds 

I think the biggest problem is that classes could change (generating another classNames based on `shouldUpdate` rules inside `GlamorousComponent`. This can (and will) break styles in all others that rely on these classNames.

Perhaps the best solution is to create a trusted source of className. A unique generated string for each component, that goes together into `getGlamorClassName` guys.

If you give me positive feedback on this idea, I can create a PR right now with the initial works. The biggest question would be how to generate this unique class.

**Comment by kentcdodds** [comment]
Well, I literally had [a working implementation](https://github.com/paypal/glamorous/pull/183) that I felt pretty good about... Is there a reason that one wont work?

**Comment by renatorib** [comment]
Ops, I have not seen it. I'll take a look

**Comment by renatorib** [comment]
Wait. If you already have a working implementation, why not just use that code?

**Comment by braposo** [comment]
I still think this is only an issue because of the lack of documentation. If you compare with https://github.com/paypal/glamorous/pull/183#issuecomment-313196808, the only thing that prevents the initial example to work is not defining the class for the component.

You can play around with this sandbox for a better example on how this is currently supported: https://codesandbox.io/s/206pk4nrvr

As I said in my previous comment (https://github.com/paypal/glamorous/pull/183#issuecomment-314114010), I'm not against this but I think it makes it easier to introduce issues with style inheritance as it's very easy to lose track of which component is overriding the styles, specially if defined elsewhere.

I honestly think this kind of style overriding should be considered an anti-pattern in component-based styling frameworks (including styled-components). If the use-case is to change the styles depending on the wrapper component maybe that's a case for [theming](https://glamorous.rocks/advanced/#theming) instead, but for the large majority of situations using props and component composition is enough (and probably recommended).

Having that said, adding this wouldn't cause much friction as it won't change the API at all. My problem is with the behaviour that it enables.

**Comment by kentcdodds** [comment]
Thanks @braposo. I have similar feelings. But enough folks have bugged me about it that I think it's better to include it than not.

> Wait. If you already have a working implementation, why not just use that code?

Well, we can pretty much use that code, except 2 things:
1. There are some merge conflicts
2. Docs are now on the website, not in this repo.

So if anyone wants to make a new PR based on my original one that'd be great :) Shouldn't require a ton of effort I think.

**Comment by renatorib** [comment]
@braposo

Great points, I agree with almost everything. I just think there's no need to make it harder to discourage use. You can speak very little about the feature in the documentation, and when to say, argue about the negative points of this practice, and clarify that it is not a good practice.

> I honestly think this kind of style overriding should be considered an anti-pattern in component-based styling frameworks

Yes, I agree that is a anti-pattern. The big win with css-in-js and component-based styles, is that you can use all the power of javascript, composition and in case of React, the props flow.
However there are decades of CSS and its own techniques which we can not fail to consider. **Hindering these features means hindering the learning curve, and migration.**

@kentcdodds 

I'm going to use my weekend to work on it. But if anyone wants to start before, feel free and let me know so I can help too.

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this issue for now. We've got [an example](https://glamorous.rocks/examples#component-as-a-selector) on the site now. If anyone wants to improve that experience they're welcome to do so with a pull request :)
