### ISSUE TITLE
[Question]how to apply inline styles to glamorous component?

### ISSUE THREAD

**Issue by mzbac** [paypal/glamorous#317]
Hi all,

Not sure if I missed any thing from docs but I have gone through the docs, could not find how to apply the inline style to glamorous component? the reason I am asking this question because when I try to change the position of the glamorous component on window resizing event, it keeps generating style class in the header for every new position. 

there's a code sandbox example for my question:

[![Edit 2w4zzrwq6y](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2w4zzrwq6y)

**Comment by kentcdodds** [comment]
Yep! You [can use](https://codesandbox.io/s/pp4ryl6wjj) the regular `style` attribute. But it looks like `react-glamorous-tooltip` (super cool by the way, I wasn't aware that existed!) is using glamorous to set that position. You really don't need to worry about it though. It's super fast (try throttling your CPU using DevTools and it'll still be fast). It's super cool that it can be that fast right?!

I'll go ahead and close this issue as it's not really actionable. Enjoy glamorous!
