### ISSUE TITLE
Typescript: Build errors when using TS workaround

### ISSUE THREAD

**Issue by tenshiemi** [paypal/glamorous#318]
- `glamorous` version: 4.3.1, 4.6.0
- `glamor` version: 2.20.40
- `react` version: 15.6.1

Relevant code.

```javascript
// Per https://glamorous.rocks/api/ "Known Issues" section
// Underlying issue: Microsoft/TypeScript/issues/5938
import glamorous, { ExtraGlamorousProps, WithComponent  } from 'glamorous'
export { ExtraGlamorousProps, WithComponent }
```

What you did:

Builds just started failing this morning. I tried updating Glamorous and it didn't resolve the issue.

What happened:
```
ERROR in ./src/NumericInput/index.tsx
(7,31): error TS2305: Module '"/Users/echen/Code/nuna-ui-components/node_modules/glamorous/typings/glamorous"' has no exported member 'WithComponent'.

ERROR in ./src/NumericInput/index.tsx
(7,46): error TS2305: Module '"/Users/echen/Code/nuna-ui-components/node_modules/glamorous/typings/glamorous"' has no exported member 'WithProps'.

ERROR in ./src/NumericInput/index.tsx
(13,7): error TS4023: Exported variable 'NumericInput' has or is using name 'GlamorousComponent' from external module "/Users/echen/Code/nuna-ui-components/node_modules/glamorous/typings/glamorous-component" but cannot be named.

ERROR in ./src/index.tsx
(3,42): error TS2305: Module '"/Users/echen/Code/nuna-ui-components/node_modules/glamorous/typings/glamorous"' has no exported member 'WithComponent'.
Reproduction:
```

Problem description:

One of our devs implemented this code to fix a type definition issue per the Readme. Today when we tried to build we started getting the errors above. These exports previously existed and I'm not sure why they were removed. Not sure if workaround is no longer needed, or if Readme is out of date, or if the change to typings files is the problem.

Suggested solution:

**Comment by tenshiemi** [comment]
appears workaround no longer needed

**Comment by luke-john** [comment]
Hey @tenshiemi, apologies I forgot to update the documentation for re exporting when creating definition files.

There's getting to be a backlog of outdated and missing typescript documentation unfortunately,  I'll try and get some updated over the coming weekend.

Glad to hear you got it working.
