### ISSUE TITLE
Direct CSS Support

### ISSUE THREAD

**Issue by prasannavl** [paypal/glamorous#325]
Currently, the only thing I find not possible with galamorous/glamor combo is to be able to insert CSS styles sheet that are currently in pure CSS. While it is ideal to ditch them and just use js objects - it's not always practical to do so in many circumstances like working with existing components, existing module based components like styled-jsx/styled components, etc. It would also immensely helpful with some quick copy-pasting of styles while providing full css tooling support from most editors. 

It would be very nice there was a way to just use existing styles. Something like `insert`, but not for just a single rule, but rather a full set of styles. One way to do it would be to do something similar to what styled-jsx does, and just insert the stylesheet.

**Comment by luke-john** [comment]
Hey @prasannavl, thanks for the issue.

`glamor`s `insert` api allows you to add as many css rules as you'd like in a string so this may be what you are looking for.

ie.

```js
import {css} from 'glamor'

const pureCSSString = `
body {
    color: green;
}
p {
    color: red;
}
`

css.insert(pureCSSString)
```

**Comment by kentcdodds** [comment]
Thanks @luke-john :+1:

This is a pretty common question, so it might be a good idea for us to add it to the documentation.

What do you think @prasannavl? Would you like to try? Could probably just add it to [this](https://github.com/kentcdodds/glamorous-website/edit/master/pages/advanced/content/existing-css.md) :)

**Comment by prasannavl** [comment]
@luke-john - ah, thanks for the pointer! I didn't realize glamour supported it. 

@kentcdodds - Sure, I'll do it over the weekend. :) 

PS: Glamor docs seems to say it's experimental and buggy? 
 (https://github.com/threepointone/glamor/blob/master/docs/css.md). I've just barely played with it - So, I'm not sure if most common patterns work without issues.

**Comment by kentcdodds** [comment]
Ah, that's for something else, you're looking for this: https://github.com/threepointone/glamor/blob/master/docs/api.md#cssglobalselector-style-cssinsertcss

:smile:

**Comment by prasannavl** [comment]
@kentcdodds - https://github.com/threepointone/glamor/issues/321 states that css insert will only work with single rule.

**Comment by kentcdodds** [comment]
Ah, yes, I'm sure @threepointone would appreciate a PR to update the glamor docs as well :wink:

On this note, I've always recommended that folks use regular stylesheets for things like this. Most applications shouldn't have more than 50 lines or so of CSS that they need injected like this so may as well just use raw CSS 🤷‍♂️

**Comment by prasannavl** [comment]
@kentcdodds - Perhaps I wasn't clear? - According to `glamor` - `css.insert` will only work with single rule. So the example @luke-john provided above will only in dev mode, and will fail in production. 

The one that's supposed to the be `real css` api is the one that's stated as buggy and experimental. 

I do agree that it just has to be raw CSS for large ones. Just trying to ensure here that if this actually works.

**Comment by kentcdodds** [comment]
Ok, so the link you provided (https://github.com/threepointone/glamor/blob/master/docs/css.md) is about an entirely different thing (a babel plugin that allows you to write glamor styles with a `css` prop on react components). That is experimental. The `css.insert` feature is not experimental, but it only works for one rule. If you want to insert multiple rules then you simply call it multiple times.

So if we update the docs we should indicate that `css.insert` only works for one rule and suggest that folks use a regular stylesheet if they have more rules.

**Comment by prasannavl** [comment]
Ok, that makes sense. Thanks. :) So, now to put it in the context of the issue - perhaps, the resolution would be to simply delegate it to the babel plugin and wait for it stabilize.

**Comment by kentcdodds** [comment]
I'm afraid that the babel plugin is totally unrelated to this issue...

**Comment by prasannavl** [comment]
@kentcdodds  - Sorry, I updated the comment after realizing that. It seems you read the old one :)

**Comment by kentcdodds** [comment]
Gotcha :+1:

Yes, we understand each other :clap:

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
