### ISSUE TITLE
Typescript props issue: Property 'size' does not exist on type '{ theme: object; }'.

### ISSUE THREAD

**Issue by jakeleboeuf** [paypal/glamorous#328]
- `glamorous`: 4.9.1
- `glamor`: 2.20.40
- `react`: 15.6.1
- `typescript`: 2.4.2

#### Relevant code.

```javascript
import React from 'react';
import { render } from 'react-dom';
import glamorous, { ThemeProvider } from 'glamorous';
const { img, div } = glamorous;

const Logo = img(
  {
    height: 80
  },
  props => ({
    height: props.size
  })
);

function App() {
  return (
    <Logo
      size={300}
      src="https://www.realthread.com/assets/hero/sketch@3x-38bee0f40a276225b56b52f984158ad9.jpg"
    />
  );
}

render(<App />, document.getElementById('root'));

```

#### What you did:

I'm _just_ getting my feet wet with typescript (and react...), so maybe there is something obvious I need to do?

#### What happened:

`Property 'size' does not exist on type '{ theme: object; }'.`

![image](https://user-images.githubusercontent.com/690573/30492471-9091eeee-9a0e-11e7-97d8-ae23fad93ff2.png)

#### Reproduction:

https://stackblitz.com/edit/react-ts-glamorous-help-rwyaqi

#### Problem description:

grabbing props is throwing a type error.

**Comment by marzelin** [comment]
Specify custom properties that your component needs in angle brackets:
`const Logo = img<{size: number}>(`

**Comment by jakeleboeuf** [comment]
Thanks Marzelin- Is this syntax documented somewhere?

**Comment by marzelin** [comment]
@jakeleboeuf This feature is called *generics* and is used everywhere in typescript. You can read more about it here: https://www.typescriptlang.org/docs/handbook/generics.html

As for using glamorous with typescript specifically, you can get more info here: https://glamorous.rocks/api#typescript

**Comment by jakeleboeuf** [comment]
@marzelin thanks so much!!
