### ISSUE TITLE
Fix test:ts

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#335]
See [this build](https://travis-ci.org/paypal/glamorous/builds/279108767) and you'll see the `test:ts` output has a whole bunch of messages that I think mean something's wrong. I'm not sure what's up though.

**Comment by luke-john** [comment]
Looking into it now

**Comment by luke-john** [comment]
ahh, looks like the version of typescript used when running the test was different to the version that was used to create the snapshots.

Typescript improved error messages in 2.5 to include suggestions for mis-speliing so the typescript expected error messages in the snapshot are failing on the suggestions that have been added to the output.

Looks like that snapshots been fixed on master though so you may just need to rebase.

**Comment by luke-john** [comment]
oh actually, I was looking at the wrong thing here.

The `test:ts` command output is a bit meaningless, that test/npm script predates the addition of the snapshot test added to the main tests and can be removed.

I'll open a pr to remove shortly.

Thanks
