### ISSUE TITLE
Breakpoint priority/source order

### ISSUE THREAD

**Issue by johnnyBira** [paypal/glamorous#342]
- `glamorous` version: 4.9.5
- `glamor` version: 2.20.40
- `react` version: 15.6.1

What you did:

I'm writing a HOC for breakpoints and have run into an issue that is likely related to media query source order.
In the HOC I generate an array of media queries which is then passed to the wrapped component.
In turn the wrapped component adds it's own styles (with own media queries) and pass those together with the props from the HOC as an array to the glamorous css prop.
```javascript
<Column css={[styles, breakpoints]}>
  {children}
</Column>
```

What happened:

As expected the styles/media queries are merged, but the problem is they are outputted in an undesired order. Since I'm using mobile first (min-width) media queries this causes both 1200 and 992 to match, but the latter takes precedence since it appears last in the source order.

<img width="1236" alt="example" src="https://user-images.githubusercontent.com/23634023/31068449-52e0e954-a758-11e7-8854-155adf426235.png">

Suggested solution:

A way to specify source order for situations when it matters. I'm currently looking into how this could be done but I'm not sure if it's the right approach. Since the key/value order of the objects aren't guaranteed I'm not even sure it's possible. Any suggestions or experience on this is highly appreciated.

**Comment by kentcdodds** [comment]
Hi @johnnyBira, thanks for the issue. The solution to this problem would have to be in [glamor](https://github.com/threepointone/glamor). Could you move this issue to over there please?

Thank you, and good luck!

**Comment by johnnyBira** [comment]
Thanks for the reply @kentcdodds and all your work on Glamorous! Really enjoy working with it, and I feel inspired to contribute to related open source projects.
I'll investigate this further and look into wether this is an actual issue or not.

Thank you again and keep up the good work!
