### ISSUE TITLE
Setting "default" styles

### ISSUE THREAD

**Issue by jeromepeters** [paypal/glamorous#343]
How should I set the ``body`` style, in the rendered file like

```
<style>
body {
  color: white;
}
```

And is it possible to import fonts and use them with ``Glamorous``? Thought about something like the following:

```
import font from './fonts/fontname.ext'

const style = {
    fontFamily: font
}
```

**Comment by kentcdodds** [comment]
Hi @jeromepeters,
You'll want to use `glamor` to do this: https://github.com/threepointone/glamor/blob/master/docs/api.md

Thanks!

**Comment by jeromepeters** [comment]
@kentcdodds works like a charm, thank you so much!
