### ISSUE TITLE
glamorous.div is ok, not glamorous('div')

### ISSUE THREAD

**Issue by bulby97** [paypal/glamorous#344]
I have a weird bug, and I don't know if it's related to SSR or anything else.

I want to use glamorous on an old project based on [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example).
When I'm using glamorous.div, everything is fine. As soon as I use glamorous('div'), I have `glamorous is not defined` logged is the server console.

![image](https://user-images.githubusercontent.com/3509412/31687078-89bb0cd4-b388-11e7-9774-ca11e8ae1583.png)

Here a simple example based on my Row component 👍 

``` javascript
import glamorous from 'glamorous'

const Row = glamorous.div(({ extended }) => ({ // THIS IS OK
  position: 'relative',
  maxWidth: extended ? 1330 : 1200,
  margin: '0 auto',
  boxsizing: 'border-box',
  display: 'flex',
  flexDirection: 'row',
  flexWrap: 'wrap',
}))

const Row = glamorous('div')(({ extended }) => ({ // THIS IS NOT OK
  position: 'relative',
  maxWidth: extended ? 1330 : 1200,
  margin: '0 auto',
  boxsizing: 'border-box',
  display: 'flex',
  flexDirection: 'row',
  flexWrap: 'wrap',
}))

export default Row
```

Maybe it can help,  here is my [gist](https://gist.github.com/bulby97/769a532ed191d8f366fd26fdec7b95a2) with more files.

I'm using
"glamor": "^2.20.40",
"glamorous": "^4.9.7",
"react": "15.5.4",

Did I miss something ?

**Comment by bulby97** [comment]
Alright, figured out.

This is somewhat related to babel-plugin-glamorous-displayname 🤔 🤔 .

I will investigate further :)

**Comment by kentcdodds** [comment]
Thank you! I hope we can get it fixed. Super weird!

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
