### ISSUE TITLE
Visiting website page directly for getting-started triggers a download

### ISSUE THREAD

**Issue by agmcleod** [paypal/glamorous#346]
Hi there!

Visited the main site, and went to the getting starting page, which worked fine. However, if i refreshed the page, or copied the URL into another tab, i receive a download request.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/113275/31750041-8aa5c102-b44b-11e7-816a-60ba987af27c.png">

Seems to happen to me in firefox & chrome, but not Safari. Tested on Mac OS Sierra.

**Comment by kentcdodds** [comment]
Hi! Thanks for reporting! That's super weird. I have no idea why that would be happening... Could you investigate further?

**Comment by luke-john** [comment]
Just had a quick look and the content-type looks suspect.

![image](https://user-images.githubusercontent.com/848525/31751247-fa735d8a-b4b6-11e7-930f-b1831468edbc.png)

**Comment by kentcdodds** [comment]
Sounds like an issue with now.sh then...

**Comment by kentcdodds** [comment]
I think it was fixed! https://twitter.com/TooTallNate/status/920876268752531456

**Comment by kentcdodds** [comment]
Thanks again!

**Comment by agmcleod** [comment]
Thanks for fixing :)
