### ISSUE TITLE
Glamorous label does not pass down 'for' prop

### ISSUE THREAD

**Issue by thomhos** [paypal/glamorous#347]
It seems that a Glamorous label doesn't pass down the 'for' property to the actual label element. I am assuming this is a bug rather than a feature, as I wasn't able to find a note about it in the docs.

Here's an example on CodeSandbox: https://codesandbox.io/s/5z5440z96k

Basically the code is:
```js
const CustomLabel = glamorous.label({ ...styles })

<Label for='notPassed' />
```

React 15.5.3
Glamorous 3.23.5

I'm not sure where to look for fixing this. With some pointer I can submit a PR for this.

Cheers!

**Comment by marzelin** [comment]
this  is react's "feature". see: https://reactjs.org/docs/dom-elements.html#htmlfor

**Comment by thomhos** [comment]
Wow, thanks for the quick reply. Totally missed that :D
