### ISSUE TITLE
flow types being added to flow-typed

### ISSUE THREAD

**Issue by aaronjensen** [paypal/glamorous#348]
I'm opening this issue for visibility. I'm in the process of building out flow types for glamorous. We've just started using them internally and I will continue to add functionality as I go. They're not complete yet. 

Given that they don't have the full css properties in the file, they're not even usable at the moment. I have a copy of those elsewhere. If anyone would like to try them on their codebase, please let me know and I'll make those available.

In the meantime, if anyone would care to review the existing test cases, I would appreciate it.

If anyone would care to add more test cases and add additional functionality, I would appreciate it as well.

https://github.com/flowtype/flow-typed/pull/1393

Thanks!

**Comment by kentcdodds** [comment]
Awesome! Thank you very much!

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
