### ISSUE TITLE
Suggestion: allow `innerRef`-prop to be passed to underlying component via option-flag

### ISSUE THREAD

**Issue by danielberndt** [paypal/glamorous#349]
I'm working on a project with a big `Ui` File which exports a lot of components like Buttons, Boxes, Text-Components, etc.

I'd like those to behave as similarily as possible. I.e. I'd like them all to use `innerRef` to be able to access the underlying _DOM_-Node.

For wrapping plain html-tags (`glamorous('div')({...})`) this works as expected. 
Now if I want to wrap a Component like a React-Router `Link` I can do `const WrappedLink = glamorous(Link)({})`

If I write `<WrappedLink innerRef={...}/>` `innerRef` gives me the reference to the `Link` Component. However I would like to do something like this:

```
const WrappedLink = glamorous(Link, {forwardProps: ["innerRef"]})({})
```

such that `innerRef` now is passed to the `Link` component yielding its underlying DOM-Node.

I believe that fixing [this line](https://github.com/paypal/glamorous/blob/f8d833619547e64506fabb40dead6e6992a3347a/src/create-glamorous.js#L89) could resolve this issue.

Do you believe it's worthwhile pursuing? If so I'm happy to do a PR :)

**Comment by marzelin** [comment]
To achieve your goal you can use `findDOMNode()` from `react-dom` package:
```js
<WrappedLink innerRef={
    (ref) => el = ReactDOM.findDOMNode(ref)
}/>
```

Implementing your suggestion would require changes in [this file](https://github.com/paypal/glamorous/blob/f8d833619547e64506fabb40dead6e6992a3347a/src/split-props.js#L16) as well (adding `innerRef` to forwarded props on specific condition).

**Comment by danielberndt** [comment]
Thanks for your suggestion!

However I don't really like relying on `ReactDOM.findDOMNode`. First it's not cross-plattform, and second, it's possible that `innerRef` and `ReactDOM.findDOMNode` might return different nodes* in which case I want to rely on the result of `innerRef`.

*Think of something like `<Container><input ref={this.props.innerRef}/></Container>`

**Comment by kentcdodds** [comment]
Hi @danielberndt,
I don't see any reason to disallow opting-into forwarding `innerRef` as you have here. I'd be open to a pull request with the implementation and tests :+1:

Thanks!

**Comment by Ailrun** [comment]
Nice! I really appreciate for your suggestion!
