### ISSUE TITLE
[Discussion] How to use glamorous with MUI child components (Drawer example)

### ISSUE THREAD

**Issue by FjVillar** [paypal/glamorous#354]
Hi everyone,

## Problem decription:

We are using **MUI-next** in our application.

We are trying to apply styles to the Drawer (a MUI [component](https://material-ui-next.com/demos/drawers/)). This component has a child called Paper, but you can't access that component since It's inside Drawer. (If you want to see Paper on the browser you have to render a Drawer).

Our first attempt with Glamorous was unsatisfactory (check the [codesandbox](https://codesandbox.io/s/zqq1555qpp) to see what happened). We applied some styles to Drawer ( fixed width to 240px) but they didn't work. We expected MUI's Drawer to have some kind of inheritance that would apply these styles to Paper. 

This a piece of code of the previous Codesandbox:

```js
const StyledDrawer = glamorous(Drawer)({
  backgroundColor: "grey !important",
  width: 240 // OMG its not working! T.T
});

const Sidenav = () => {
  return (
    <StyledDrawer type="permanent">
      <Divider />
      Sidenav Content
      <Divider />
    </StyledDrawer>
  );
};
```

This is what MUI says about Drawer and Paper([api documentation](https://material-ui-next.com/api/drawer/)):

> You can override all the class names injected by Material-UI thanks to the classes property. This property accepts the following keys:
> - ...
> - paper

Of course I was wrong on that approach. That was an expample for you to understand what I'm trying to achieve: **Apply the width style (240px) to the Drawer**. 

So, as MUI requires, we need to pass the styles by the built-in **classes** attribute. To achieve that, I got to two different solutions for this:
1. The MUI solution which is using **withStyles**.
2. The Glamor solution (the closest to Glamorous).

###  1. MUI solution
Check this other [Codesandbox](https://codesandbox.io/s/vl4o8xko7) to see the result. This works. 

```js
const drawerPaperStyles = {
  backgroundColor: 'grey !important',
  width: 240  
};

class Sidenav extends Component {

  render() {
    const { classes } = this.props;
    return (
      <Drawer classes={{ paper: classes.drawerPaperStyles }} type="permanent">
        <Divider />
        Sidenav Content
        <Divider />
      </Drawer>
    );
  }
}

export default withStyles({ drawerPaperStyles })(Sidenav);
```
But we weren't happy about this since we are not using Glamorous here. And we wanted the styled component approach of glamorous in every component in our application without using the *withStyles* approach of MUI. 

###  2. Glamor solution
So we tried it with **Glamor** trying to achieve something closer to Glamorous. We end up with this other [solution](https://codesandbox.io/s/x3qzy941xp).

```js
const drawerPaperStyles = {
  backgroundColor: 'grey !important',
  width: 240  
};

// First we get the classNames with Glamor css function
const drawerPaperClasses = css(drawerPaperStyles);

// We need the class names to be strings
const classNamesStrings = classnames(drawerPaperClasses.toString());

// Then we just assign them to the paper in the Drawer's classes attribute
class Sidenav extends Component {

  render() {
    return (
      <Drawer classes={{ paper: classNamesStrings }} type="permanent" >
        <Divider />
        Saysomething
        <Divider />
      </Drawer>
    );
  }
}

export default Sidenav;
```

We are not using Glamorous but at least It's Glamor.

## Question

So we ask the community:

- What do you think it is the best solition to achieve this from the examples above? If none ¿How would you do it?
- Is there some *pure* way to do it with Glamorous that you have managed to accomplish?

### Codesandbox

Drawer Paper child component with glamorous (erroneus approach)
[![Edit Drawer Paper child component with glamorous (erroneus approach)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zqq1555qpp)

Drawer Paper child component with Glamor
[![Edit Drawer Paper child component with Glamor](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x3qzy941xp)

Drawer Paper child component with withStyles
[![Edit Drawer Paper child component with withStyles](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vl4o8xko7)

- `glamorous` version: 4.11.0
- `glamor` version: 2.20.40
- `react` version: 15.6.2
- `mui`version: 1.0.0-beta.18

**Comment by kentcdodds** [comment]
Yeah, unfortunately the glamorous approach wont work at all because [this](http://www.material-ui.com/#/customization/styles):

> Every component provides a className property. Those properties are always applied to the root element.

And you need the class name that glamorous passes to be applied to a child element, not the root. This is an unfortunately limitation of the material UI library. I suggest your glamor solution is probably best.

Good luck!

**Comment by marzelin** [comment]
If you want to use glamorous, here's one way to do it with attribute selectors:
```js
const StyledDrawer = glamorous(Drawer)({
  "& [class^=MuiPaper]": {
    backgroundColor: "grey !important",
    width: 240 // OMG its working! T.T
  }
});
```

**Comment by techniq** [comment]
I've run into this today as well.  I was looking to use `Glamorous`/`styled-components`/etc so I could have dynamic styles (for instance, modify `<AppBar />`'s margin and width when a `<Drawer type="persistent" />` is open without having to toggle classeName's manually as MUI's [example](https://material-ui-next.com/demos/drawers/#persistent-drawer) does.  I was also receiving the drawer width as a prop, which makes it impossible to pass this to the static styles definition. 

Also note, the specificity of the styles becomes a problem as well, which is being discussed [here](https://github.com/styled-components/styled-components/issues/860#issuecomment-321710970).

---
Just had an idea... maybe it would be nice if you could apply the className to the wrapped component yourself.  Maybe something like:

```js
const StyledDrawer = glamorous({
  backgroundColor: "grey !important",
  width: 240
})(({ className, ...props }) => <Drawer className={className} {...props} />) ;
```
this example is just to show where className is coming from.  Technically it could just be...

```js
const StyledDrawer = glamorous({
  backgroundColor: "grey !important",
  width: 240
})(props => <Drawer {...props} />) ;
```

but going with the explicit case and working with nested elements could create multiple classNames (or could be called `classes) like MUI, such as...
```js
const StyledDrawer = glamorous({
  drawer: {
    backgroundColor: "grey !important",
  },
  paper: {
    width: 240
  }
})(({ classes, ...props }) => <Drawer classes={classes} {...props} />) ;
```

The problem would be when to know when to generate multiple classnames for nested elements and when they are just nested css selectors without using a DOM whitelist.  Maybe some special identifier/prefix like `$drawer` or `&drawer`.

Anyways, just some ramblings/possible ideas (but not very well thought out).

**Comment by kentcdodds** [comment]
You can actually do that already @techniq :smile:

https://codesandbox.io/s/y2l4w9j939

```js
const StyledDrawer = glamorous(({className, ...props}) => (
  <Drawer classes={{paper: className}} {...props} />
))({
  backgroundColor: 'grey !important',
  width: 240, // OMG its not working! T.T
})
```

Not exactly ergonomic, but I blame MaterialUI for that :wink:

**Comment by techniq** [comment]
@kentcdodds awesome!  but what about multiple classnames for the same wrapped component (MUI's drawer has potentionally [9](https://material-ui-next.com/api/drawer/#css-api))

**Comment by kentcdodds** [comment]
In that case just use glamor. I don't think I want to do anything about this directly in glamorous. That's out of scope.

**Comment by techniq** [comment]
Understood. Is it safe to use glamor in `render` for dynamic styles, or will it append a lot of rules into the head?

**Comment by kentcdodds** [comment]
Uhhh... I guess it's probably safe-ish... But I wouldn't recommend it. I'd just use glamor 🤷‍♂️

**Comment by oliviertassinari** [comment]
> Yeah, unfortunately the glamorous approach wont work at all because this:

@kentcdodds You are referring to the v0.x version of Material-UI. We are relying on JSS with v1.
In the documentation, [we state that](https://material-ui-next.com/customization/overrides/#overriding-with-class-names):

> The CSS injected by Material-UI to style a component has the highest specificity possible as the <link /> is injected at the bottom of the <head />. This way, we ensure our components always render correctly.

Could you clarify the injection order of the link of glarmorous? It seems that Material-UI suffers the same injection order issue than with styled-components. JSS exposes a [`insertionPoint` option](http://cssinjs.org/js-api/?v=v9.1.0#setup-jss-instance) to dodge the issue. I wish we had a better Interoperability story.

**Comment by kentcdodds** [comment]
No, I'm not saying that priority/css insertion order is the problem, I'm saying that the fact that the `className` prop is applied to the root element is the problem. They're just not really built to work together. glamorous takes a component and some css and passes the generated class name to that component. Because your components require you pass multiple class names they're simply incompatible.

**Comment by oliviertassinari** [comment]
> I'm saying that the fact that the className prop is applied to the root element is the problem.

Ohhh, I have missed this part of the discussion!

**Comment by oliviertassinari** [comment]
> Because your components require you pass multiple class names they're simply incompatible.

@kentcdodds The only alternative I can think of on Material-UI side is to allow users to provide their own implementation of each component. They way, they would be able to provide, in our case, a styled Paper element to the Drawer. I need to mature the reflexion on this end.

**Comment by oliviertassinari** [comment]
This just crossed my mind, it's not a Material-UI unique limitation. How would one style [react-autosuggest](https://github.com/moroshko/react-autosuggest#theme-optional)? I won't accept [downshift](https://github.com/paypal/downshift) as an answer, it's cheating 😛 . I'm very happy to have crossed this issue. It's a new challenging problem to solve.

**Comment by kentcdodds** [comment]
I would use downshift 😜
But if I couldn't, then I'd just use glamor. I don't mind that 🤷‍♂️

**Comment by techniq** [comment]
The injection order / specificity is still a problem regardless of the multiple classname issue.

![image](https://user-images.githubusercontent.com/177476/32382741-72391ed2-c08c-11e7-87ab-2d355320fa10.png)

Notice the overridden width. 

This is a problem whether I let glamorous pass the `className` to MUI's `AppBar` implicitly: 
```js
const StyledAppBar = glamorous(MuiAppBar)(props => ({
  marginLeft: props.drawerWidth,
  width: `calc(100% - ${props.drawerWidth}px)`
}));
```

or explicitly via the `classes` prop and `root` key
```js
const StyledAppBar = glamorous(({ className, ...props }) => (
  <MuiAppBar classes={{ root: className }} {...props} />
))(props => ({
  marginLeft: props.drawerWidth,
  width: `calc(100% - ${props.drawerWidth}px)`
}));
```

One hack (as [mentioned](https://github.com/styled-components/styled-components/issues/860#issuecomment-337874677) by mxstbr) is to apply the generated classname repeatedly to the styles to increase their specificity.
```js
const StyledAppBar = glamorous(MuiAppBar)(props => ({
  '&&': {
    marginLeft: props.drawerWidth,
    width: `calc(100% - ${props.drawerWidth}px)`
  }
}));
```

which generates:
![image](https://user-images.githubusercontent.com/177476/32383170-a31bc2c4-c08d-11e7-8ed1-70d5faf2b5e3.png)

**Comment by kentcdodds** [comment]
Actually, specificity is a pretty simple battle to win with a simple glamor plugin (works for glamor and glamorous): https://github.com/threepointone/glamor/issues/107#issuecomment-260165887

**Comment by techniq** [comment]
@kentcdodds thanks for the quick reply, I just tried it and it works.

@oliviertassinari Regarding react-autosuggest, they use [consistent classnames](https://github.com/moroshko/react-autosuggest#theme-optional) so thus they can be declared as nested selectors.  Some discussions on this with regards to styled-components is [here](https://github.com/styled-components/styled-components/issues/1085).

**Comment by techniq** [comment]
@kentcdodds @oliviertassinari I started thinking about this a little more this afternoon and thought something like this would work.... 

```js
const StyledDrawer = glamorous(({ className, ...props }) => (
  <Drawer classes={{
    //root: className,
    paper: `${className}-paper`
  }} {...props} />
))({
  backgroundColor: 'grey',
  width: 240,
  '&-paper': {
    backgroundColor: 'green',
  }
});
```
but the nested rule doesn't appear to be working.  I see the following style injected into `<head />` (formatting done by me)

```html
<style type="text/css" data-glamor="">
  #root .css-glamorous-unknown--qc0kp4,
  #root [data-css-glamorous-unknown--qc0kp4 {
    background-color: grey;
    width:240px;
  }

  #root .css-glamorous-unknown--qc0kp4-paper,
  #root [data-css-glamorous-unknown--qc0kp4]-paper{
    background-color: green;
  }
</style>
```

and the following html:
```html
<div class="MuiPaper-root-10 MuiPaper-shadow0-12 MuiDrawer-paper-2 css-glamorous-unknown--qc0kp4-paper MuiDrawer-paperAnchorDockedLeft-7"><hr class="MuiDivider-root-37 MuiDivider-default-38"><!-- react-text: 4 -->Sidenav Content<!-- /react-text --><hr class="MuiDivider-root-37 MuiDivider-default-38"></div>
```
which includes `css-glamorous-unknown--qc0kp4-paper` in it's classes so I'm not sure what I'm overlooking.

I setup a [codesandbox](https://codesandbox.io/s/wj34wppvk) if someone else could take a look

**Comment by marzelin** [comment]
@techniq Selector `[data-css-glamorous-unknown--qc0kp4]-paper` is invalid which makes the whole ruleset invalid, so style declarations are not applied.

**Comment by techniq** [comment]
@marzelin good catch.  I was able to get this to work... 🎉 

```js
const StyledDrawer = glamorous(({ className, ...props }) => (
  <Drawer className={className} classes={{
    paper: 'paper'
  }} {...props} />
))({
  '& .paper': {
    width: 240,
    backgroundColor: 'green',
  }
});
```

This approach does have a potential risk of unexpected global styles taking affect, such as...

```css
.paper {
  background-color: 'red'
}
```

would also match the paper within `StyledDrawer` unless `StyledDrawer` had the same rules as they would have a higher specificity.  It's not a bad solution, but is prone to unexpected styling.

**Comment by techniq** [comment]
Btw, here is a little more concise approach (allowing `glamorous` to pass down `className` and the remaining props implicitly)

```js
const StyledDrawer = glamorous(Drawer, { withProps: { classes: { paper: 'paper' }}})
({
  '& .paper': {
    width: 240,
    backgroundColor: 'blue',
  }
});
```

I did come across an odd issue when using this glamor plugin to increase the css specificity (to beat JSS's rules) and codesandbox

```js
function specific({ selector, style }) {
  const newSelector = selector
    .split(',')
    .map(s => `#root ${s}`)
    .join(',')
  return { selector: newSelector, style }
}
plugins.add(specific)
```
If I change a rule and let codesandbox live reload, the plugin is double-prefixing `#root`

```
#root #root .css-glamorous-withstyles-drawer---1ds5hjh,#root #root [data-css-glamorous-withstyles-drawer---1ds5hjh]{null}
#root #root .css-glamorous-withstyles-drawer---1ds5hjh .paper,#root #root [data-css-glamorous-withstyles-drawer---1ds5hjh] .paper{width:240px;background-color:red;}
```

**Comment by techniq** [comment]
Sorry for all the noise, but a simple workaround for the repeated prefixing is to check and only apply the prefix if it hasn't been yet, such as

```js
function specific({ selector, style }) {
  const newSelector = selector
    .split(',')
    .map(s => s.startsWith('#root') ? s : `#root ${s}`)
    .join(',')
  return { selector: newSelector, style }
}
plugins.add(specific)
```

I'm a little surprised glamor/glamorous is maintaining the prefixed selector names each time, but this works none-the-less.

**Comment by kentcdodds** [comment]
What's happening is when codesandbox does hot module replacement on your example, it is adding the plugin multiple times :P

**Comment by techniq** [comment]
Makes sense. Thanks

**Comment by oliviertassinari** [comment]
Very interesting thread! Anyone want to write an glamorous integration documentation page on Material-UI side? It would also help us think of how we can improve the integration story.

**Comment by oliviertassinari** [comment]
@FjVillar I was thinking of creating a new guide: `Interoperability`, explaining how to use glamourous, styled-components, CSS-modules, etc. with Material-UI. We can start with glamourous 
:).
