### ISSUE TITLE
[TypeScript] Component as selector: className does not exist on GlamorousComponent type

### ISSUE THREAD

**Issue by Tenga** [paypal/glamorous#355]
- `glamorous` version: 4.11.0
- `glamor` version: 2.20.40
- `react` version: 15.6.2
- `typescript` version: 2.5.3

#### What you did:

Following the docs for [Component as selector](https://glamorous.rocks/examples/#component-as-a-selector), assigning the `className` props in TypeScript seems to be impossible as the compiler fails due to `className` not existing on the type returned.

#### Relevant code:

```typescript
const footerHeaderClassName = `app-footer-header`;
const FooterHeader = glamorous.div(footerHeaderClassName, {color: 'red'});
FooterHeader.className = footerHeaderClassName;
```
#### What happened:
```
[ts] Property 'className' does not exist on type 'GlamorousComponent<HTMLProps<HTMLDivElement>, object>'.
```

#### Reproduction:
https://stackblitz.com/edit/react-ts-glamorous-help-acryds

#### Problem description:
I assume there are incomplete typings here, as you can see in the repro, the app works as intended, but will cause the compiler to fail unless the type error is ignored.

**Comment by luke-john** [comment]
Hey @Tenga, thanks for the detailed issue and reproduction.  The docs for Component as selector appear to suggest monkey patching the react component to couple the classname to the component.

I'm hesitant to add this to the typings as it's not really part of the glamorous api.

To achieve what you want you could instead use the `footerHeaderClassName` value in the following components selector. I've setup an example of this working at the following stackblitz.

https://stackblitz.com/edit/react-ts-glamorous-help-j4ytsf?file=index.tsx

**Comment by Tenga** [comment]
I've just resolved it in my project the same way. 🙂 

The slightly annoying thing is, should `FooterHeader` need to be exported to be reused, you also need to export the other var that stores the `className` instead of just accessing it from the `FooterHeader`.

I've read the discussions on the components-as-selectors that have been going on. Hopefully someone will eventually come up with an official and satisfactory common way to simply reuse the glamorous generated className as a selector, even tho it's considered to be an anti-pattern. 😄
