### ISSUE TITLE
[Suggestion] Addition to documentation section "Working with existing CSS"

### ISSUE THREAD

**Issue by jamaldewitte** [paypal/glamorous#356]
Hi all, 

I'm not exactly sure if this is the correct section as the below doesn't seem to be an issue but more of a suggestion, but here goes. 

I was interested in getting bootstrap to work with glamorous and I found [this doc section](https://glamorous.rocks/advanced/#working-with-existing-css). 

 In the bootstrap example in the above docs, the following syntax is used in [codesandbox](https://codesandbox.io/s/73W7nZ6BQ):
    `const Alert = glamorous.div('alert', props =>` `alert-${props.type}` `');`

Based on my understanding, this basically appends 'alert' and 'alert-xxx' to props.className and React  renders it the DOM with prop `"class = "glamor-generated-class alert alert-xxx".

At first I was a bit confused why this worked, but then I realized that no object literal is passed into glamorous.div, but just strings.  I looked in the documentation and I could not find any additional information on this, and I thought it may be helpful to add this information in case other people would find it confusing at first sight. Also, the 'normal' react syntax also works (though you cannot use dynamic props and maybe some other features I don't know so I assume that's why its not written down in the docs): 

`<Alert className = "alert alert-success"` </Alert>` 

Furthermore, maybe it would be nice if there was a bit more information regarding CSS specificity and where the CSS produced by glamorous is lexically located in the compiled app (is it like styled-components right above </head>?) . For example if I add {backgroundColor: red} to the below code:

  `const Alert = glamorous.div('alert', props => ` `alert-${props.type}` `, {backgroundColor: red}');`

This overrides the bootstrap color, which is exactly the behavior we want to see. However, I could imagine there may be cases where this desired behavior does not happen in case bootstrap is lexically located after Glamorous in the compiled app (is this even possible? I don't know). I.e. similar problem as with using Material UI and Glamorous [github reference to issue](https://github.com/paypal/glamorous/issues/354). The referenced issue contains a fix for this, but maybe would be helpful to know for new users. 

I just recently started learning (web) development so sorry for any wrong use of terminology and hesitant manner of speech. 

Cheers,
chocomel

**Comment by kentcdodds** [comment]
Hi @chocomel1!

Thank you for bringing this up! I'd welcome any improvement you'd like to make to the existing documentation in this regard. Would you like to [make a pull request](http://makeapullrequest.com) to do that? You may be able to do it using the github editor as well (no need to pull down the repo).

**Comment by kentcdodds** [comment]
Oh, and the repo is here: https://github.com/kentcdodds/glamorous-website

There should be an edit link next to the section you'd like to update :)

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
