### ISSUE TITLE
Typescript errors when passing dynamic styles

### ISSUE THREAD

**Issue by johhansantana** [paypal/glamorous#359]
Hello

I've been getting a few errors on typescript. When I try to add dynamic styles to a glamorous component I get the following:
![image](https://user-images.githubusercontent.com/9933887/33132222-80d5638e-cf45-11e7-9787-efb1f256bcb1.png)
`Error:(21, 5) TS2459:Type '{ theme: object; }' has no property 'backgroundUrl' and no string index signature.`

Also when I add this property in the component I get:
![image](https://user-images.githubusercontent.com/9933887/33132253-ada1b0ac-cf45-11e7-9610-01c9aa9d2a9c.png)
`Error:(36, 15) TS2339:Property 'backgroundUrl' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<{ theme: object; }, never> & HTMLPr...'.`

Everything seems to be working correctly though.

**Comment by johhansantana** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/9933887/33132993-cf36905a-cf47-11e7-8519-b904572fb289.png)

![image](https://user-images.githubusercontent.com/9933887/33133002-d57fc512-cf47-11e7-9827-180eb960ae74.png)

**Comment by Ailrun** [comment]
@johhansantana 
You can also use following

```
export const Header = glamorous.div<HeaderProps>({
    ...
  },
  ({ backgroundUrl }) => ({
  })
)
```

And you can use destructuring with type annotation
```
export const Header = glamorous.div({
    ...
  },
  ({ backgroundUrl }: HeaderProps) => ({
  })
)
```
