### ISSUE TITLE
[TS] KeyGlamorousComponentFactory generate different type to BuiltInGlamorousComponentFactory

### ISSUE THREAD

**Issue by Ailrun** [paypal/glamorous#360]
- `glamorous` version: 4.11.0
- `glamor` version: 2.20.40
- `react` version: 16.2
- `typescript` version: 2.6.2

Relevant code:

https://github.com/paypal/glamorous/blob/0076e2676568911f0027c8f70634dfc17d697470/typings/component-factory.d.ts#L18-L21

and

https://github.com/paypal/glamorous/blob/0076e2676568911f0027c8f70634dfc17d697470/typings/component-factory.d.ts#L50-L55

What you did:

``` typescript
interface Props {
  clicked: boolean
}

const Comp = (props: Props) => null;

const x = glamorous.div<Props>(({ clicked }) => ({ color: clicked ? 'red' : 'blue' }));
const y = glamorous('div')<Props>(({ clicked }) => ({ color: clicked ? 'red' : 'blue' }));

x.withComponent(Comp);
y.withComponent(Comp);
```

What happened:

`y` makes an error.

Reproduction:

https://stackblitz.com/edit/glamorous-type-issue-00

Problem description:

Based on what I understand with glamorous document, `glamorous('HTML tag')` should be compatible with `glamorous.['HTML tag']`. However, in TS, it's not the case because  `KeyGlamorousComponentFactory` returns quite different type to `BuiltInGlamorousComponentFactory`.

Suggested solution:

Change `KeyGlamorousComponentFactory` to returns something like

```
GlamorousComponent<
    ElementProps & ExternalProps & Partial<DefaultProps> & Props,
    ExternalProps & Props,
>
```

As you can see in https://stackblitz.com/edit/glamorous-type-solution-00

P.S. I'm quite confused about what two type parameter of `GlamorousComponent<E, P>` means. Could you please clarify it for me? I believe @luke-john is who could explain this.....)

**Comment by Ailrun** [comment]
@luke-john If your time allows... could you please give an answer for above P.S.?

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
