### ISSUE TITLE
Custom glamorous component returned .withProps doesn't filter custom props

### ISSUE THREAD

**Issue by exah** [paypal/glamorous#364]
Hi! Thank you for amazing project. 

- `glamorous` version: 4.9.7
- `glamor` version: 2.20.40
- `react` version: 16.2.0

Relevant code.

```javascript
import glamorous from 'glamorous'
import { componentFromProp } from 'recompose'
import * as styles from './styles'

const TextBaseComponent = componentFromProp('component')

const Text = glamorous(TextBaseComponent, {
  rootEl: 'p',
  withProps: { component: 'p' },
  forwardProps: [ 'component' ]
})(
  styles.defaulTextStyle,
  styles.textStyles
)

const LeadText = Text.withProps({ lead: true })

<LeadText />
```

What you did:

Created custom glamorous component with `rootEl`, then returned new component using `.withProps`.

What happened:

```
Warning: Unknown prop `lead` on <p> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

Reproduction:

https://codesandbox.io/s/w7njowpk6l

Problem description:

I'm getting unexpected `Unknown prop  error` when using `.withProps` with custom component. 

Suggested solution:

Temporal solution is to replace custom component using `.withComponent`.

**Comment by kentcdodds** [comment]
Interesting! Thanks for sharing. [Here's the code responsible for splitting the props](https://github.com/paypal/glamorous/blob/cb6de3abe6b3a7e2643828f4239e0487d4f80455/src/split-props.js). The stuff that ends up in `toForward` is what gets applied to the underlying component.

My guess is that when you use `withProps`, we're not properly setting the `rootEl` to the new component when calling `withProps`:

https://github.com/paypal/glamorous/blob/cb6de3abe6b3a7e2643828f4239e0487d4f80455/src/create-glamorous.js#L127-L129

If you could dig a little further (add some breakpoints or `console.log`s in your app where you seeing this) that would be great! Thanks!

**Comment by marzelin** [comment]
> My guess is that when you use withProps, we're not properly setting the rootEl to the new component when calling withProps

exactly. We should take into account `comp.rootEl` when setting `rootEl` here:
https://github.com/paypal/glamorous/blob/cb6de3abe6b3a7e2643828f4239e0487d4f80455/src/create-glamorous.js#L199
