### ISSUE TITLE
Vector logos have incorrect file names.

### ISSUE THREAD

**Issue by knpwrs** [paypal/glamorous#366]
Unless I'm missing something it looks like `full.png` is rendered from `compact.ai` and `compact.png` is rendered from `full.ai`.

![glamorous-logo](https://user-images.githubusercontent.com/174864/34523586-218ea7fe-f066-11e7-97d7-7affbca4e642.gif)

**Comment by kentcdodds** [comment]
Haha, whoops! Feel free to open a pill request to rename them! 😅

**Comment by knpwrs** [comment]
I'm having really strange git issues. I'll open the PR as soon as I have it figured out.
