### ISSUE TITLE
hash function for css naming is very slow

### ISSUE THREAD

**Issue by blackswanny** [paypal/glamorous#373]
please, see
https://github.com/threepointone/glamor/issues/343

**Comment by kentcdodds** [comment]
There's nothing that we can do in glamorous about this. Closing in favor of the issue you linked. Thanks!

**Comment by blackswanny** [comment]
thanks for fast response. Do you know if glamor project is still live? Since november there is no issues addressed or answered

**Comment by kentcdodds** [comment]
I know that the original creator has kinda moved on to other things. I don't watch the repo so I don't have a pulse on how the other maintainers have been.

If you're really concerned about the performance though, you might want to give [emotion](https://emotion.sh/) a look.

**Comment by blackswanny** [comment]
@kentcdodds  thanks. They use the same strong , but slow hash method https://github.com/emotion-js/emotion/blob/master/packages/emotion-utils/src/hash.js
Will discuss it there
