### ISSUE TITLE
Components returned from `withComponent` use the wrong rootEl

### ISSUE THREAD

**Issue by tikotzky** [paypal/glamorous#376]
* `glamorous` version: 4.11.3
* `glamor` version: 2.20.40
* `react` version: 16.2.0

Relevant code.

```javascript
const A = glamorous.div({}).withComponent('a');

function Link() {
	<A href="https://www.google.com">href is missing 🙁</A>
}
```

What you did:
Tried to render an `a` tag with an `href` attribute

What happened:
It rendered an `a` tag without the `href` attribute

Reproduction:
https://codesandbox.io/s/vvzq1kwlw0

Problem description:
This broke in 4.11.3
Here is a codesandbox with the same code working on 4.11.2
https://codesandbox.io/s/3xr58oxqv6

Suggested solution:
Dont know the internals well enough 😄

**Comment by kentcdodds** [comment]
Hi @tikotzky!

Thanks for the issue. It probably broke when we merged and released #374 (cc @exah).

@tikotzky, do you think you could write a unit test to reproduce this issue? Probably in this file: https://github.com/paypal/glamorous/blob/master/src/__tests__/create-glamorous.with-component.js

If you feel so inclined to provide the fix as well that would be welcome :)

Thanks!

**Comment by tikotzky** [comment]
I already have a unit test which reproduces the issue :)
I'll open a PR in a few minutes.

I'll try to fix but its my first time peering under the hood at glamorous, so might take a few...

**Comment by kentcdodds** [comment]
Hopefully looking at #374 will give you some clues. Thanks!

**Comment by tikotzky** [comment]
I opened a PR with a failing test here https://github.com/paypal/glamorous/pull/377

After a little more testing it seems like the test passes on 4.11.2, and starts failing after
https://github.com/paypal/glamorous/commit/d9560fa6ac9afcdd214ce211f8533280beb7062c.

Judging from that it seems like a dep broke it.
I'll dig a little further to see if I can figure it out.

**Comment by kentcdodds** [comment]
Thanks!

**Comment by tikotzky** [comment]
The test seemed to be breaking due to a change in enzyme...
I fixed the test and have a fix...
Gonna update the PR soon.

**Comment by tikotzky** [comment]
Pr updated.

Thanks for the awesome lib 😄 👍

**Comment by kentcdodds** [comment]
Fixed!
