### ISSUE TITLE
Get access to Theme inside regular React components? (Typescript) 

### ISSUE THREAD

**Issue by seivan** [paypal/glamorous#380]
Is there a way to get access to theme from within a regular stateless React component that doesn't necessarily derive from Glamorous? 

I'm pretty sure I've missed something, I assume props is not the right way, but something along side getting it from the context, but I am not sure exactly how. 

* `glamorous` version: `glamorous@4.11.2`
* `glamor` version: `glamor@2.20.40`
* `react` version: `16.0.0`
* `typescript` version: `2.6.2`

//Pseudocode
```typescript
export interface MyTheme {
    theme: { color: string }
}

 class Badge extends React.PureComponent<{someRandomProps: string} & MyTheme> {
     render() {
         const { someRandomProps, theme, ...rest } = this.props
        //Do something with Theme. 
         return  (<InternalGlamorousButton type={"Button"}  {... someRandomProps} {...rest} />)
     }
 }
```

**Comment by Ailrun** [comment]
Hm... In my fool opinion, just wrapping it using `glamorous`? I mean, `glamorous(Badge)(...)` with adding `className` props to `Badge`.

**Comment by bjoernricks** [comment]
You can wrap you regular component within the [withTheme](https://github.com/paypal/glamorous/blob/master/src/with-theme.js#L12) HOC.
```jsx
let MyComponent = ({theme, ...props}) => (....)
MyComponent = withTheme(MyComponent);
```

**Comment by seivan** [comment]
@bjoernricks That helps silence the compiler and makes the typechecking, but I don't actually have any value inside theme even though the components are wrapped under `<Themeprovider theme={..}>`
