### ISSUE TITLE
Localization/Filipino translation

### ISSUE THREAD

**Issue by jcpuzs1** [paypal/glamorous#386]
Good day sir, I wwould like to contribute translation by localizing to Filipino dialect.

**Comment by kentcdodds** [comment]
That's terrific @jcpuzs1!

Please see the documentation on that in [the glamorous website repo](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md)

I'll go ahead and close this issue. Can't wait to see PRs for Filipino on the website repo!
