### ISSUE TITLE
Typescript: Generic type missing from withProps(fn)

### ISSUE THREAD

**Issue by epeli** [paypal/glamorous#389]
I'm trying to create an button component which can be disabled with an `inactive` prop. The prop should change the text color and set `disabled` prop the button.

* `glamorous` version: 4.11.6
* `glamor` version: 2.20.40
* `react` version: 16.2.0
* `typescript` version: 2.7.2

Relevant code.

```typescript
const MyButton = glamorous
    .button<{inactive: boolean}>(props => ({
        color: props.inactive ? "red" : "green",
    }))
    .withProps(props => ({
        disabled: Boolean(props.inactive),
    }));
```

Here the `withProps(props` will give implicit any error.

What you did:

What happened:

![image](https://user-images.githubusercontent.com/225712/36540299-7f4d95b4-17e2-11e8-8bd3-93fd16689da4.png)

Reproduction:

Sorry I cannot reproduce this on Stackblitz as it allows implicit any.

**Comment by quicksnap** [comment]
@epeli looks like you'll need to cast in the generics area same as with button:

`.withProps<MyProps>(props => ...)` 

TypeScript inference could be improved on this, maybe! But this should be a workaround for now.

**Comment by quicksnap** [comment]
Ah wait, I'm incorrect.. seems not to be the case. For now you'll have to cast it in the argument itself.

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
