### ISSUE TITLE
Allow nested functions for css prop

### ISSUE THREAD

**Issue by quicksnap** [paypal/glamorous#390]
Glamorous accepts an array for the `css` prop, which may contain nested arrays of styles. Those styles may be callback functions in order to access the theme:

`<Div css={ [myStyle1, myStyle2, ({ theme}) => myStyle3] } />`

We currently do not support recursion for the callback's results: https://github.com/paypal/glamorous/blob/d9560fa6ac9afcdd214ce211f8533280beb7062c/src/get-glamor-classname.js#L79-L86

Would you accept a PR to adjust this? I'm working to make styles functionally composeable, and it would be great if I could return an array with further callback functions!

**Comment by quicksnap** [comment]
Something like this: https://gist.github.com/quicksnap/c7607d49e2450a25d6208224bc83a668#file-glamorous-js-L13-L19

**Comment by kentcdodds** [comment]
I've thought about this before. I feel like we might be able to make it simpler. Would this work?

```js
function handleStyles(styles, props, context, mappedArgs = [], nonGlamorClassNames = []) {
  let current
  for (let i = 0; i < styles.length; i++) {
    current = styles[i]
    if (typeof current === 'function') {
      const result = current(props, context)
      handleStyles(current, props, context, mappedArgs, nonGlamorClassNames)
    } else if (typeof current === 'string') {
      const {glamorStyles, glamorlessClassName} = extractGlamorStyles(current)
      mappedArgs.push(...glamorStyles)
      nonGlamorClassNames.push(...glamorlessClassName)
    } else if (Array.isArray(current)) {
      const recursed = handleStyles(current, props, context)
      mappedArgs.push(...recursed.mappedArgs)
      nonGlamorClassNames.push(...recursed.nonGlamorClassNames)
    } else {
      mappedArgs.push(current)
    }
  }
  return {mappedArgs, nonGlamorClassNames}
}
```

**Comment by quicksnap** [comment]
Nice! I suppose that means you're receptive to this idea? =P

I'll drum up a PR soon and use that approach
