### ISSUE TITLE
StyleFunction typings need updating for nested functions

### ISSUE THREAD

**Issue by quicksnap** [paypal/glamorous#394]
See https://github.com/paypal/glamorous/pull/392#pullrequestreview-100970256 for more details.

**Comment by Powell-v2** [comment]
I'd like to help with this one if that's alright.

**Comment by quicksnap** [comment]
Go for it! Appreciate the help!

**Comment by Powell-v2** [comment]
Is there anything else to update apart from `StyleFunction` interface as proposed by _luke-john_?

```
export interface StyleFunction<Properties, Props> {
  (props: Props):
    | Properties
    | string
    | Array<Properties | string | StyleFunction<Properties, Props>>
    | StyleFunction<Properties, Props>
}
```

**Comment by luke-john** [comment]
@Powell-v2 adding that would be great and would cover the scope of this issue 👍.

Revisiting this though, I think props should be optional optional on `StyleFunction` `(props?: Props):`.

**Comment by Powell-v2** [comment]
I made `props` optional and , as a result, one of the snapshot tests fails. Should I just update the snapshot and proceed?

**Comment by quicksnap** [comment]
Somewhat unrelated, these recent type updates cause some issues when TypeScript is unable to infer the type `CSSProperties`. For example:

```ts
const myStyle = { display: 'none' };
<Div css={myStyle} /> // Type error!
```

Users need to cast:

```ts
const myStyle: CSSProperties = { display: 'none' }
<Div css={myStyle} /> // Works fine
```

The reason is that `display` is typed to explicit constants, but the type of that object without casting is `type: { display: string }`, which isn't compatible with `display: 'none' | 'initial' | ...`

In my fork of Glamorous, I changed this type to accept `{}` type:

```ts
export type CSSPropertiesRecursive =
  | CSSProperties
  | CSSPropertiesArray
  | CSSFunction
  | {}
```

We may want make this change upstream for ease of use.

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
