### ISSUE TITLE
Generate functional class names

### ISSUE THREAD

**Issue by souporserious** [paypal/glamorous#40]
First off, thank you for this lib! I've really enjoyed using it. I was wondering if you would be interested in allowing an option to generate functional class names instead of unique class names? Similar to what [CXS](https://github.com/jxnblk/cxs) does. I'd be willing to try out a PR :) just let me know.

**Comment by kentcdodds** [comment]
Hey @souporserious! This is actually an issue for [glamor](https://github.com/threepointone/glamor). glamorous doesn't actually have anything to do with the generated class names. Mind filing an issue over there?

I'm glad that you've enjoyed using the lib!

**Comment by souporserious** [comment]
Will do! Thanks!
