### ISSUE TITLE
overflowStyle not applied in IE 11

### ISSUE THREAD

**Issue by screendriver** [paypal/glamorous#400]
* `glamorous` version: 4.12.1
* `glamor` version: 2.20.40
* `react` version: 16.2.0
* `typescript` version: 2.7.2

Relevant code.

```javascript
const MyComponent = glamorous.div({
  overflowStyle: 'none',
  '-ms-overflow-style': 'none',
});
```

What you did:

I want to apply the styles written above. But unfortunately `overflowStyle` will not be applied in IE 11. Instead I have to write manually `'-ms-overflow-style': 'none'` (as you can see in the last line). Shouldn't browser prefixes be done automatically in glamorous or glamor?

What happened:

When I just write `overflowStyle: 'none'` without ` '-ms-overflow-style': 'none'` then nothing will be applied in IE 11. In Chrome conversely I can see a `overflow-style: 'none'` (with a warning that this property is not supported, but that's ok here)

**Comment by kentcdodds** [comment]
Hi @screendriver,

Yes, glamor should be auto-prefixing. That's done by this project: https://github.com/rofrischmann/inline-style-prefixer

So could you file this issue over there please? Thanks!

**Comment by screendriver** [comment]
Ok. Thank you for the quick response 👍
