### ISSUE TITLE
Use csstype

### ISSUE THREAD

**Issue by pelotom** [paypal/glamorous#408]
[`csstype`](https://github.com/frenic/csstype) is a set of standard, high-quality CSS typings generated from MDN data. It is now being used by the React and JSS typings. It would be great to have the entire CSS-in-JS ecosystem standardize on these typings rather than each project maintaining its own pet CSS typings, each with varying degrees of completeness and usually inconsistent with one another!

**Comment by kentcdodds** [comment]
Seems very cool!
