### ISSUE TITLE
withTheme() HoC for theming normal components

### ISSUE THREAD

**Issue by vesparny** [paypal/glamorous#41]
As discussed with @kwelch in #24 we might want to provide a `withTheme()` HoC that allows using theming capabilities with non-glamorous components.

```jsx
import {withTheme} from 'glamorous'

const Hello = ({theme, ...rest}) =>
  <div style={{color: theme.colors.primary}} {...rest} /> 

export default withTheme(Hello)
```

`withTheme()` will just receive the context, setup subscription and return the wrapped component with a `theme` prop.

Am I correct @kwelch ?

**Comment by kentcdodds** [comment]
Looks good to me!

**Comment by kwelch** [comment]
Yes, this should isolate context to within the library so users don't have to use an experimental API (knowingly).

**Comment by vesparny** [comment]
Is anyone willing to take this one? Otherwise I can do it.

**Comment by kentcdodds** [comment]
Let's wait a day or so to see whether anyone else wants to do it. Unless you need it now if course. The more the merrier!

**Comment by kkemple** [comment]
I would love to jump on this, been working with HOCs a lot lately.

**Comment by kentcdodds** [comment]
Awesome! 👍

**Comment by kkemple** [comment]
@kentcdodds sent a PR, mostly there but there are some questions that need answering before its ready to go! :smile:
