### ISSUE TITLE
Doesn't forward `playsInline` prop to `<video>` components

### ISSUE THREAD

**Issue by dylanpyle** [paypal/glamorous#412]
Using:

```
"glamor": "2.20.40",
"glamorous": "4.12.3",
"react": "16.3.2",
```

Relevant code.

```javascript
const Video = glamorous.video();
render(<Video playsInline />, el);
```

Actual result:

```jsx
<video class="css-glamorous-video--irvhhv"></video>
```

Expected result: 
```jsx
<video class="css-glamorous-video--irvhhv" playsinline></video>
```

https://codesandbox.io/s/8k2wx5p3m0

---

Assuming this is a whitelist in the code somewhere, I'll try to follow up with a PR shortly.

**Comment by kentcdodds** [comment]
The problem is if we forward all the props then we could send props to dom nodes that don't actually belong there and can cause some issues (and React will warn against it, resulting in many console log statements).

**Comment by kentcdodds** [comment]
Glad you got it fixed!

**Comment by dylanpyle** [comment]
Yeah, interesting — I guess I figured that was more of the user's responsibility to avoid, but I see how it's a potential footgun.

This issue is fixed upstream, but looks like the NPM distribution of glamorous uses `dist/glamorous.cjs.js` as the entry point, so I don't think it'll be fixed on NPM until you republish. Not sure how your usual release cycle works, so feel free to close this issue whenever.

**Comment by kentcdodds** [comment]
Ah, yes, that's correct. I can fix that right now.
