### ISSUE TITLE
Change ref to use forwardRef (to return the reference of inner element)

### ISSUE THREAD

**Issue by Ailrun** [paypal/glamorous#418]
* `glamorous` version: 4.12.5
* `glamor` version: 2.20.40
* `react` version: 16.3

Relevant code.

```javascript
const StyledButton = glamorous.button({
  background: 'blue',
});

class Wrapper extends React.Component {
  constructor() {
    this.buttonRef = React.createRef();
  }

  render() {
    return (
      <StyledButton ref={this.buttonRef} />
    );
  }
}
```

What you did:
Try to get a innerRef

What happened:
ref returns an element from glamorous component, instead of React DOM element.

Problem description:
React 16.3 supports `forwardRef` for forwarding reference of inner element. As @kentcdodds mentioned, most of time people try to get a innerRef instead of glamorous ref.
#243 is close because of lack of support from React, however, now React supports it.

Suggested solution:
Change current `ref` into `glamRef` (or `glamorousRef`, ...) and forward `innerRef` as `ref`.
However, it looks like this change makes problematic breaking change, maybe fixing this during major version update is better choice...

**Comment by danielberndt** [comment]
> However, it looks like this change makes problematic breaking change, maybe fixing this during major version update is better choice...

Or even nicer: introduce the new behaviour while still maintaining the old `innerRef` with a deprecation notice.

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
