### ISSUE TITLE
Deprecate glamorous 💄 in favor of emotion 👩‍🎤

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#419]
For a long time now I've been considering deprecating glamorous (NOT glamorous-native) in favor of [emotion](https://emotion.sh/).

**Here's my reasoning**:

1. Emotion can do everything glamorous can do
2. Emotion can do more than glamorous can do
3. Emotion is faster than glamorous
4. Emotion is smaller than glamorous
5. It's good for the community to consolidate and rally around using and improving a single solution

I would not recommend people spend a bunch of time migrating to emotion. glamorous isn't bad, it's just not as good as emotion and I don't think it would be worth the effort to manually migrate. That said, I'm fairly confident that a codemod could be written to automatically migrate your glamorous code to emotion.

**What a deprecation would mean**:

- I would add a notice to the README and website indicating that this project is no longer maintained and encouraging people to use emotion instead.

**What a deprecation would NOT mean**:

- glamorous-native is still the best-in-class for styling native applications and is entirely separate from glamorous. It would NOT be deprecated. It is an entirely separate project with no shared dependencies anyway, so a deprecation of glamorous wouldn't impact glamorous-native directly.

**What I want from you**:

Please give this a :+1: if you agree or a :-1: if you disagree.

**If you disagree, please list reasons why and whether you would be willing to assume the maintainer role.**

Thanks friends!

**Comment by kentcdodds** [comment]
Things are looking very positive for this. If someone would like to help a LOT of people here are a few things you could do:

1. Write a migration guide. It could be a simple markdown file [here](https://github.com/paypal/glamorous/tree/master/other).
2. Write a codemod. If you don't have any experience with ASTs then this might be a bit of a challenge for you. I have some resources for you though:

* [Writing custom Babel and ESLint plugins with ASTs](https://youtu.be/VBscbcm2Mok?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf): A 53 minute talk by [@kentcdodds](https://twitter.com/kentcdodds)
* [babel-handbook](https://github.com/thejameskyle/babel-handbook): A guided handbook on how to use Babel and how to create plugins for Babel by [@thejameskyle](https://twitter.com/thejameskyle)
* [Code Transformation and Linting](https://kentcdodds.com/workshops/#code-transformation-and-linting): A workshop (recording available on Frontend Masters) with exercises of making custom Babel and ESLint plugins

A good starting point for the codemod could be the one I wrote for upgrading people's version of glamorous due to the theme breaking change we had a few months ago: https://github.com/paypal/glamorous/blob/master/other/codemods/theme-move.js

I don't think that I'll have time to do either of these things any time soon, but I'd love it if anyone would like to pitch in to do it :)

I'm 99% certain that we'll be doing this.

**Comment by morajabi** [comment]
I can think of one concern, this move can confuse people (like some already asked) and raise this question that what would happen to glamorous-native again and again. Adding a notice mentioning "This is actively maintained" or something like that in that project's readme would be helpful.

**Comment by Ailrun** [comment]
One thing that can (probably) confuse people is TS support. Emotion's TS support is quite immature compared with Glamorous. It does almost nothing with CSS typing, does not have proper plugin type, ...

**Comment by kentcdodds** [comment]
@Ailrun, that is a very valid concern and I'm sure it would be frustrating for folks like you and others who have poured a TON of effort into making glamorous as great as it is with regards to TypeScript. Hopefully by switching to emotion we can combine efforts with other folks to take the things we've learned from glamorous to improve the Typings in emotion.

**Comment by Ailrun** [comment]
@kentcdodds Hm... then, I should spend some time on emotion typing to move there safely. Thank you for kind comment.

**Comment by quicksnap** [comment]
Does anyone have a react+emotion demo repo/codepen or something I could test a few things with? 

My primary use case with Glamorous has been css-object composition+ThemeProvider--nested arrays of objects or functions-returning-objects. I'd like to validate that emotion can work with some of those patterns.

Soon enough I'll test it out, but if there's already a codesandbox or something I could test things very quickly.

@kentcdodds You're making a very awesome decision to rally around a single solution. Love the direction here.

**Comment by brentertz** [comment]
@kentcdodds Emotion does not seem to have any notion of prop filtering, and the associated API's `rootEl`, `filterProps`, `forwardProps`, like Glamorous does.  Was this a difficult thing to maintain in Glamorous?  Any thoughts on how to approach if migrating to Emotion?  The library that I work on relies on it pretty heavily at present.

**Comment by kentcdodds** [comment]
Interesting. Could you file an issue on emotion @brentertz? Let's see if this is something they'd be willing to implement. Either that or we could implement a small layer on top of emotion that could do this.

**Comment by Andarist** [comment]
@quicksnap 
> My primary use case with Glamorous has been css-object composition+ThemeProvider--nested arrays of objects or functions-returning-objects. I'd like to validate that emotion can work with some of those patterns.

Emotion should handle all that jazz just fine. We use it on production and receiving serializable theme objects through the wire + ofc we use some local functions etc to style based on props.

**Comment by Andarist** [comment]
In `emotion` this can be achieved by using custom helpers or libraries like [`styled-system`](https://github.com/jxnblk/styled-system)

**Comment by bjoernricks** [comment]
From #421 
> Object Syntax If moving to emotion you will need their babel-plugin-emotion
Is that true? In that case moving from glamorous to emotion is a no go for me and users of create-react-app who like to still use the object notation.

**Comment by Andarist** [comment]
@bjoernricks that's not true, emotion handles object syntax without babel's help

**Comment by ctrlplusb** [comment]
@bjoernricks the babel plugin is only needed if you want a similar API to glamorous.

Without babel plugin:

```js
import styled from 'react-emotion'

const Foo = styled('div')({
  position: 'relative'
})
```

With babel plugin:

```js
import styled from 'react-emotion'

const Foo = styled.div({
  position: 'relative'
})
```

So whilst the plugin isn't required, it certainly makes the migration easier.

**Comment by Andarist** [comment]
Also there is a plan to support `styled.div` style without a babel plugin in upcoming emotion@10, but it's still recommended to use babel plugin nevertheless to downsize production bundles.

**Comment by danielberndt** [comment]
fyi: v2 of `create-react-app` supports babel-macros. This means that you can use (`'emotion/macro'`)[https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion#babel-macros] without having to eject.
Macros seem to support all features that `babel-plugin-emotion` support except for optimising the css-prop.

**Comment by dragosbulugean** [comment]
Two things that emotion doesn't are exactly the things that I used glamorous for: 

- being able to inline styles like this (lets you not give anything a name if you don't reuse it):
```js
<Div width={100} height={100}>
 <H1 backgroundColor="green">Hello</H1>
</Div>
```
- if you used TypeScript these props would be type-checked at compile time.

So, not really feeling 'emotion is better than glamorous'.
I will probably continue to use it.

**Comment by VinSpee** [comment]
@dragosbulugean I started migrating and found

```jsx
<div
  css={{
    width: 100,
    height: 100,
  }}
>
  <h1
    css={{
      backgroundColor: 'green',
    }}
  >
    Hello
  </h1>
</div>
```

to be a suitable alternative. I even like it a bit more.

**Comment by kentcdodds** [comment]
In addition, the `css` prop is actually _more_ powerful because you can use media queries and such, so I haven't used the named css props for a long time. On top of that, when you use the built-in components with glamorous, you're putting that code on the slow path. It's fast enough to not be a problem most of the time, but it's definitely the slowest way to use glamorous. That's not the case with emotion. They've done some amazing work to make it super fast.

**Comment by Ailrun** [comment]
Can we use emotion with an
Y type of css lint? In glamorous, as far as I know, we can use stylelint. But I cannot find any related tools for css linting working with emotion.

**Comment by kentcdodds** [comment]
I don't think there'd be anything to preclude us from adding that functionality if it doesn't already exist. They're very similar libraries. Whatever tooling you're using for glamorous could probably be retrofitted to work with emotion fairly easily.

**Comment by dragosbulugean** [comment]
@VinSpee yes but create-react-app is not there yet :(. Plus I just checked that the css object doesn't get type-checked.
@kentcdodds I understand :(
Pretty unhappy, but this is the OSS world.

**Comment by kentcdodds** [comment]
As I said @dragosbulugean:

> If you disagree, please list reasons why and whether you would be willing to assume the maintainer role.

**Comment by VinSpee** [comment]
@dragosbulugean emotion comes with a babel macro, which create-react-app is onboard with! https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion#babel-macros

**Comment by JeffersonFilho** [comment]
I love glamorous and I have already started migrating some stuff to it on our current project some months ago, but looks like now I will have to migrate to something different.

My only concerned and question is: Why emotion instead of styled-components? 

I'm just bit concerned that emotion might have the same fate as glamorous did.

**Comment by Ailrun** [comment]
@JeffersonFilho
First, styled-component does not support object style syntax.
Second, styled-component is even slower than glamorous, as far as I know.

**Comment by kentcdodds** [comment]
Actually, as of very recently, styled-components now actually supports objects, it's also made leaps and bounds with regard to performance, though it's still not as fast as emotion. I'm pretty certain that emotion is still more capable though, so I still recommend emotion over styled-components personally. I don't think that you'll go wrong either way though.

Again, you can't really go wrong by not migrating at all. It's not like glamorous suddenly got an infusion of bugs or performance problems. You can keep using and loving it for all the same reasons you use and love it today. I just wouldn't recommend starting a new project with it.

Eventually we can hopefully create a codemod to migrate your code to emotion automatically. The folks who maintain storybook were big users of glamorous and have manually migrated to emotion saying that the effort was "minimal." So you might try to take an hour of your time to manually migrate and see if you can do the same. I probably wouldn't spend more than an hour on it though.

**Comment by Ailrun** [comment]
@kentcdodds Oh, thank you for correcting me! I should check and send some PR to benchmark repos!

**Comment by kentcdodds** [comment]
Thank you @Ailrun! I think this is wonderful that we can combine forces and make our chosen solution even better!

**Comment by kentcdodds** [comment]
With the overwhelming :+1: over :-1:, I've added a message to the top of the README. I'll try to get a message on the website as well.

**Comment by quicksnap** [comment]
Glamorous has been and still is an amazing library! I love the maturity around this decision. Thanks for everything @kentcdodds and everyone else behind this library!

**Comment by knpwrs** [comment]
> Glamorous has been and still is an amazing library! I love the maturity around this decision.

You might even say that this decision shows _emotion_al maturity. ☜(ﾟヮﾟ☜)

I'll show myself out.

**Comment by RoystonS** [comment]
Has anybody started a list of what's in glamorous that has no equivalent in emotion yet?  It would be helpful for planning a migration (we have >100 components that were styled with glamorous). I can't see `withProps` there, for instance.

**Comment by Ailrun** [comment]
@RoystonS
I wish this document could help you.
https://github.com/emotion-js/emotion/blob/master/docs/with-props.md

**Comment by RoystonS** [comment]
@Ailrun Ah, of course - I forgot about that. We previously tried to use that with glamorous but it didn't play nicely, so had to switch to glamorous' own `withProps`.  Thanks!

**Comment by Andarist** [comment]
Using `defaultProps` should accommodate for most use cases too.

**Comment by cheapsteak** [comment]
defaultProps is sufficient, is you prefer, recompose's withProps also works

**Comment by gucong3000** [comment]
> But I cannot find any related tools for css linting working with emotion.

Try this:
https://github.com/gucong3000/postcss-jsx

```bash
npm i stylelint postcss-jsx --save-dev
stylelint **/*.{js,css}
```

**Comment by Ailrun** [comment]
@gucong3000 Actually I'm currently working on stylelint plugin for emotion...

**Comment by gucong3000** [comment]
@Ailrun This is exactly what you are looking for.
`postcss-jsx` is what I developed specifically for `stylelint` & `postcss`.

**Comment by gucong3000** [comment]
https://github.com/emotion-js/emotion/issues/686

**Comment by antoniobrandao** [comment]
Omg, this is such bad news. I much rather write CSS inside JS using the JS syntax

    textAlign

not 

    text-align

I also much prefer `not` using  these ```` around my code... I don't care if emotion is "faster", `glamorous` is perfectly fast enough for us!

Please don't kill this project! Is anyone volunteering to maintain glamorous?

**Comment by VinSpee** [comment]
@antoniobrandao you must not have looked closely. Emotion fully supports js objects as you described. It's the syntax I use and prefer too, so that was important to me!

**Comment by knpwrs** [comment]
> I much rather write CSS inside JS using the JS syntax

To echo @VinSpee: https://emotion.sh/docs/object-styles

**Comment by antoniobrandao** [comment]
Thanks @VinSpee, didn't know and it's great to know! 👍

But it gives me more work to achieve the same result... 

If I install just the `glamorous` NPM package I can write like this:

    import glamorous from 'glamorous'
    const H2 = glamorous.h2({
        fontSize: '44px'
    })

To use it like

    <H2>Some text<H2>

To be able to do this in `emotion` I have to use `react-emotion`, which in turn requires that I install `babel-plugin-emotion`.

Then I can do this:

    import styled from 'react-emotion'
    const H2 = styled.h2({
        fontSize: '44px'
    })
    // and use like
    <H2>Some text<H2>

Yarn didn't install `emotion` automatically when I installed `react-emotion` by the way. Had to install it separately.

So in total I need to install:

`emotion`
`react-emotion`
`babel-plugin-emotion`
And I have to add `emotion` to the `.babelrc` file

Isn't it a lot to install / config for something I can achieve with a single `glamorous` NPM module installation?

**Comment by knpwrs** [comment]
@antoniobrandao The babel plugin is optional, as it appears you are aware. It enables the `styled.div` syntax so you don't have to use `styled('div')`. Using the latter is a simple find and replace across your project.

Having to install `emotion` and `react-emotion` is no different from having to install `glamor` and `glamorous`. `react-emotion` even exports everything that `emotion` exports so you have direct access to those exports without having to fuss with packages.

**Comment by knpwrs** [comment]
@antoniobrandao `react-emotion` declares `emotion` as a peer dependency and `glamorous` declares `glamor` as a peer dependency. `glamorous` does _not_ automatically install `glamor`. I just installed `glamorous` in an empty project and got the following warning:

```
npm WARN glamorous@4.13.1 requires a peer of glamor@>=2 but none is installed. You must install peer dependencies yourself. 
```

And the following `node_modules` tree (no `node_modules` under glamorous` either):

```
node_modules
├── brcast
├── csstype
├── fast-memoize
├── glamorous
├── html-element-attributes
├── html-tag-names
├── is-function
├── is-plain-object
├── isobject
├── react-html-attributes
└── svg-tag-names

11 directories, 0 files
```

I can't help the character difference. It leads to a smaller package size which is why glamorous ships a "tiny" version which is more similar to emotion: https://glamorous.rocks/advanced/#optimizing-bundle-size

**Comment by antoniobrandao** [comment]
@knpwrs sorry I must have remembered incorrectly. I just realised, I don't even use `glamor`. Removed `glamor` from my (large) project and with `glamorous` alone it still compiles and works, using the simpler dot syntax. Package size optimisation is nice, but not always that important, and it's also nice to have a less verbose syntax (for some people at least). It's really a matter of syntax flavour and simplicity. I really like the syntax that `glamorous` offers out of-the-box, even without `glamor`. Just wanted to put it out there - Not to argue the design choices made with `emotion` which are perfectly sensible. I already knew `emotion` and it looked great to me, just didn't migrate because of the different default syntax. It's nice to know `emotion` can do the same even if with a little more setup, so thanks for your clarifications.

**Comment by kentcdodds** [comment]
It would be fairly trivial to publish and maintain another package that depends on emotion and react-emotion and exposes the type of API you're looking for. But that's not important to me specifically so I won't personally be working on it.

**Comment by Andarist** [comment]
Keep also in mind that having all of those `.div`, `.h1` etc costs u bytes shipped over the wire. It's actually preferable to use `styled('div')` etc - but that can ofc be compiled with babel plugin which is super nice, because you have great DX & less bytes shipped to production.

**Comment by Ailrun** [comment]
@kentcdodds One of the hard things to move is class names.
In glamorous, we can use something like
```
const StyledButton = glamorous.button('awesome-library-class', (props) => `${props.country}-style`, {
  //... other styles
});
```
However, in emotion, we cannot use something like
```
const StyledButton = styled('button')('awesome-library-class', (props) => `${props.country}-style`, {
  //... other styles
});
```
but something like
```
const StyledButton = styled('button', {
  target: ['awesome-library-class'],
})({
  //... other styles
});
```
and no ways to port `(props) => ...`.
Or there is a way and I just don't know it?

**Comment by kentcdodds** [comment]
Huh, that's odd. I thought that was possible. @tkh44, could you speak to this? Any reason that providing a string isn't possible as described above? Would a PR be accepted to support this? It's a pretty handy feature.

**Comment by Andarist** [comment]
@Ailrun could u illustrate both with runnable example? Is `awesome-library-class` a problem here?

**Comment by Ailrun** [comment]
1. https://github.com/emotion-js/emotion/blob/21c3308ee6764a04a267ff07e5890a6626603c15/packages/create-emotion-styled/src/index.js#L65
    - When users call `styled(...)(/* second call parameters */)`, `/* second call parameters */` are just pushed to `styles`
2. https://github.com/emotion-js/emotion/blob/21c3308ee6764a04a267ff07e5890a6626603c15/packages/create-emotion-styled/src/index.js#L119-L122
    - `styles` passed to `emotion.css`
3. https://github.com/emotion-js/emotion/blob/21c3308ee6764a04a267ff07e5890a6626603c15/packages/create-emotion/src/index.js#L285
    - and `emotion.css` creates a single selector (or rather, css class), not css classes.

**Comment by Ailrun** [comment]
@Andarist Here it is. `'awesome-library-class'` is just some static class.
https://codesandbox.io/s/9q191nkxpp

**Comment by Ailrun** [comment]
Sorry, this one is correct one.
https://codesandbox.io/s/yq1w2vkj1

**Comment by Andarist** [comment]
Got it, aint sure what it would take to support it because emotion supports both tagged template literals & objects syntax this might be somewhat ambiguous - at least when talking about glamorous-like API.

**Comment by TejasQ** [comment]
Hi y'all! I have [thoroughly enjoyed](https://twitter.com/TejasKumar_/status/893194684427902976) glamorous for the past almost-year or so. I'm sad to see it deprecated in favor of emotion.

Still, I've got a large codebase that depends on it that we've built for months that I needed to migrate over, and so [I've written a codemod](https://github.com/TejasQ/babel-plugin-glamorous-to-emotion) here for everyone who may have a similar situation.

Thanks again for your great work on this library, @kentcdodds!

**Comment by kentcdodds** [comment]
This is fantastic! Thank you for your help! Would you be willing to accept contributions to improve it? For example, I think it'd be great to have an option to assume the babel-plugin-emotion will be used so that `styled.div` and the `css` prop work. What do you think?

**Comment by TejasQ** [comment]
For sure. All contributions welcome!

**Comment by melbourne2991** [comment]
I can't see the capitalized html components available in glamorous in emotion's docs eg: `<Div paddingTop="10px"/>`. It's easy enough to fix but it means a simple find replace won't cut it if you're using these extensively.

**Comment by TejasQ** [comment]
My codemod will replace `glamorous.Div`s to `<div>`s. Can I update it to help your use case, @melbourne2991?

**Comment by ctrlplusb** [comment]
Upgraded a pretty huge side project of mine (approx a year worth of dev on it) within an hour. Pretty decent! Huge thanks to @TejasQ for the codemod. ⭐️

**Comment by TejasQ** [comment]
@ctrlplusb awesome to hear it! Glad I could help! I hope your project flourishes!

**Comment by danielberndt** [comment]
I just migrated quite a big project using a lot of glamorous features to emotion. I'm almost done, and it took me about a day of work.

Notable things the codemod does not support (yet):
- wont work with "glamorous.macro" (should be easy to fix)
- won't work if you do imports like `import g from "glamorous"` the codemod expects `import glamorous from "glamorous"``
- you manually need to convert code like `<glamorous.div marginTop={5}/>` to `<div css={{marginTop: 5}}/>`
- no automatic translation from `filterProps/forwardProps` to `shouldForwardProps` (the latter expects a function), most other options (e.g. `withProps`) are also not directly translatable
- `forwardProps: ["innerRef"]` does not work with emotion 
- global styles and keyframes can't be automatically translated yet either
- won't work with `create-react-app` out of the box, but [react-app-rewire-emotion](https://github.com/osdevisnot/react-app-rewire-contrib/tree/master/packages/react-app-rewire-emotion) makes it fairly straight forward without the need to eject.

**Comment by TejasQ** [comment]
Wow! Thanks so much @danielberndt! Would you be interested to implement these features in the codemod together?

**Comment by danielberndt** [comment]
@TejasQ this would be quite a nice opportunity for me to dig into AST-transformations which I've never done before. :) 
But I can't promise anything since my schedule is quite full at the moment.

**Comment by TejasQ** [comment]
No worries whatsoever. The easiest thing would probably be working with generic default import specifiers (number 2 on your list). Shall I reserve that for you?

I could even just submit PRs that you review and could use for learning.

What would you prefer?

**Comment by danielberndt** [comment]
Ah, how nice! Yes, if you have the time, feel free to go ahead and implement it yourself. I'd be very happy to learn from your changes 👍

**Comment by TejasQ** [comment]
I don't really have the time, but I'll make the time for you. <3

**Comment by antoniobrandao** [comment]
@danielberndt does the standard `ref` work ?

**Comment by danielberndt** [comment]
@antoniobrandao both `innerRef` and `ref` work the same way in glamorous and emotion. I was referring to a very niche feature that was introduced [here](https://github.com/paypal/glamorous/issues/349):

If you want to avoid glamorous to apply the `innerRef` mechanism and instead just forward that prop to the underlying Component (e.g. use react-routers own `<Link innerRef={handler}/>` you could just do 
```jsx
const StyledLink = glamourous(Link, {forwardProps: ["innerRef"]})({...styles})
```
This feature is not supported by emotion and instead you need to do something like:

```jsx
const MyLink = ({myInnerRef, ...rest}) => <Link innerRef={myInnerRef} {...rest}/>
const StyledLink = emotion(MyLink)({...styles})

// use it like this
<StyledLink myInnerRef={handlerReceivingTheATag}/>
```

**Comment by antoniobrandao** [comment]
@danielberndt thanks man

**Comment by antoniobrandao** [comment]
How does this work in Emotion with object styles? Can't find it in the docs.

Glamorous way to make a element that is blue by default, be red when it has a certain class:

    const SomeDiv = styled.div({
      color: 'blue',
      ['.someClass']: {
        color: 'red',
      }
    })

**Comment by VinSpee** [comment]
@antoniobrandao:

```js
const SomeDiv = styled.div({
  color: 'blue',
  ['&.someClass']: {
    color: 'red',
  }
})
```

**Comment by antoniobrandao** [comment]
Thanks @VinSpee 🙏

**Comment by tkh44** [comment]
Thanks @VinSpee. FWIW you do not need the `[ ]` around the selector @antoniobrandao.

**Comment by syberen** [comment]
Does anyone have guidelines for migrating from glamorous to styled-components? Having a lot of trouble getting it to work properly.

**Comment by TejasQ** [comment]
@syberen is there a reason you've chosen to migrate from glamorous to styled-components instead of to emotion? 🤔

**Comment by syberen** [comment]
@TejasQ We're researching both options, but styled-components does seem to have a larger community and I've gotten some reports of buggy behavior from emotion from fellow developers, although I don't know the details.

**Comment by Andarist** [comment]
> @TejasQ We're researching both options, but styled-components does seem to have a larger community and I've gotten some reports of buggy behavior from emotion from fellow developers, although I don't know the details.

Not sure where did that come from, but we barely receive any bug reports for emotion and even if there are bugs reported they are fixed pretty quickly.

**Comment by danielberndt** [comment]
Hello people!
I've taken some time to rewrite a big chunk of the [codemod](https://github.com/TejasQ/babel-plugin-glamorous-to-emotion).
It's now in a much more solid state, and tackles most of my points above. 

I'm most excited about all the transforms around the `<glamorous.Div>` syntax. Here some examples:

```jsx
import g from "glamorous";

<g.Div marginTop={5}/>
// transformed to ↓
<div css={{marginTop: 5}}/>

<g.Div marginTop={5} css={{marginTop: 10}} marginBottom="5" onClick={handler}/>
// transformed to ↓
<div onClick={handler} css={{
  marginTop: 10,
  marginTop: 5,
  marginBottom: "5"
}} />

<g.Img width={100}/>
// transformed to ↓
<img width={100} />

<g.Span width={100}/>
// transformed to ↓
<span css={{width: 100}} />

<g.Span css={redStyles} marginLeft={5}/>
// transformed to ↓
<span css={{ ...redStyles, marginLeft: 5}} />
```

There's also an `withBabelPlugin` option, allowing you to decide what kind of emotion setup you want to support.

Thanks a lot to @TejasQ for the helpful code reviews! The code is in quite a readable state, should you be curious about babel-transforms :)

**Comment by kentcdodds** [comment]
That's fantastic @danielberndt! Thank you and @TejasQ for all your work on that :clap: :clap: :clap: :clap: :clap: :clap:

**Comment by kentcdodds** [comment]
I just published glamorous@5 and deprecated it so people installing latest will now get a deprecation message. (This means that existing projects using 4.x will not see a deprecation message, only people installing glamorous for the first time). I will also be archiving this repository in the next few days. https://glamorous.rocks will remain untouched for the foreseeable future (though the repo https://github.com/kentcdodds/glamorous-website will be archived as well).

![image](https://user-images.githubusercontent.com/1500684/49609080-be997880-f957-11e8-9c2e-b4d976aaae84.png)

I would like to give a special thank you to everyone who helped make this project what it was and inspired other projects to be built and enhanced pushing the css-in-js coding style forward. It was an awesome run. Thanks everyone who helped make the transition as smooth as possible.

I love you all <3

**Comment by TejasQ** [comment]
Love you too Kent 💞
