### ISSUE TITLE
Make glamorous smaller

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#42]
Because as @philpl [put it](https://twitter.com/_philpl/status/851639879628988422):

> SC v2 will be 11kb gzip, 32kb raw - although lower with preprocessing. @kentcdodds let the bytes war begin 😂

So here are a few ideas on the top of my head:

1. A lot of the size comes from the list of html attributes and element tag names. I'm not sure how SC is dealing with this but we may be able to learn from it. We could potentially make a build that skips the element tag names altogether and people could just do: `glamorous('div')({/* styles */})` on their own. It's mostly a convenience anyway... But I'm pretty sure I'd rather not do this... Other ideas? Maybe we could generate them at runtime somehow?
2. We added quite a bit with the `ThemeProvider` and not everyone needs to support theming. So we _could_ make a build that excludes the `ThemeProvider` related code 🤔 Things could get pretty messy though!
3. Anything else? Someone wanna peruse the code and see where we could shave some bytes?

**Comment by threepointone** [comment]
I notice you're missing an es6 'module' build? so consumers can DCE efficiently.

**Comment by threepointone** [comment]
(I'm doing the same for glamor)

**Comment by kentcdodds** [comment]
Thanks for looking into it. We actually do have one: https://unpkg.com/glamorous@3.1.0/dist/glamorous.es.js :tada:

**Comment by kentcdodds** [comment]
Also, I freaking LOVE rollup. Everytime I open up the rollup built file and see that it's totally flat I cheer: "Thank you @Rich-Harris" 👏

**Comment by Rich-Harris** [comment]
you're welcome 😀

**Comment by vesparny** [comment]
@kentcdodds 

I tried removing the html attributes list from glamorous.
The final build is 5.18kb gzipped (1kb less than actual one)

Obviously the only way to use glamorous will be, as you said:

```js
import glamorous from 'glamorous'

glamorous('a')({
  color: 'red'
})
```


Another possible solution would be

```js
function glamorous (comp, {rootEl, displayName} = {}) {
  .....
  ....
  // return glamorousComponentFactory
}

const handler = {
  get: (target, name) => glamorous.bind(null, name)
}

const proxiedGlamorous = new Proxy({}, handler)

export default proxiedGlamorous
```

this would enable users to do 

```js
import glamorous from 'glamorous'

glamorous.a({
  color: 'red'
})

// as well as

glamorous.whatever({
  color: 'red'
})
```

If we also remove the `shouldForwardProperty` check, and remove `<ThemeProvider>` from the export... the glamorous build is less than 2kb gzipped.

But I do not know how this would work...especially without `shouldForwardProperty`

**Comment by vesparny** [comment]
Uhm..maybe proxies are not a good solution tho.

**Comment by kentcdodds** [comment]
Thanks for that analysis! Thanks to @philpl for [noting](https://twitter.com/_philpl/status/851837058582753282) about styled-components:

> I figured we can remove attrs validation in prod => 9.1kb gzip; shall I send over a PR? https://github.com/styled-components/styled-components/pull/681

We may be able to do this, depending on what would actually happen if those props got forwarded onto the DOM nodes... I'm not sure 🤔

**Comment by kentcdodds** [comment]
Oh, and on the subject of proxies. I'd actually thought of it and this is one case where I think they'd actually make sense! However, I think it's a little too early. And if we did, we'd probably just make a separate build for it. Something to think about. Would probably be fun actually :) May require making more modules for our stuff probably. But thanks to Rollup there's basically no cost to doing that so I'm good with that :)

**Comment by vesparny** [comment]
Are you aware of any other technique we could use to generate elements at runtime without breaking the current API?

**Comment by philpl** [comment]
@kentcdodds We were experimenting with proxies, but the user has to add a polyfill/babel plugin to their project and the properties still need to be defined somewhere:

https://github.com/styled-components/styled-components/pull/166

**Comment by vesparny** [comment]
@philpl interesting discussion, thanks for sharing.

I think there is no way to properly polyfill a Proxy.

It would have been a nice solution, too bad.

**Comment by kentcdodds** [comment]
Actually, if we could make it so the tiny glamorous API works with the normal glamorous API, then I think that would be fine. That way we could say: if you really care about things being small/performance, then just use this build instead and limit yourself to this more constrained API. I think that would totally be possible without complicating the code too much... But I think I'd want it all in this one package rather than having totally separate packages... Maybe... Hmmmmm..... Maybe doing a `glamorous-tiny` package would be ok, and would actually simplify things for users and implementors. 🤔

Not a fan of `glam` though 😅 but maybe `glamorousProps` is too long... `glam` is probably fine.

**Comment by vesparny** [comment]
something like

```js
import glamorous from 'glamorous'

import ThemeProvider from 'glamorous/ThemeProvider'

import withTheme from 'glamorous/withTheme'

import glamorousTiny from 'glamorous/tiny'
```

?

**Comment by vesparny** [comment]
`glam` was the fist word that came to my mind...just to stay in context :)

**Comment by paulmolluzzo** [comment]
At that point why not break out the HTML tags and SVG elements as well? This way we're only importing the tags that are required?

`import { h1, h2 } from 'glamorous/headings'`

We'd have to restructure all the HTML/SVG stuff.

**Comment by kentcdodds** [comment]
To be clear:

```javascript
import glamorous from 'glamorous' // the normal lib that has everything in it
import glamorousTiny from 'glamorous/tiny' // the core lib that is basically the glamorous function. Still supports the theme context
```

I think that's actually pretty good! Then for people who really care about perf, they opt-into it, but we would be able to easily reuse our own bits to make the normal lib.

> why not break out the HTML tags and SVG elements as well?

I like that too! Except instead we could rely on tree-shaking and keep all the html tags in a single file:

```javascript
// src/tags.js
import glamorous from './core' // this is glamorous-tiny
export const h1 = glamorous('h1', {propsToForward: h1Props})
export const div = glamorous('div', {propsToForward: divProps}) // propsToForward is new and I think I like it
// etc.
```

Then in the main export, we could just do:

```javascript
// src/glamorous.js
import glamorous from './glamorous'
import ThemeProvider from './theme-provider'
import * as tags from './tags'

const glamorousWrapper = (...args) => glamorous(...args)
// Object.assign all the tags onto glamorousWrapper
// this way we don't muddy up the original `glamorous` function
export default glamorousWrapper
export {ThemeProvider} // and whatever else
```

And we'd have another file that's just:

```javascript
// tiny.js
module.exports = require('./dist/cjs/core') // still uncertain where I'd want the transpiled stuff to go...
```

Lots of thoughts in here. Very interested in what you all think. But I think relying on tree-shaking is the real place to win here.

**Comment by paulmolluzzo** [comment]
@kentcdodds With your suggestion we'd have the ability to do something like this and only have the core `glamorous` lib and single `h1` tag included in the build, right?

```js
import glamorousTiny from 'glamorous/tiny'
import { h1 } from 'glamorous/tags'

// only use h1 tag
```

If this fully leverages tree-shaking I'd always use the tiny version. No component would use _every_ HTML tag.

Sorry if I'm missing some understanding of tree-shaking here.

**Comment by kentcdodds** [comment]
I think you've got it. And you wouldn't even need to import `glamorous/tiny` actually. Just import `glamorous/tags` and that would give you the `h1` for you to use.

Actually.... Now that I'm thinking of this further, we could actually make a babel plugin very much like [this lodash one](https://github.com/lodash/babel-plugin-lodash) where you could write your code like this:

```javascript
import glamorous from 'glamorous'
const MyDiv = glamorous.div()
```

And the plugin could rewrite it like this:

```javascript
import {div} from 'glamorous/tags'
const MyDiv = div()
```

That would be spectacular :smile:

**Comment by kof** [comment]
Glamorous is react specific, you can for sure grab it from react package somewhere.

**Comment by kentcdodds** [comment]
Hi @kof! I'm confused by your comment. What do you mean to say? I'm just unsure I see relevance to the topic...

**Comment by kof** [comment]
edited

**Comment by kentcdodds** [comment]
That sounds like an interesting idea! Anyone wanna dig and see whether React keeps a list of tag/prop names hanging around anywhere?

**Comment by vesparny** [comment]
I can star playing around with all the ideas we came up with in this thread.

@kentcdodds what should I do?
Create a branch and open a PR so we can continue the discussion there?

**Comment by kentcdodds** [comment]
Yep, that sounds like a great start! If we could do this incrementally that would be good. It's going to require quite a few changes, so doing as little as possible to get us to this would probably be easier to review.

**Comment by vesparny** [comment]
Ok cool, hope to able to start tomorrow.
Otherwise after Easter. I'm going to be offline for few days 🎉

**Comment by kentcdodds** [comment]
This is an ongoing effort. I'll go ahead and close this now.
