### ISSUE TITLE
Typescript 2.9 compatibility

### ISSUE THREAD

**Issue by epeli** [paypal/glamorous#422]
Hi, I tried upgrading my project to Typescript 2.9rc but it seems that the typings in Glamorous are not compatible with the new support for symbols and numeric literals in keyof. [See release notes](https://blogs.msdn.microsoft.com/typescript/2018/05/16/announcing-typescript-2-9-rc/)

```
node_modules/glamorous/typings/helpers.d.ts:4:55 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
export type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>
```

Using glamorous 4.13.0.

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
