### ISSUE TITLE
IE11: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by FredericHeem** [paypal/glamorous#48]
"glamor": "2.20.24",
    "glamorous": "3.2.0",
    "react": "15.5.3",

IE11 complains about the missing `Object.assign` even though `babel-polyfill` are imported the top of the app.  The issue is that` glamorous.es.js` is loaded before `babel-polyfill`
Using the babel plugin `transform-object-assign` doesn't help either.

**Comment by kentcdodds** [comment]
You solve this at the application level. Normally you have your main entry file that loads all the things you need for the rest of the app. For example:

```javascript
// entry.js
// this would be your webpack entry..
import 'babel-polyfill'
// import any other global environment things
import bootstrap from './bootstrap'
bootstrap()
```

```javascript
// bootstrap.js
import glamorous from 'glamorous'

// do glamorous stuff
```

This is not something that glamorous can/will solve. Good luck!

**Comment by kentcdodds** [comment]
By the way, thanks for taking the time to try out the project and file an issue. Best of luck to you!

**Comment by FredericHeem** [comment]
The code example is the one followed by my code. For the record, it's in https://github.com/FredericHeem/starhackit/tree/master/client

**Comment by kentcdodds** [comment]
Hmmm... Interesting. I don't see how this could be possible. If you could do a little digging to see why that's not working, glamorous wouldn't be the only library with this issue. Many libraries would have this issue.

Still, I've tested glamorous in IE10 in my own app and it works fine. So I'm convinced it's something in your setup. Let us know what you come up with!

**Comment by FredericHeem** [comment]
Is there any webpack config to share which could show how to support IE11 ?

**Comment by FredericHeem** [comment]
glamorous was in the `vendor.js` webpack bundle, by moving it to the `app.js` bundles instead, `Object.assign` is found. 
By the way, thanks a lot for this project and for the other one too.

**Comment by kentcdodds** [comment]
Glad you got it working. You're welcome for this project! What's the other project you're talking about?
