### ISSUE TITLE
Improve documentation for component composition and fix `css` prop docs

### ISSUE THREAD

**Issue by braposo** [paypal/glamorous#55]
I've been using `glamorous` in a few test applications and got a bit stuck when trying to work out the best way of doing component composition. I couldn't find anything related to this in the documentation so thought about opening this "issue". 

- `glamorous` version: 3.5.0
- `glamor` version: 2.20.24
- `react` version: 15.5.4

**Reproduction:**

https://codesandbox.io/s/OyM7DoxLg

**Problem description:**

I couldn't find an easy way of using the styles from a `glamorous` component without having to create a functional component. Something like `styled-components` does with the [styled()](https://github.com/styled-components/styled-components/blob/master/README.md#overriding-component-styles) helper.

Is this actually possible to do at the moment?

**Suggested solution:**

In the sandbox I suggested a couple of options, but I'm not sure which would be the best.

Doing something like 
```js
const LargeText = glamorous.div([
   Text,
   { fontSize: 24 }
]);
```
would give the flexibility of using a different HTML element if needed, which might be useful.

But going on the `styled-components` route of using something like
```js
const LargeText = withStyles([Text, { fontSize: 24 }]);
```
keeps things simple. I used `withStyles` in line with `withTheme` but alternatively it could maybe be simply `glamorous([Text, { fontSize: 24 }])` since the HTML element would be inferred from the `Text` component. This could have some issues when composing more than one component so not sure about that.

**Side note**

I think I might have found a bug with `cssOverrides` in the sandbox I posted above. If that's the case I can open a separate issue if you want, but maybe I'm just expecting a different behaviour.

Thanks!

**Comment by kentcdodds** [comment]
Hey @braposo! Thanks for filing the issue! You did indeed find a bug, but it's not in the code, it's in the documentation! We refer to `cssOverrides` in our source code to make things more clear, but the prop is actually called `css`! (Would you like to [makeapullrequest.com](http://makeapullrequest.com) to fix that?!)

In addition, we actually do have a composition model similar to styled-components. [I've forked your original example](https://codesandbox.io/s/vgPjZXE9M) to demonstrate both this composition mode as well as the `css` prop.

I'll leave this open to have us update the docs for `cssOverrides` -> `css`. Also, if the composition model is missing from the docs, would you be willing to improve our docs in that way as well?

Thank you!

**Comment by braposo** [comment]
Thanks for the super quick reply @kentcdodds! Yes I can take care of the missing documentation, will open a PR when I'm done, thanks for the suggestion.

I imagined there was something like `glamorous()` for composition but tried a different syntax which wasn't working so wondered if it actually existed at all. Glad it's already part of the library 😝
