### ISSUE TITLE
Add support for `innerRef`

### ISSUE THREAD

**Issue by ElliotChong** [paypal/glamorous#59]
Instead of having to convolutedly wrap components to gain access to the inner element / component of a Glamorous-wrapped node it would be nice to have a convenience prop such as `innerRef` that would proxy down to the underlying element's `ref` property.

i.e.:
```
import { Div } from 'glamorous'

<Div innerRef={(node) => { console.log(node) }} />
```

**Comment by kentcdodds** [comment]
I think I'm on board with this. Certainly enough to review a [pull request](http://makeapullrequest.com) :)

**Comment by ElliotChong** [comment]
Thanks @rrdelaney and @kentcdodds ! :)

I was planning on doing a PR this weekend but was pleasantly surprised to see this already landed, you guys rock!
