### ISSUE TITLE
concat forwardProps option for wrapped components

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#63]
We should probably do the same to `forwardProps` that we do to `styles` [here](https://github.com/paypal/glamorous/blob/424a7e575f4242044b5c891209578f671e193de5/src/index.js#L138). Because otherwise you have to do this:

```javascript
const compProps = ['a', 'b']
const MyComp = glamorous(Comp, {forwardProps: compProps})()
const MyWrapperComp = glamorous(MyComp, {forwardProps: compProps})()
```

I would prefer to only have to do:

```javascript
const compProps = ['a', 'b']
const MyComp = glamorous(Comp, {forwardProps: compProps})()
const MyWrapperComp = glamorous(MyComp)()
```

And the `compProps` are forwarded along because the wrapping `MyComp` has defined them as acceptable props to be forwarded.

**Comment by miguelc1221** [comment]
I'll give this a shot

**Comment by miguelc1221** [comment]
I get an eslint complexity warning of 6 when adding the ternary to `forwardProps`, wondering if I should disable the eslint rule for this line?

**Comment by kentcdodds** [comment]
If there's no way to break up that into a function, then yes, go ahead and use `// eslint-disable-next-line complexity` on the line above the function.
