### ISSUE TITLE
Can we make it possible to use the `css` prop on glamorous.Div, etc?

### ISSUE THREAD

**Issue by tkh44** [paypal/glamorous#74]
Problem description:

I would like to be able to use `css` prop or something similar on built-in GlamorousComponents. My use case is for dynamically generated keys. This is also a great way to write styles quickly.

```jsx
const { Div } = glamorous;

export default ({ theme }) => (
  <Div
    css={{
      cursor: 'pointer',
      fill: theme.color.blue[0],
      height: 27,
      transition: 'all 200ms ease',
      width: 90,
      [theme.breakpoints.mq[1]]: {
        height: 27,
        width: 90,
      },
      [theme.breakpoints.mq[2]]: {
        height: 40,
        width: 134,
      },
      [theme.breakpoints.mq[3]]: {
        height: 50,
        width: 165,
      },
    }}
  >
    <Logo />
  </Div>
);
```

Right now, in our codebase, we just have a set of helpers like `export Div = glamorous.div()`. It would be nice if we could build this functionality in. I have no problem doing the work for a PR, but I would want to know which strategy would be used to enable something like this.

If something like this is built in and I missed it please point it out 😅

**Comment by kentcdodds** [comment]
I like that! Let's do it!

**Comment by kentcdodds** [comment]
Supported :)
