### ISSUE TITLE
html-tags

### ISSUE THREAD

**Issue by thejameskyle** [paypal/glamorous#8]
https://github.com/sindresorhus/html-tags

**Comment by kentcdodds** [comment]
Nice! Thanks for the tip!

**Comment by thejameskyle** [comment]
https://github.com/wooorm/html-element-attributes

**Comment by kentcdodds** [comment]
Oh that's great! That'll let things be a little more specific because they're scoped to the actual element they apply too! Thanks!

**Comment by tsriram** [comment]
@kentcdodds I'd like to work on this if you're not doing it already. Is this to replace `src/dom-elements.js` with `html-tags` module?

**Comment by kentcdodds** [comment]
Yep! That's one half of it! The other half is a little more tricky. But if you want to do that part, be my guest. Make sure to follow the contributing guidelines. Thank you!

**Comment by tsriram** [comment]
Aha! Could you shed some light on the other half please?

**Comment by kentcdodds** [comment]
Why don't we get the first but fine first, then we can talk about the other bit. They're fairly isolated.

**Comment by paulmolluzzo** [comment]
> https://github.com/sindresorhus/html-tags

This doesn't include `svg`-related tags like `path` or `rect`, which [we already have](https://github.com/paypal/glamorous/blob/f75fd4556edf826c927e6ffba20a7f950229b133/src/dom-elements.js#L125-L144).

If we're going to use `html-tags` we should either 1) allow some extension of that list in `glamorous`, or 2) submit a PR upstream to `html-tags` to include the other tags and make it more comprehensive. (I like option 2, but it relies on another project accepting those changes.)

Incidentally, our list doesn't seem comprehensive either, but maybe there's a reason some other elements were omitted (@kentcdodds?). See MDN: https://developer.mozilla.org/en-US/docs/Web/SVG/Element

**Comment by kentcdodds** [comment]
Thanks for looking into that! I suggest we submit a pull request to html-tags to support all the attributes the are. If some were omitted it's not intentional by me. I just copied styled-components there. We should probably let @mxstbr know.

**Comment by paulmolluzzo** [comment]
> Thanks for looking into that! I suggest we submit a pull request to html-tags to support all the attributes the are. If some were omitted it's not intentional by me. I just copied styled-components there. We should probably let @mxstbr know.

It _could_ be intentional by those projects. There is this project, https://github.com/davidohlin/svg-elements, so perhaps it was just about keeping a confined scope.

Maybe we can source these projects as they are, `concat` the arrays, then deduplicate? Best of all worlds?

**Comment by kentcdodds** [comment]
That approach sounds good to me too 👍

**Comment by wooorm** [comment]
Next to `html-element-attributes`, I also made [`svg-tag-names`](https://github.com/wooorm/svg-tag-names) and [`html-tag-names`](https://github.com/wooorm/html-tag-names) (not knowing there are apparently many projects like this!). Both projects include all tag-names from their respective specs!

Just wanted to add another option :)

**Comment by tsriram** [comment]
So which one should be used? :confused:

**Comment by kentcdodds** [comment]
I've got done thoughts. Give me a few minutes

**Comment by kentcdodds** [comment]
So I'd say that creating component factories for every `svg` tag name is out of scope... It's really easy to do it manually:

```javascript
const MyFeColorMatrix = glamorous('feColorMatrix')({/* my styles */})
```

So I'm going to just say no on those. Most people wont use them anyway. And if they really want to have it on `glamorous` they can just do the same thing [we do](https://github.com/paypal/glamorous/blob/f75fd4556edf826c927e6ffba20a7f950229b133/src/index.js#L117-L126). It's pretty straightforward.

It looks like https://github.com/wooorm/html-tag-names is most up to date. So I'm going to go ahead and ask that we just use that one. We should be able to simply swap [this](https://github.com/paypal/glamorous/blob/master/src/index.js#L8) import with an import of that library and delete `dom-elements.js`.

I'll create a new issue for the attributes one.

Thanks!
