### ISSUE TITLE
Add Notes to readme around limitations of typescript support

### ISSUE THREAD

**Issue by luke-john** [paypal/glamorous#83]
- `glamorous` version: [master@20170424](https://github.com/paypal/glamorous/tree/72c0305a3b2aa48b0447d56846e807ec7bd7105a)

Problem description:

The current bundled typescript definitions are incomplete and based around the needs of the developers who contributed them.

Whilst this is true of the definitions of many non typescript projects, it could still be a pain point for consumers.

Suggested solution:

It would nice to add a small section to the README with a brief overview of what the definitions do and don't include currently.

I'll likely be able to open a PR in a few days, however if someone is able to work on this before then, that would be great 👍 .

**Comment by paulmolluzzo** [comment]
Thanks for opening the issue and suggestion! PR certainly welcome!

// @luke-john

**Comment by ErikCupal** [comment]
👍 I'll definetely take a look at it if you open the PR

**Comment by luke-john** [comment]
Sorry I'd forgotten about this one. Though in the week since creation a some of the limitations have been solved :) .

Currently the main ones are as follows;

> built-in GlamorousComponents

0 support

> built-in DOM component factories

only have support for div and svg

> * pseudo-class
> * pseudo-element
> * Relational CSS Selectors
> * Media Queries

All of these work, however you only get typesafety and intellisense on simple css key props (see https://github.com/paypal/glamorous/blob/master/typings/css-properties.d.ts).

potentially we could add support via helper methods along the lines of http://typestyle.io/.  probs needs discussion.

Also as @ErikCupal pointed out in pr this may become possible in future with regex typings https://github.com/Microsoft/TypeScript/issues/6579

> * Animations

possible support via glamors typings https://github.com/threepointone/glamor/blob/master/index.d.ts

**Comment by sammkj** [comment]
I think we should hold off writing definitions for built-in Glamorous components because of [this](https://github.com/paypal/glamorous/issues/42).

**Comment by ErikCupal** [comment]
@sammkj Well, I don't think there is a problem with library size. The typescript typings are never included in the final module (either as single js file or as part of webpack build). They simply cannot add any library size because they are just linting informations. The tests, examples or docs also don't add up the size. Hope it's clear :).

**Comment by sammkj** [comment]
@ErikCupal ah, I think you have mistaken my reference to the issue. If you look through the issue, there might be a change in glamorous APIs. I was just thinking we should wait and see before we write more definitions.

**Comment by kentcdodds** [comment]
Ah, I should have mentioned, all the changes to the glamorous APIs have been made. The full API is now:

```javascript
glamorous.div(
  {}, // objects
  undefined,
  null,
  'class-name', // strings (this was the only change from what was already there
  () => ({}), // functions that return objects
  () => ('class-name2') // functions that return strings, I guess that is a change too...
)
```

I don't expect the API to change from that ever.

**Comment by ErikCupal** [comment]
@sammkj Aaah sorry, yes I have mistaken it. I see.
@kentcdodds Ok, thanks :)
@sammkj @luke-john It looks we can start writing typings since all API changes are made. Am I right?
