### ISSUE TITLE
Make glamorous work out of the box with preact

### ISSUE THREAD

**Issue by aaronjensen** [paypal/glamorous#85]
Original issue: https://github.com/developit/preact/pull/653#issuecomment-297111106

At the moment there are a couple of snags while working with preact:

1. preact doesn't handle the `autoFocus` attribute in the same way that react does, and, at the moment, [does not declare that `autoFocus` (it uses `autofocus`)](https://github.com/developit/preact/pull/653) is a valid prop on html intrinsic elements in its typescript definition. Glamorous, on the other hand, only whitelists `autoFocus` as a prop to be passed on to the intrinsic element, so it does not pass `autofocus` on. @kentcdodds suggested using `forwardProps`, but I'm not sure how to use that in this case just yet and it seems like it'd be a hack.
2. React is a peer-dependency of glamorous, which means you get a warning if you don't have it installed.
3. Glamorous requires `preact-compat`. Ideally it would work w/o it.

**Comment by vesparny** [comment]
I've created a small glamorous version for preact that skips all the attributes check.

https://www.npmjs.com/package/preact-glam

I will dig into how to enable compatibility with preact for glamorous out of the box. That would be awesome
