### ISSUE TITLE
Built-in rect component doesn't render size/position attributes

### ISSUE THREAD

**Issue by AlteredConstants** [paypal/glamorous#91]
- `glamorous` version: 3.11.2
- `glamor` version: 2.20.24
- `react` version: 15.5.4

Relevant code.

```javascript
const BuiltinComponentRect = glamorous.Rect;
const BuiltinFactoryRect = glamorous.rect({ fill: "blue" });
const CustomRect = glamorous("rect", {
  forwardProps: ["x", "width", "height"]
})({ fill: "orange" });

ReactDOM.render(
  <div>
    <svg width="250" height="50">
      <rect x="0" width="50" height="50" fill="red" />
      <BuiltinComponentRect x="60" width="50" height="50" fill="green" />
      <BuiltinFactoryRect x="110" width="50" height="50" />
      <CustomRect x="170" width="50" height="50" />
    </svg>
  </div>,
  document.getElementById("root")
);
```

What you did:

N/A

What happened:

In Firefox and Edge, the green (built-in component) and blue (built-in factory-created component) boxes do not render correctly (they have no size) and in Chrome, the blue box doesn't render.

Reproduction:

https://codepen.io/alteredconstants/pen/YVZByv?editors=0010

Problem description:

I could very well be misunderstanding something, but it appears that the `x`, `width`, and `height` props are not being passed on to the underlying `<rect>` element with the built-in component/component factory. Inspecting the DOM in Chrome, it looks like `glamorous.Rect` is rendering those props as styles rather than attributes (which appears to be unsupported in Firefox) and the `glamorous.rect`-generated component simply doesn't render them at all.

Suggested solution:

I haven't used this library much (I like it so far!) but the docs suggest that non-style props on the built-in components should be passed through as attributes (e.g. `href` on `<a>`). I'm guessing these size/position ones aren't because they're also style properties? Considering this doesn't currently work on Firefox and Edge, I'd suggest adding those as exceptions for SVG components as they are effectively unusable otherwise.

Or since that might break things for people who only care about Chrome, maybe just a note about this in the docs recommending using the custom component syntax in this case.

**Comment by kentcdodds** [comment]
Thanks! Probably a bug in our react-html-attributes dependency actually... On mobile now, but if you want to look into that, that'd be great!

**Comment by jackyho112** [comment]
I believe it is. I will take a look!

**Comment by AlteredConstants** [comment]
Yeah, it looks like that library only handles the `<svg>` element by assigning every property React mentions for all of the SVG components.

That said, there will probably still need to be some changes here:
https://github.com/paypal/glamorous/blob/master/src/should-forward-property.js#L46
to include the various other SVG components and their specific exceptions. The [`cssProps` array](https://github.com/paypal/glamorous/blob/master/src/should-forward-property.js#L18) might also need to be expanded to include `x`, `y`, and possibly others. Not sure how exactly that array was defined.

**Comment by jackyho112** [comment]
I got a PR up but it's not ready to be merged yet. Some React elements share the same tag names with some HTML elements, which is why some tests are breaking. Any idea on how to deal with such scenarios?
