### ISSUE TITLE
export 'Div' was not found in 'glamorous'

### ISSUE THREAD

**Issue by brianyang** [paypal/glamorous#95]
- `glamorous` version: ^3.12.0
- `glamor` version: ^2.20.24
- `react` version: 15.4.1

Relevant code.

```javascript
// importing documented built-in
import {Div} from 'glamorous'

// class method
render() {
  <Div />
}
```

What you did:

importing built-in HTML tag as defined in the documentation 

What happened:

throws an error and prevents the app from building. 
`export 'Div was not found in 'glamorous'` 

Reproduction:

not able to reproduce on codesandbox.io

Problem description:

the code was using the built-in html tags as defined in the docs. when refactoring the same code in a new project, I cam across this error.

Suggested solution:

skimming through this thread:
https://github.com/paypal/glamorous/issues/42
... it became obvious a simple way to get around this was to define these tags as methods of glamorous. 

```js
// before
import {Div} from 'glamorous'

// after
import glamorous from 'glamorous'
const Div = glamorous.div()
```

**Comment by kentcdodds** [comment]
Hi! Yes, importing the built in components is not supported and there are no plans to add support. Feel free to open a pull request if you feel like the docs could be improved in this regard. Thanks!

**Comment by kentcdodds** [comment]
Oh and actually, this is what you should do:

import glamorous from 'glamorous'
const {Div} = glamorous
