### ISSUE TITLE
textArea vs. textarea

### ISSUE THREAD

**Issue by newyork-anthonyng** [paypal/glamorous#99]
- `glamorous` version: 3.13.1
- `glamor` version: 2.20.24
- `react` version: 15.5.4

#### Relevant code.

```javascript
import glamorous from 'glamorous'

const CorrectTextArea = glamorous.textarea(); // => renders as expected with props
const IncorrectTextArea = glamorous.textArea(); // => renders as a textarea without props
```

#### What you did:
I wanted a glamorous textArea, and accidentally used `glamorous.textArea()`, instead of `glamorous.textarea()`.

#### What happened:
`textArea` is a valid SVG tag, so `glamorous` didn't throw.

From what I saw, it seems like React Components are case-insensitive (other than the first letter). React renders `<textArea />`, `<textarea />`, `<tEXTAREA>` all the same (when not wrapped inside an `<svg />` tag).

#### Reproduction:

Link to [Sandbox](https://codesandbox.io/s/zGvy7Jk8)

#### Problem description:
I was confused at first because my `glamorous.textArea()` still rendered as expected, except none of my `props` were getting passed down. This is because of how our `should-forward-property` function is running its check.

#### Suggested solution:
One solution is to add a conditional inside of `should-forward-property` to handle this.
However, I'm not sure if this is a case that we want to handle at all. Should we just expect the user to know the correct case-sensitive spelling for `textarea`?

**Comment by kentcdodds** [comment]
Just to be clear, `glamorous.textArea` exists because it's an SVG element and `glamorous.textarea` exists because it's an HTML element?

If that's the case, I'm unsure of how to really solve this problem :-/ Because we want to support both... 🤔 I'm not sure I understand your suggested solution though. Could you be more specific?

**Comment by kentcdodds** [comment]
Also, thanks!

**Comment by newyork-anthonyng** [comment]
> Just to be clear, glamorous.textArea exists because it's an SVG element and glamorous.textarea exists because it's an HTML element?

Yes, correct!

> I'm not sure I understand your suggested solution though. Could you be more specific?

Now that I'm thinking about it, the solution I had wouldn't work. I was thinking of changing this [line](https://github.com/paypal/glamorous/blob/master/src/should-forward-property.js#L39) to something like:

```js
elementAttributes = reactHTMLAttributes[tagName.toLowerCase()] || []
```

But like you said, we would lose support for the `svg textArea`.

I think we can close this ticket. I hope this helps anyone else who trips up on a similar problem.
And I'm glad I just learned that HTML tagnames are case-insensitive 😅
